// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _image_filter_borderInterpolate_HH_
#define _image_filter_borderInterpolate_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct image_filter_borderInterpolate : public sc_module {
    // Port declarations 6
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<12> > p;
    sc_in< sc_lv<11> > len;
    sc_out< sc_lv<13> > ap_return;
    sc_in< sc_logic > ap_ce;


    // Module declarations
    image_filter_borderInterpolate(sc_module_name name);
    SC_HAS_PROCESS(image_filter_borderInterpolate);

    ~image_filter_borderInterpolate();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<12> > p_p2_fu_91_p3;
    sc_signal< sc_lv<12> > p_p2_reg_198;
    sc_signal< sc_lv<1> > tmp_3_fu_103_p2;
    sc_signal< sc_lv<1> > tmp_3_reg_203;
    sc_signal< sc_lv<1> > sel_tmp2_fu_145_p2;
    sc_signal< sc_lv<1> > sel_tmp2_reg_208;
    sc_signal< sc_lv<1> > sel_tmp6_demorgan_fu_151_p2;
    sc_signal< sc_lv<1> > sel_tmp6_demorgan_reg_213;
    sc_signal< sc_lv<13> > newSel9_fu_157_p3;
    sc_signal< sc_lv<13> > newSel9_reg_218;
    sc_signal< sc_lv<1> > tmp_fu_37_p3;
    sc_signal< sc_lv<12> > len_cast4_cast_fu_51_p1;
    sc_signal< sc_lv<1> > tmp_s_fu_55_p2;
    sc_signal< sc_lv<1> > rev_fu_45_p2;
    sc_signal< sc_lv<1> > tmp_80_fu_77_p3;
    sc_signal< sc_lv<12> > p_assign_fu_85_p2;
    sc_signal< sc_lv<12> > tmp_4_fu_109_p3;
    sc_signal< sc_lv<13> > tmp_4_cast_cast_fu_117_p1;
    sc_signal< sc_lv<13> > tmp_5_fu_121_p2;
    sc_signal< sc_lv<13> > p_p2_cast_cast_fu_99_p1;
    sc_signal< sc_lv<1> > tmp_not_fu_133_p2;
    sc_signal< sc_lv<1> > tmp_1_fu_71_p2;
    sc_signal< sc_lv<1> > sel_tmp1_fu_139_p2;
    sc_signal< sc_lv<1> > or_cond_82_fu_61_p2;
    sc_signal< sc_lv<13> > p_cast_cast_fu_67_p1;
    sc_signal< sc_lv<13> > p_assign_1_fu_127_p2;
    sc_signal< sc_lv<1> > sel_tmp6_fu_165_p2;
    sc_signal< sc_lv<1> > sel_tmp7_fu_170_p2;
    sc_signal< sc_lv<12> > newSel_fu_175_p3;
    sc_signal< sc_lv<1> > or_cond_fu_186_p2;
    sc_signal< sc_lv<13> > newSel_cast_fu_182_p1;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<11> ap_const_lv11_1;
    static const sc_lv<12> ap_const_lv12_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<13> ap_const_lv13_1FFE;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_return();
    void thread_len_cast4_cast_fu_51_p1();
    void thread_newSel9_fu_157_p3();
    void thread_newSel_cast_fu_182_p1();
    void thread_newSel_fu_175_p3();
    void thread_or_cond_82_fu_61_p2();
    void thread_or_cond_fu_186_p2();
    void thread_p_assign_1_fu_127_p2();
    void thread_p_assign_fu_85_p2();
    void thread_p_cast_cast_fu_67_p1();
    void thread_p_p2_cast_cast_fu_99_p1();
    void thread_p_p2_fu_91_p3();
    void thread_rev_fu_45_p2();
    void thread_sel_tmp1_fu_139_p2();
    void thread_sel_tmp2_fu_145_p2();
    void thread_sel_tmp6_demorgan_fu_151_p2();
    void thread_sel_tmp6_fu_165_p2();
    void thread_sel_tmp7_fu_170_p2();
    void thread_tmp_1_fu_71_p2();
    void thread_tmp_3_fu_103_p2();
    void thread_tmp_4_cast_cast_fu_117_p1();
    void thread_tmp_4_fu_109_p3();
    void thread_tmp_5_fu_121_p2();
    void thread_tmp_80_fu_77_p3();
    void thread_tmp_fu_37_p3();
    void thread_tmp_not_fu_133_p2();
    void thread_tmp_s_fu_55_p2();
};

}

using namespace ap_rtl;

#endif
