// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module image_filter_Filter2D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_src_rows_V_read,
        p_src_cols_V_read,
        p_src_data_stream_V_dout,
        p_src_data_stream_V_empty_n,
        p_src_data_stream_V_read,
        p_dst_data_stream_V_din,
        p_dst_data_stream_V_full_n,
        p_dst_data_stream_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 5'b1;
parameter    ap_ST_st2_fsm_1 = 5'b10;
parameter    ap_ST_st3_fsm_2 = 5'b100;
parameter    ap_ST_pp0_stg0_fsm_3 = 5'b1000;
parameter    ap_ST_st9_fsm_4 = 5'b10000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv11_5 = 11'b101;
parameter    ap_const_lv11_2 = 11'b10;
parameter    ap_const_lv11_7FD = 11'b11111111101;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv11_7FF = 11'b11111111111;
parameter    ap_const_lv12_1 = 12'b1;
parameter    ap_const_lv13_1FFE = 13'b1111111111110;
parameter    ap_const_lv13_2 = 13'b10;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv11_4 = 11'b100;
parameter    ap_const_lv12_FFC = 12'b111111111100;
parameter    ap_const_lv12_FFF = 12'b111111111111;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv12_FFB = 12'b111111111011;
parameter    ap_const_lv12_5 = 12'b101;
parameter    ap_const_lv12_FFA = 12'b111111111010;
parameter    ap_const_lv12_6 = 12'b110;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv9_0 = 9'b000000000;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [11:0] p_src_rows_V_read;
input  [11:0] p_src_cols_V_read;
input  [7:0] p_src_data_stream_V_dout;
input   p_src_data_stream_V_empty_n;
output   p_src_data_stream_V_read;
output  [7:0] p_dst_data_stream_V_din;
input   p_dst_data_stream_V_full_n;
output   p_dst_data_stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_V_read;
reg p_dst_data_stream_V_write;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm = 5'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_23;
reg   [10:0] p_025_0_i_reg_295;
wire   [10:0] tmp_1_fu_359_p1;
reg   [10:0] tmp_1_reg_1567;
wire   [10:0] heightloop_fu_367_p2;
reg   [10:0] heightloop_reg_1572;
wire   [10:0] widthloop_fu_373_p2;
reg   [10:0] widthloop_reg_1577;
wire   [11:0] tmp_17_cast_fu_385_p1;
reg   [11:0] tmp_17_cast_reg_1582;
wire   [1:0] p_neg226_i_cast_fu_393_p2;
reg   [1:0] p_neg226_i_cast_reg_1587;
wire   [10:0] ref_fu_399_p2;
reg   [10:0] ref_reg_1593;
wire   [11:0] ref_cast_fu_405_p1;
reg   [11:0] ref_cast_reg_1598;
wire   [11:0] len_cast4_i_cast_fu_409_p1;
reg   [11:0] len_cast4_i_cast_reg_1603;
wire  signed [14:0] tmp_5_cast_i_fu_429_p1;
reg  signed [14:0] tmp_5_cast_i_reg_1609;
wire   [11:0] len_cast4_i30_cast_fu_433_p1;
reg   [11:0] len_cast4_i30_cast_reg_1614;
wire   [12:0] tmp_5_i1_fu_447_p2;
reg   [12:0] tmp_5_i1_reg_1623;
wire   [1:0] tmp_5_i2_fu_465_p2;
reg   [1:0] tmp_5_i2_reg_1628;
wire   [10:0] i_V_fu_480_p2;
reg   [10:0] i_V_reg_1637;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_76;
wire   [0:0] tmp_7_fu_486_p2;
reg   [0:0] tmp_7_reg_1642;
wire   [0:0] tmp_6_fu_475_p2;
reg   [0:0] tmp_15_reg_1647;
wire   [1:0] tmp_19_fu_581_p1;
reg   [1:0] tmp_19_reg_1651;
wire   [1:0] tmp_25_fu_605_p3;
reg   [1:0] tmp_25_reg_1657;
wire   [1:0] tmp_31_fu_670_p1;
reg   [1:0] tmp_31_reg_1663;
wire   [1:0] sel_tmp_i2_fu_684_p3;
reg   [1:0] sel_tmp_i2_reg_1668;
wire   [0:0] sel_tmp7_i2_fu_704_p2;
reg   [0:0] sel_tmp7_i2_reg_1673;
wire   [1:0] tmp_32_fu_710_p1;
reg   [1:0] tmp_32_reg_1678;
wire   [1:0] tmp_36_fu_771_p1;
reg   [1:0] tmp_36_reg_1685;
wire   [0:0] sel_tmp7_i3_fu_797_p2;
reg   [0:0] sel_tmp7_i3_reg_1690;
wire   [1:0] newSel_fu_803_p3;
reg   [1:0] newSel_reg_1695;
wire   [0:0] brmerge_fu_811_p2;
reg   [0:0] brmerge_reg_1700;
wire   [0:0] sel_tmp8_fu_821_p2;
reg   [0:0] sel_tmp8_reg_1704;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_114;
wire   [0:0] sel_tmp1_fu_825_p2;
reg   [0:0] sel_tmp1_reg_1709;
wire   [0:0] sel_tmp3_fu_841_p2;
reg   [0:0] sel_tmp3_reg_1714;
wire   [0:0] sel_tmp5_fu_846_p2;
reg   [0:0] sel_tmp5_reg_1719;
wire   [1:0] locy_2_t_fu_857_p2;
reg   [1:0] locy_2_t_reg_1724;
wire   [0:0] tmp_8_fu_866_p2;
reg   [0:0] tmp_8_reg_1728;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_3;
reg    ap_sig_bdd_131;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg   [0:0] ap_reg_ppstg_tmp_8_reg_1728_pp0_it1;
reg   [0:0] or_cond7_reg_1769;
reg   [0:0] ap_reg_ppstg_or_cond7_reg_1769_pp0_it1;
reg    ap_sig_bdd_150;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg   [0:0] or_cond219_i_reg_1737;
reg   [0:0] ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it3;
reg    ap_sig_bdd_162;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg   [0:0] ap_reg_ppstg_tmp_8_reg_1728_pp0_it2;
wire   [10:0] j_V_fu_871_p2;
wire   [0:0] or_cond219_i_fu_893_p2;
reg   [0:0] ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it1;
reg   [0:0] ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it2;
wire   [11:0] ImagLoc_x_fu_898_p2;
reg   [11:0] ImagLoc_x_reg_1741;
wire   [0:0] or_cond_i1_fu_927_p2;
reg   [0:0] or_cond_i1_reg_1746;
wire   [0:0] tmp_40_fu_933_p3;
reg   [0:0] tmp_40_reg_1751;
reg   [0:0] ap_reg_ppstg_tmp_40_reg_1751_pp0_it1;
wire   [11:0] p_p2_i_fu_947_p3;
reg   [11:0] p_p2_i_reg_1755;
wire   [0:0] sel_tmp7_i_fu_972_p2;
reg   [0:0] sel_tmp7_i_reg_1760;
wire   [0:0] tmp_18_fu_984_p2;
reg   [0:0] tmp_18_reg_1765;
reg   [0:0] ap_reg_ppstg_tmp_18_reg_1765_pp0_it1;
wire   [0:0] or_cond7_fu_989_p2;
wire   [0:0] tmp_20_fu_995_p2;
reg   [0:0] tmp_20_reg_1773;
reg   [0:0] ap_reg_ppstg_tmp_20_reg_1773_pp0_it1;
wire   [1:0] col_assign_fu_1000_p2;
reg   [1:0] col_assign_reg_1777;
reg   [1:0] ap_reg_ppstg_col_assign_reg_1777_pp0_it1;
reg   [10:0] k_buf_0_val_0_addr_reg_1783;
reg   [10:0] k_buf_0_val_1_addr_reg_1789;
reg   [10:0] k_buf_0_val_2_addr_reg_1795;
wire   [1:0] col_assign_2_fu_1049_p2;
reg   [1:0] col_assign_2_reg_1801;
reg   [7:0] src_kernel_win_0_val_0_1_6_reg_1807;
reg   [7:0] src_kernel_win_0_val_2_1_9_reg_1812;
reg   [7:0] src_kernel_win_0_val_1_1_6_reg_1817;
reg   [0:0] isneg_reg_1822;
wire   [7:0] p_Val2_3_fu_1392_p1;
reg   [7:0] p_Val2_3_reg_1828;
wire   [0:0] not_i_i_i_fu_1406_p2;
reg   [0:0] not_i_i_i_reg_1833;
wire   [10:0] k_buf_0_val_0_address0;
reg    k_buf_0_val_0_ce0;
wire   [7:0] k_buf_0_val_0_q0;
wire   [10:0] k_buf_0_val_0_address1;
reg    k_buf_0_val_0_ce1;
reg    k_buf_0_val_0_we1;
wire   [7:0] k_buf_0_val_0_d1;
wire   [10:0] k_buf_0_val_1_address0;
reg    k_buf_0_val_1_ce0;
wire   [7:0] k_buf_0_val_1_q0;
wire   [10:0] k_buf_0_val_1_address1;
reg    k_buf_0_val_1_ce1;
reg    k_buf_0_val_1_we1;
wire   [7:0] k_buf_0_val_1_d1;
wire   [10:0] k_buf_0_val_2_address0;
reg    k_buf_0_val_2_ce0;
wire   [7:0] k_buf_0_val_2_q0;
wire   [10:0] k_buf_0_val_2_address1;
reg    k_buf_0_val_2_ce1;
reg    k_buf_0_val_2_we1;
wire   [7:0] k_buf_0_val_2_d1;
reg   [10:0] p_012_0_i_reg_284;
reg    ap_sig_cseq_ST_st9_fsm_4;
reg    ap_sig_bdd_298;
wire   [63:0] tmp_13_fu_1042_p1;
reg   [7:0] src_kernel_win_0_val_0_1_fu_138;
wire   [7:0] src_kernel_win_0_val_0_0_fu_1075_p3;
wire   [7:0] col_buf_0_val_0_0_9_fu_1135_p3;
reg   [7:0] src_kernel_win_0_val_0_2_fu_142;
reg   [7:0] col_buf_0_val_0_0_3_fu_146;
reg   [7:0] src_kernel_win_0_val_2_1_fu_150;
reg   [7:0] src_kernel_win_0_val_1_1_fu_154;
wire   [7:0] src_kernel_win_0_val_1_0_fu_1090_p3;
wire   [7:0] right_border_buf_0_val_1_2_11_fu_1152_p3;
reg   [7:0] src_kernel_win_0_val_1_2_fu_158;
reg   [7:0] col_buf_0_val_0_0_5_fu_162;
reg   [7:0] src_kernel_win_0_val_2_2_fu_166;
reg   [7:0] col_buf_0_val_0_0_6_fu_170;
reg   [7:0] right_border_buf_0_val_1_2_1_fu_174;
wire   [7:0] right_border_buf_0_val_1_2_8_fu_1244_p3;
reg   [7:0] right_border_buf_0_val_1_2_2_fu_178;
wire   [7:0] right_border_buf_0_val_1_2_6_fu_1235_p3;
reg   [7:0] right_border_buf_0_val_1_2_7_fu_182;
wire   [7:0] right_border_buf_0_val_1_2_4_fu_1218_p3;
reg   [7:0] right_border_buf_0_val_0_0_fu_198;
reg   [7:0] right_border_buf_0_val_0_1_fu_202;
reg   [7:0] right_border_buf_0_val_0_2_fu_206;
wire   [10:0] tmp_2_fu_363_p1;
wire   [10:0] tmp_4_fu_379_p2;
wire   [1:0] tmp_3_fu_389_p1;
wire   [11:0] tmp_5_fu_413_p2;
wire   [12:0] tmp_4_cast_i_cast_fu_419_p1;
wire   [12:0] tmp_5_i_fu_423_p2;
wire   [11:0] tmp_10_fu_437_p2;
wire   [12:0] tmp_4_cast_i46_cast_fu_443_p1;
wire   [0:0] tmp_11_fu_453_p1;
wire   [1:0] tmp_4_i2_fu_457_p3;
wire   [11:0] tmp_18_cast_fu_471_p1;
wire   [11:0] ImagLoc_y_fu_492_p2;
wire   [10:0] tmp_12_fu_504_p4;
wire   [0:0] icmp_fu_514_p2;
wire   [0:0] tmp_14_fu_520_p2;
wire   [10:0] tmp_16_fu_551_p1;
wire   [12:0] p_p2_cast1_i40_cast_fu_555_p1;
wire   [0:0] tmp_i1_fu_546_p2;
wire   [0:0] tmp_3_i1_fu_559_p2;
wire   [0:0] sel_tmp6_i1_fu_569_p2;
wire   [10:0] p_i_fu_539_p3;
wire   [12:0] p_assign_2_fu_564_p2;
wire   [1:0] tmp_22_fu_589_p1;
wire   [1:0] tmp_23_fu_593_p1;
wire   [0:0] sel_tmp7_i1_fu_575_p2;
wire   [1:0] tmp_21_fu_585_p1;
wire   [1:0] tmp_24_fu_597_p3;
wire   [11:0] y_1_fu_613_p2;
wire   [0:0] tmp_27_fu_619_p3;
wire   [0:0] tmp_i2_fu_633_p2;
wire   [0:0] rev_fu_627_p2;
wire   [0:0] tmp_30_fu_648_p3;
wire   [11:0] p_assign_3_fu_656_p2;
wire   [11:0] p_p2_i1_fu_662_p3;
wire   [0:0] or_cond_i2_fu_638_p2;
wire   [1:0] tmp_29_fu_644_p1;
wire   [1:0] p_assign_1_cast_i_fu_679_p2;
wire   [0:0] tmp_i2_not_fu_692_p2;
wire   [0:0] tmp_3_i2_fu_674_p2;
wire   [0:0] sel_tmp6_i2_fu_698_p2;
wire   [11:0] y_1_1_fu_714_p2;
wire   [0:0] tmp_33_fu_720_p3;
wire   [0:0] tmp_i3_fu_734_p2;
wire   [0:0] rev1_fu_728_p2;
wire   [0:0] tmp_35_fu_749_p3;
wire   [11:0] p_assign_4_fu_757_p2;
wire   [11:0] p_p2_i2_fu_763_p3;
wire   [0:0] tmp_i3_not_fu_785_p2;
wire   [0:0] tmp_3_i3_fu_775_p2;
wire   [0:0] sel_tmp6_i3_fu_791_p2;
wire   [0:0] or_cond_i3_fu_739_p2;
wire   [1:0] tmp_34_fu_745_p1;
wire   [1:0] p_assign_1_cast_i1_fu_780_p2;
wire   [0:0] tmp_s_fu_498_p2;
wire   [0:0] or_cond6_fu_525_p2;
wire   [1:0] tmp_26_fu_817_p2;
wire   [1:0] p_assign_2_i2_fu_831_p3;
wire   [1:0] locy_1_t_fu_836_p2;
wire   [1:0] newSel1_fu_852_p3;
wire   [9:0] tmp_37_fu_877_p4;
wire   [0:0] icmp1_fu_887_p2;
wire   [11:0] tmp_21_cast_fu_862_p1;
wire   [0:0] tmp_39_fu_908_p3;
wire   [0:0] tmp_i_fu_922_p2;
wire   [0:0] rev2_fu_916_p2;
wire   [11:0] p_assign_fu_941_p2;
wire   [0:0] tmp_i_not_fu_960_p2;
wire   [0:0] tmp_3_i_fu_955_p2;
wire   [0:0] sel_tmp6_i_fu_966_p2;
wire   [0:0] tmp_17_fu_978_p2;
wire   [1:0] tmp_38_fu_904_p1;
wire  signed [13:0] p_p2_i_cast_fu_1008_p1;
wire   [14:0] p_p2_cast1_i_cast_fu_1011_p1;
wire  signed [14:0] p_cast_i_cast_fu_1005_p1;
wire  signed [14:0] p_assign_1_fu_1015_p2;
wire   [14:0] sel_tmp_i_fu_1020_p3;
wire   [14:0] p_assign_2_i_fu_1027_p3;
wire  signed [31:0] x_fu_1034_p1;
wire   [1:0] tmp_41_fu_1038_p1;
wire   [7:0] sel_tmp9_fu_1068_p3;
wire   [7:0] sel_tmp4_fu_1083_p3;
wire   [0:0] sel_tmp_fu_1117_p2;
wire   [0:0] sel_tmp2_fu_1130_p2;
wire   [7:0] col_buf_0_val_0_0_2_fu_1122_p3;
wire   [7:0] right_border_buf_0_val_1_2_fu_1144_p3;
wire   [0:0] sel_tmp6_fu_1200_p2;
wire   [0:0] sel_tmp7_fu_1213_p2;
wire   [7:0] right_border_buf_0_val_1_2_3_fu_1205_p3;
wire   [7:0] right_border_buf_0_val_1_2_5_fu_1227_p3;
wire   [8:0] tmp_147_0_2_cast_fu_1290_p1;
wire   [8:0] OP1_V_0_cast_fu_1286_p1;
wire   [8:0] p_Val2_3_0_2_fu_1294_p2;
wire   [8:0] p_shl_fu_1304_p3;
wire   [9:0] p_shl_cast_fu_1312_p1;
wire   [9:0] p_Val2_s_fu_1316_p2;
wire   [8:0] p_Val2_114_2_fu_1326_p3;
wire   [8:0] OP1_V_2_cast_fu_1338_p1;
wire   [8:0] p_Val2_2_fu_1342_p2;
wire  signed [10:0] tmp_147_1_cast_fu_1322_p1;
wire  signed [10:0] tmp_147_2_cast_fu_1348_p1;
wire  signed [9:0] p_Val2_3_0_2_cast_cast_fu_1300_p1;
wire   [9:0] tmp_147_2_2_cast_cast_fu_1352_p1;
wire  signed [9:0] tmp26_fu_1362_p2;
wire  signed [10:0] tmp132_cast_fu_1368_p1;
wire   [10:0] tmp_147_1_cast_37_fu_1334_p1;
wire  signed [10:0] tmp27_fu_1372_p2;
wire  signed [10:0] tmp25_fu_1356_p2;
wire  signed [10:0] p_Val2_1_fu_1378_p2;
wire   [2:0] tmp_28_fu_1396_p4;
wire   [0:0] tmp_i_i_fu_1424_p2;
wire   [0:0] overflow_fu_1429_p2;
wire   [0:0] tmp_i_i_38_fu_1442_p2;
wire   [7:0] p_mux_i_i_cast_fu_1434_p3;
reg   [4:0] ap_NS_fsm;


image_filter_Filter2D_1_k_buf_0_val_0 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_0_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_0_val_0_address0 ),
    .ce0( k_buf_0_val_0_ce0 ),
    .q0( k_buf_0_val_0_q0 ),
    .address1( k_buf_0_val_0_address1 ),
    .ce1( k_buf_0_val_0_ce1 ),
    .we1( k_buf_0_val_0_we1 ),
    .d1( k_buf_0_val_0_d1 )
);

image_filter_Filter2D_1_k_buf_0_val_0 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_1_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_0_val_1_address0 ),
    .ce0( k_buf_0_val_1_ce0 ),
    .q0( k_buf_0_val_1_q0 ),
    .address1( k_buf_0_val_1_address1 ),
    .ce1( k_buf_0_val_1_ce1 ),
    .we1( k_buf_0_val_1_we1 ),
    .d1( k_buf_0_val_1_d1 )
);

image_filter_Filter2D_1_k_buf_0_val_0 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_2_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_0_val_2_address0 ),
    .ce0( k_buf_0_val_2_ce0 ),
    .q0( k_buf_0_val_2_q0 ),
    .address1( k_buf_0_val_2_address1 ),
    .ce1( k_buf_0_val_2_ce1 ),
    .we1( k_buf_0_val_2_we1 ),
    .d1( k_buf_0_val_2_d1 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == tmp_8_fu_866_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

/// ap_reg_ppiten_pp0_it3 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) begin
            if (~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) begin
                ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
            end else if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) begin
                ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
            end
        end
    end
end

/// ap_reg_ppiten_pp0_it4 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
            ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_4)) begin
        p_012_0_i_reg_284 <= i_V_reg_1637;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        p_012_0_i_reg_284 <= ap_const_lv11_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_lv1_0 == tmp_8_fu_866_p2))) begin
        p_025_0_i_reg_295 <= j_V_fu_871_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        p_025_0_i_reg_295 <= ap_const_lv11_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_40_reg_1751_pp0_it1)))) begin
        src_kernel_win_0_val_0_1_fu_138 <= k_buf_0_val_0_q0;
    end else if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_40_reg_1751_pp0_it1) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_18_reg_1765_pp0_it1) & (col_assign_2_reg_1801 == ap_const_lv2_1)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_40_reg_1751_pp0_it1) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_18_reg_1765_pp0_it1) & (col_assign_2_reg_1801 == ap_const_lv2_0)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_40_reg_1751_pp0_it1) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_18_reg_1765_pp0_it1) & ~(col_assign_2_reg_1801 == ap_const_lv2_1) & ~(col_assign_2_reg_1801 == ap_const_lv2_0)))) begin
        src_kernel_win_0_val_0_1_fu_138 <= col_buf_0_val_0_0_9_fu_1135_p3;
    end else if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & (ap_const_lv1_0 == brmerge_reg_1700) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == tmp_15_reg_1647) & (locy_2_t_reg_1724 == ap_const_lv2_1)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & (ap_const_lv1_0 == brmerge_reg_1700) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == tmp_15_reg_1647) & (locy_2_t_reg_1724 == ap_const_lv2_0)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & (ap_const_lv1_0 == brmerge_reg_1700) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == tmp_15_reg_1647) & ~(locy_2_t_reg_1724 == ap_const_lv2_1) & ~(locy_2_t_reg_1724 == ap_const_lv2_0)))) begin
        src_kernel_win_0_val_0_1_fu_138 <= src_kernel_win_0_val_0_0_fu_1075_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_40_reg_1751_pp0_it1)))) begin
        src_kernel_win_0_val_1_1_fu_154 <= k_buf_0_val_1_q0;
    end else if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_40_reg_1751_pp0_it1) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_18_reg_1765_pp0_it1) & (col_assign_2_reg_1801 == ap_const_lv2_1)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_40_reg_1751_pp0_it1) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_18_reg_1765_pp0_it1) & (col_assign_2_reg_1801 == ap_const_lv2_0)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_40_reg_1751_pp0_it1) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_18_reg_1765_pp0_it1) & ~(col_assign_2_reg_1801 == ap_const_lv2_1) & ~(col_assign_2_reg_1801 == ap_const_lv2_0)))) begin
        src_kernel_win_0_val_1_1_fu_154 <= right_border_buf_0_val_1_2_11_fu_1152_p3;
    end else if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & (ap_const_lv1_0 == brmerge_reg_1700) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == tmp_15_reg_1647) & (locy_2_t_reg_1724 == ap_const_lv2_1)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & (ap_const_lv1_0 == brmerge_reg_1700) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == tmp_15_reg_1647) & (locy_2_t_reg_1724 == ap_const_lv2_0)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & (ap_const_lv1_0 == brmerge_reg_1700) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == tmp_15_reg_1647) & ~(locy_2_t_reg_1724 == ap_const_lv2_1) & ~(locy_2_t_reg_1724 == ap_const_lv2_0)))) begin
        src_kernel_win_0_val_1_1_fu_154 <= src_kernel_win_0_val_1_0_fu_1090_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_40_reg_1751_pp0_it1) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_18_reg_1765_pp0_it1) & ~(col_assign_2_reg_1801 == ap_const_lv2_1) & ~(col_assign_2_reg_1801 == ap_const_lv2_0))) begin
        src_kernel_win_0_val_2_1_fu_150 <= right_border_buf_0_val_0_2_fu_206;
    end else if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_40_reg_1751_pp0_it1) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_18_reg_1765_pp0_it1) & (col_assign_2_reg_1801 == ap_const_lv2_0))) begin
        src_kernel_win_0_val_2_1_fu_150 <= right_border_buf_0_val_0_0_fu_198;
    end else if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_40_reg_1751_pp0_it1) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_18_reg_1765_pp0_it1) & (col_assign_2_reg_1801 == ap_const_lv2_1))) begin
        src_kernel_win_0_val_2_1_fu_150 <= right_border_buf_0_val_0_1_fu_202;
    end else if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & (ap_const_lv1_0 == brmerge_reg_1700) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == tmp_15_reg_1647) & ~(locy_2_t_reg_1724 == ap_const_lv2_1) & ~(locy_2_t_reg_1724 == ap_const_lv2_0)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_40_reg_1751_pp0_it1)))) begin
        src_kernel_win_0_val_2_1_fu_150 <= k_buf_0_val_2_q0;
    end else if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & (ap_const_lv1_0 == brmerge_reg_1700) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == tmp_15_reg_1647) & (locy_2_t_reg_1724 == ap_const_lv2_0))) begin
        src_kernel_win_0_val_2_1_fu_150 <= k_buf_0_val_0_q0;
    end else if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & (ap_const_lv1_0 == brmerge_reg_1700) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == tmp_15_reg_1647) & (locy_2_t_reg_1724 == ap_const_lv2_1))) begin
        src_kernel_win_0_val_2_1_fu_150 <= k_buf_0_val_1_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_lv1_0 == tmp_8_fu_866_p2))) begin
        ImagLoc_x_reg_1741 <= ImagLoc_x_fu_898_p2;
        or_cond219_i_reg_1737 <= or_cond219_i_fu_893_p2;
        or_cond_i1_reg_1746 <= or_cond_i1_fu_927_p2;
        p_p2_i_reg_1755 <= p_p2_i_fu_947_p3;
        sel_tmp7_i_reg_1760 <= sel_tmp7_i_fu_972_p2;
        tmp_40_reg_1751 <= ImagLoc_x_fu_898_p2[ap_const_lv32_B];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        ap_reg_ppstg_col_assign_reg_1777_pp0_it1 <= col_assign_reg_1777;
        ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it1 <= or_cond219_i_reg_1737;
        ap_reg_ppstg_or_cond7_reg_1769_pp0_it1 <= or_cond7_reg_1769;
        ap_reg_ppstg_tmp_18_reg_1765_pp0_it1 <= tmp_18_reg_1765;
        ap_reg_ppstg_tmp_20_reg_1773_pp0_it1 <= tmp_20_reg_1773;
        ap_reg_ppstg_tmp_40_reg_1751_pp0_it1 <= tmp_40_reg_1751;
        ap_reg_ppstg_tmp_8_reg_1728_pp0_it1 <= tmp_8_reg_1728;
        tmp_8_reg_1728 <= tmp_8_fu_866_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) begin
        ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it2 <= ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it1;
        ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it3 <= ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it2;
        ap_reg_ppstg_tmp_8_reg_1728_pp0_it2 <= ap_reg_ppstg_tmp_8_reg_1728_pp0_it1;
        src_kernel_win_0_val_0_1_6_reg_1807 <= src_kernel_win_0_val_0_1_fu_138;
        src_kernel_win_0_val_1_1_6_reg_1817 <= src_kernel_win_0_val_1_1_fu_154;
        src_kernel_win_0_val_2_1_9_reg_1812 <= src_kernel_win_0_val_2_1_fu_150;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(tmp_6_fu_475_p2 == ap_const_lv1_0))) begin
        brmerge_reg_1700 <= brmerge_fu_811_p2;
        newSel_reg_1695 <= newSel_fu_803_p3;
        sel_tmp7_i2_reg_1673 <= sel_tmp7_i2_fu_704_p2;
        sel_tmp7_i3_reg_1690 <= sel_tmp7_i3_fu_797_p2;
        sel_tmp_i2_reg_1668 <= sel_tmp_i2_fu_684_p3;
        tmp_15_reg_1647 <= ImagLoc_y_fu_492_p2[ap_const_lv32_B];
        tmp_19_reg_1651 <= tmp_19_fu_581_p1;
        tmp_25_reg_1657 <= tmp_25_fu_605_p3;
        tmp_31_reg_1663 <= tmp_31_fu_670_p1;
        tmp_32_reg_1678 <= tmp_32_fu_710_p1;
        tmp_36_reg_1685 <= tmp_36_fu_771_p1;
        tmp_7_reg_1642 <= tmp_7_fu_486_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(ap_const_lv1_0 == brmerge_reg_1700) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_lv1_0 == tmp_8_reg_1728) & (ap_const_lv1_0 == or_cond7_reg_1769) & (ap_const_lv1_0 == tmp_40_reg_1751) & (ap_const_lv1_0 == tmp_18_reg_1765))) begin
        col_assign_2_reg_1801 <= col_assign_2_fu_1049_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(ap_const_lv1_0 == brmerge_reg_1700) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_lv1_0 == tmp_8_fu_866_p2) & ~(ap_const_lv1_0 == or_cond7_fu_989_p2) & (ap_const_lv1_0 == tmp_20_fu_995_p2))) begin
        col_assign_reg_1777 <= col_assign_fu_1000_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1773_pp0_it1) & ~(ap_reg_ppstg_col_assign_reg_1777_pp0_it1 == ap_const_lv2_1) & ~(ap_reg_ppstg_col_assign_reg_1777_pp0_it1 == ap_const_lv2_0))) begin
        col_buf_0_val_0_0_3_fu_146 <= k_buf_0_val_0_q0;
        right_border_buf_0_val_0_2_fu_206 <= k_buf_0_val_2_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1773_pp0_it1) & (ap_reg_ppstg_col_assign_reg_1777_pp0_it1 == ap_const_lv2_1))) begin
        col_buf_0_val_0_0_5_fu_162 <= k_buf_0_val_0_q0;
        right_border_buf_0_val_0_1_fu_202 <= k_buf_0_val_2_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1773_pp0_it1) & (ap_reg_ppstg_col_assign_reg_1777_pp0_it1 == ap_const_lv2_0))) begin
        col_buf_0_val_0_0_6_fu_170 <= k_buf_0_val_0_q0;
        right_border_buf_0_val_0_0_fu_198 <= k_buf_0_val_2_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        heightloop_reg_1572 <= heightloop_fu_367_p2;
        len_cast4_i30_cast_reg_1614[0] <= len_cast4_i30_cast_fu_433_p1[0];
len_cast4_i30_cast_reg_1614[1] <= len_cast4_i30_cast_fu_433_p1[1];
len_cast4_i30_cast_reg_1614[2] <= len_cast4_i30_cast_fu_433_p1[2];
len_cast4_i30_cast_reg_1614[3] <= len_cast4_i30_cast_fu_433_p1[3];
len_cast4_i30_cast_reg_1614[4] <= len_cast4_i30_cast_fu_433_p1[4];
len_cast4_i30_cast_reg_1614[5] <= len_cast4_i30_cast_fu_433_p1[5];
len_cast4_i30_cast_reg_1614[6] <= len_cast4_i30_cast_fu_433_p1[6];
len_cast4_i30_cast_reg_1614[7] <= len_cast4_i30_cast_fu_433_p1[7];
len_cast4_i30_cast_reg_1614[8] <= len_cast4_i30_cast_fu_433_p1[8];
len_cast4_i30_cast_reg_1614[9] <= len_cast4_i30_cast_fu_433_p1[9];
len_cast4_i30_cast_reg_1614[10] <= len_cast4_i30_cast_fu_433_p1[10];
        len_cast4_i_cast_reg_1603[0] <= len_cast4_i_cast_fu_409_p1[0];
len_cast4_i_cast_reg_1603[1] <= len_cast4_i_cast_fu_409_p1[1];
len_cast4_i_cast_reg_1603[2] <= len_cast4_i_cast_fu_409_p1[2];
len_cast4_i_cast_reg_1603[3] <= len_cast4_i_cast_fu_409_p1[3];
len_cast4_i_cast_reg_1603[4] <= len_cast4_i_cast_fu_409_p1[4];
len_cast4_i_cast_reg_1603[5] <= len_cast4_i_cast_fu_409_p1[5];
len_cast4_i_cast_reg_1603[6] <= len_cast4_i_cast_fu_409_p1[6];
len_cast4_i_cast_reg_1603[7] <= len_cast4_i_cast_fu_409_p1[7];
len_cast4_i_cast_reg_1603[8] <= len_cast4_i_cast_fu_409_p1[8];
len_cast4_i_cast_reg_1603[9] <= len_cast4_i_cast_fu_409_p1[9];
len_cast4_i_cast_reg_1603[10] <= len_cast4_i_cast_fu_409_p1[10];
        p_neg226_i_cast_reg_1587 <= p_neg226_i_cast_fu_393_p2;
        ref_cast_reg_1598[0] <= ref_cast_fu_405_p1[0];
ref_cast_reg_1598[1] <= ref_cast_fu_405_p1[1];
ref_cast_reg_1598[2] <= ref_cast_fu_405_p1[2];
ref_cast_reg_1598[3] <= ref_cast_fu_405_p1[3];
ref_cast_reg_1598[4] <= ref_cast_fu_405_p1[4];
ref_cast_reg_1598[5] <= ref_cast_fu_405_p1[5];
ref_cast_reg_1598[6] <= ref_cast_fu_405_p1[6];
ref_cast_reg_1598[7] <= ref_cast_fu_405_p1[7];
ref_cast_reg_1598[8] <= ref_cast_fu_405_p1[8];
ref_cast_reg_1598[9] <= ref_cast_fu_405_p1[9];
ref_cast_reg_1598[10] <= ref_cast_fu_405_p1[10];
        ref_reg_1593 <= ref_fu_399_p2;
        tmp_17_cast_reg_1582[0] <= tmp_17_cast_fu_385_p1[0];
tmp_17_cast_reg_1582[1] <= tmp_17_cast_fu_385_p1[1];
tmp_17_cast_reg_1582[2] <= tmp_17_cast_fu_385_p1[2];
tmp_17_cast_reg_1582[3] <= tmp_17_cast_fu_385_p1[3];
tmp_17_cast_reg_1582[4] <= tmp_17_cast_fu_385_p1[4];
tmp_17_cast_reg_1582[5] <= tmp_17_cast_fu_385_p1[5];
tmp_17_cast_reg_1582[6] <= tmp_17_cast_fu_385_p1[6];
tmp_17_cast_reg_1582[7] <= tmp_17_cast_fu_385_p1[7];
tmp_17_cast_reg_1582[8] <= tmp_17_cast_fu_385_p1[8];
tmp_17_cast_reg_1582[9] <= tmp_17_cast_fu_385_p1[9];
tmp_17_cast_reg_1582[10] <= tmp_17_cast_fu_385_p1[10];
        tmp_1_reg_1567 <= tmp_1_fu_359_p1;
        tmp_5_cast_i_reg_1609[1] <= tmp_5_cast_i_fu_429_p1[1];
tmp_5_cast_i_reg_1609[2] <= tmp_5_cast_i_fu_429_p1[2];
tmp_5_cast_i_reg_1609[3] <= tmp_5_cast_i_fu_429_p1[3];
tmp_5_cast_i_reg_1609[4] <= tmp_5_cast_i_fu_429_p1[4];
tmp_5_cast_i_reg_1609[5] <= tmp_5_cast_i_fu_429_p1[5];
tmp_5_cast_i_reg_1609[6] <= tmp_5_cast_i_fu_429_p1[6];
tmp_5_cast_i_reg_1609[7] <= tmp_5_cast_i_fu_429_p1[7];
tmp_5_cast_i_reg_1609[8] <= tmp_5_cast_i_fu_429_p1[8];
tmp_5_cast_i_reg_1609[9] <= tmp_5_cast_i_fu_429_p1[9];
tmp_5_cast_i_reg_1609[10] <= tmp_5_cast_i_fu_429_p1[10];
tmp_5_cast_i_reg_1609[11] <= tmp_5_cast_i_fu_429_p1[11];
tmp_5_cast_i_reg_1609[12] <= tmp_5_cast_i_fu_429_p1[12];
tmp_5_cast_i_reg_1609[13] <= tmp_5_cast_i_fu_429_p1[13];
tmp_5_cast_i_reg_1609[14] <= tmp_5_cast_i_fu_429_p1[14];
        tmp_5_i1_reg_1623[1] <= tmp_5_i1_fu_447_p2[1];
tmp_5_i1_reg_1623[2] <= tmp_5_i1_fu_447_p2[2];
tmp_5_i1_reg_1623[3] <= tmp_5_i1_fu_447_p2[3];
tmp_5_i1_reg_1623[4] <= tmp_5_i1_fu_447_p2[4];
tmp_5_i1_reg_1623[5] <= tmp_5_i1_fu_447_p2[5];
tmp_5_i1_reg_1623[6] <= tmp_5_i1_fu_447_p2[6];
tmp_5_i1_reg_1623[7] <= tmp_5_i1_fu_447_p2[7];
tmp_5_i1_reg_1623[8] <= tmp_5_i1_fu_447_p2[8];
tmp_5_i1_reg_1623[9] <= tmp_5_i1_fu_447_p2[9];
tmp_5_i1_reg_1623[10] <= tmp_5_i1_fu_447_p2[10];
tmp_5_i1_reg_1623[11] <= tmp_5_i1_fu_447_p2[11];
tmp_5_i1_reg_1623[12] <= tmp_5_i1_fu_447_p2[12];
        tmp_5_i2_reg_1628 <= tmp_5_i2_fu_465_p2;
        widthloop_reg_1577 <= widthloop_fu_373_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        i_V_reg_1637 <= i_V_fu_480_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it2))) begin
        isneg_reg_1822 <= p_Val2_1_fu_1378_p2[ap_const_lv32_A];
        not_i_i_i_reg_1833 <= not_i_i_i_fu_1406_p2;
        p_Val2_3_reg_1828 <= p_Val2_3_fu_1392_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_lv1_0 == tmp_8_reg_1728))) begin
        k_buf_0_val_0_addr_reg_1783 <= tmp_13_fu_1042_p1;
        k_buf_0_val_1_addr_reg_1789 <= tmp_13_fu_1042_p1;
        k_buf_0_val_2_addr_reg_1795 <= tmp_13_fu_1042_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        locy_2_t_reg_1724 <= locy_2_t_fu_857_p2;
        sel_tmp1_reg_1709 <= sel_tmp1_fu_825_p2;
        sel_tmp3_reg_1714 <= sel_tmp3_fu_841_p2;
        sel_tmp5_reg_1719 <= sel_tmp5_fu_846_p2;
        sel_tmp8_reg_1704 <= sel_tmp8_fu_821_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(ap_const_lv1_0 == brmerge_reg_1700) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_lv1_0 == tmp_8_fu_866_p2))) begin
        or_cond7_reg_1769 <= or_cond7_fu_989_p2;
        tmp_18_reg_1765 <= tmp_18_fu_984_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1773_pp0_it1) & ~(ap_reg_ppstg_col_assign_reg_1777_pp0_it1 == ap_const_lv2_1) & ~(ap_reg_ppstg_col_assign_reg_1777_pp0_it1 == ap_const_lv2_0)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1773_pp0_it1) & (ap_reg_ppstg_col_assign_reg_1777_pp0_it1 == ap_const_lv2_1)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1773_pp0_it1) & (ap_reg_ppstg_col_assign_reg_1777_pp0_it1 == ap_const_lv2_0)))) begin
        right_border_buf_0_val_1_2_1_fu_174 <= right_border_buf_0_val_1_2_8_fu_1244_p3;
        right_border_buf_0_val_1_2_2_fu_178 <= right_border_buf_0_val_1_2_6_fu_1235_p3;
        right_border_buf_0_val_1_2_7_fu_182 <= right_border_buf_0_val_1_2_4_fu_1218_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it2))) begin
        src_kernel_win_0_val_0_2_fu_142 <= src_kernel_win_0_val_0_1_6_reg_1807;
        src_kernel_win_0_val_1_2_fu_158 <= src_kernel_win_0_val_1_1_6_reg_1817;
        src_kernel_win_0_val_2_2_fu_166 <= src_kernel_win_0_val_2_1_9_reg_1812;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(ap_const_lv1_0 == brmerge_reg_1700) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_lv1_0 == tmp_8_fu_866_p2) & ~(ap_const_lv1_0 == or_cond7_fu_989_p2))) begin
        tmp_20_reg_1773 <= tmp_20_fu_995_p2;
    end
end

/// ap_done assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0 or ap_sig_cseq_ST_st2_fsm_1 or tmp_6_fu_475_p2)
begin
    if (((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_6_fu_475_p2 == ap_const_lv1_0)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_sig_cseq_ST_st2_fsm_1 or tmp_6_fu_475_p2)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_6_fu_475_p2 == ap_const_lv1_0))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp0_stg0_fsm_3 assign process. ///
always @ (ap_sig_bdd_131)
begin
    if (ap_sig_bdd_131) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_3 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_23)
begin
    if (ap_sig_bdd_23) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st2_fsm_1 assign process. ///
always @ (ap_sig_bdd_76)
begin
    if (ap_sig_bdd_76) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st3_fsm_2 assign process. ///
always @ (ap_sig_bdd_114)
begin
    if (ap_sig_bdd_114) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st9_fsm_4 assign process. ///
always @ (ap_sig_bdd_298)
begin
    if (ap_sig_bdd_298) begin
        ap_sig_cseq_ST_st9_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st9_fsm_4 = ap_const_logic_0;
    end
end

/// k_buf_0_val_0_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_150 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_162 or ap_reg_ppiten_pp0_it4)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        k_buf_0_val_0_ce0 = ap_const_logic_1;
    end else begin
        k_buf_0_val_0_ce0 = ap_const_logic_0;
    end
end

/// k_buf_0_val_0_ce1 assign process. ///
always @ (ap_sig_bdd_150 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_162 or ap_reg_ppiten_pp0_it4)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        k_buf_0_val_0_ce1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_0_ce1 = ap_const_logic_0;
    end
end

/// k_buf_0_val_0_we1 assign process. ///
always @ (brmerge_reg_1700 or ap_reg_ppstg_tmp_8_reg_1728_pp0_it1 or ap_reg_ppstg_or_cond7_reg_1769_pp0_it1 or ap_sig_bdd_150 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_162 or ap_reg_ppiten_pp0_it4)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        k_buf_0_val_0_we1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_0_we1 = ap_const_logic_0;
    end
end

/// k_buf_0_val_1_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_150 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_162 or ap_reg_ppiten_pp0_it4)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        k_buf_0_val_1_ce0 = ap_const_logic_1;
    end else begin
        k_buf_0_val_1_ce0 = ap_const_logic_0;
    end
end

/// k_buf_0_val_1_ce1 assign process. ///
always @ (brmerge_reg_1700 or ap_reg_ppstg_tmp_8_reg_1728_pp0_it1 or ap_reg_ppstg_or_cond7_reg_1769_pp0_it1 or ap_sig_bdd_150 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_162 or ap_reg_ppiten_pp0_it4 or ap_reg_ppstg_tmp_20_reg_1773_pp0_it1)
begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1773_pp0_it1)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1773_pp0_it1)))) begin
        k_buf_0_val_1_ce1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_1_ce1 = ap_const_logic_0;
    end
end

/// k_buf_0_val_1_we1 assign process. ///
always @ (brmerge_reg_1700 or ap_reg_ppstg_tmp_8_reg_1728_pp0_it1 or ap_reg_ppstg_or_cond7_reg_1769_pp0_it1 or ap_sig_bdd_150 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_162 or ap_reg_ppiten_pp0_it4 or ap_reg_ppstg_tmp_20_reg_1773_pp0_it1)
begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1773_pp0_it1)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1773_pp0_it1)))) begin
        k_buf_0_val_1_we1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_1_we1 = ap_const_logic_0;
    end
end

/// k_buf_0_val_2_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_150 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_162 or ap_reg_ppiten_pp0_it4)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        k_buf_0_val_2_ce0 = ap_const_logic_1;
    end else begin
        k_buf_0_val_2_ce0 = ap_const_logic_0;
    end
end

/// k_buf_0_val_2_ce1 assign process. ///
always @ (brmerge_reg_1700 or ap_reg_ppstg_tmp_8_reg_1728_pp0_it1 or ap_reg_ppstg_or_cond7_reg_1769_pp0_it1 or ap_sig_bdd_150 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_162 or ap_reg_ppiten_pp0_it4 or ap_reg_ppstg_tmp_20_reg_1773_pp0_it1)
begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1773_pp0_it1)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1773_pp0_it1)))) begin
        k_buf_0_val_2_ce1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_2_ce1 = ap_const_logic_0;
    end
end

/// k_buf_0_val_2_we1 assign process. ///
always @ (brmerge_reg_1700 or ap_reg_ppstg_tmp_8_reg_1728_pp0_it1 or ap_reg_ppstg_or_cond7_reg_1769_pp0_it1 or ap_sig_bdd_150 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_162 or ap_reg_ppiten_pp0_it4 or ap_reg_ppstg_tmp_20_reg_1773_pp0_it1)
begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1773_pp0_it1)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1773_pp0_it1)))) begin
        k_buf_0_val_2_we1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_2_we1 = ap_const_logic_0;
    end
end

/// p_dst_data_stream_V_write assign process. ///
always @ (ap_sig_bdd_150 or ap_reg_ppiten_pp0_it2 or ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it3 or ap_sig_bdd_162 or ap_reg_ppiten_pp0_it4)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        p_dst_data_stream_V_write = ap_const_logic_1;
    end else begin
        p_dst_data_stream_V_write = ap_const_logic_0;
    end
end

/// p_src_data_stream_V_read assign process. ///
always @ (brmerge_reg_1700 or ap_reg_ppstg_tmp_8_reg_1728_pp0_it1 or ap_reg_ppstg_or_cond7_reg_1769_pp0_it1 or ap_sig_bdd_150 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_162 or ap_reg_ppiten_pp0_it4)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        p_src_data_stream_V_read = ap_const_logic_1;
    end else begin
        p_src_data_stream_V_read = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_start or ap_CS_fsm or tmp_6_fu_475_p2 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_150 or ap_reg_ppiten_pp0_it2 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_162 or ap_reg_ppiten_pp0_it4)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if ((tmp_6_fu_475_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
        end
        ap_ST_pp0_stg0_fsm_3 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it3)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_150 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_162 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it3)))) begin
                ap_NS_fsm = ap_ST_st9_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            end
        end
        ap_ST_st9_fsm_4 : 
        begin
            ap_NS_fsm = ap_ST_st2_fsm_1;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_fu_898_p2 = ($signed(tmp_21_cast_fu_862_p1) + $signed(ap_const_lv12_FFF));
assign ImagLoc_y_fu_492_p2 = ($signed(tmp_18_cast_fu_471_p1) + $signed(ap_const_lv12_FFC));
assign OP1_V_0_cast_fu_1286_p1 = src_kernel_win_0_val_2_2_fu_166;
assign OP1_V_2_cast_fu_1338_p1 = src_kernel_win_0_val_0_2_fu_142;

/// ap_sig_bdd_114 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_114 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_131 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_131 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

/// ap_sig_bdd_150 assign process. ///
always @ (p_src_data_stream_V_empty_n or brmerge_reg_1700 or ap_reg_ppstg_tmp_8_reg_1728_pp0_it1 or ap_reg_ppstg_or_cond7_reg_1769_pp0_it1)
begin
    ap_sig_bdd_150 = ((p_src_data_stream_V_empty_n == ap_const_logic_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_8_reg_1728_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1700) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_1769_pp0_it1));
end

/// ap_sig_bdd_162 assign process. ///
always @ (p_dst_data_stream_V_full_n or ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it3)
begin
    ap_sig_bdd_162 = ((p_dst_data_stream_V_full_n == ap_const_logic_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it3));
end

/// ap_sig_bdd_23 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_23 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_298 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_298 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end

/// ap_sig_bdd_76 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_76 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end
assign brmerge_fu_811_p2 = (tmp_s_fu_498_p2 | or_cond6_fu_525_p2);
assign col_assign_2_fu_1049_p2 = (tmp_41_fu_1038_p1 + p_neg226_i_cast_reg_1587);
assign col_assign_fu_1000_p2 = (tmp_38_fu_904_p1 + p_neg226_i_cast_reg_1587);
assign col_buf_0_val_0_0_2_fu_1122_p3 = ((sel_tmp_fu_1117_p2)? col_buf_0_val_0_0_5_fu_162: col_buf_0_val_0_0_3_fu_146);
assign col_buf_0_val_0_0_9_fu_1135_p3 = ((sel_tmp2_fu_1130_p2)? col_buf_0_val_0_0_6_fu_170: col_buf_0_val_0_0_2_fu_1122_p3);
assign heightloop_fu_367_p2 = (tmp_1_fu_359_p1 + ap_const_lv11_5);
assign i_V_fu_480_p2 = (p_012_0_i_reg_284 + ap_const_lv11_1);
assign icmp1_fu_887_p2 = (tmp_37_fu_877_p4 != ap_const_lv10_0? 1'b1: 1'b0);
assign icmp_fu_514_p2 = ($signed(tmp_12_fu_504_p4) > $signed(11'b00000000000)? 1'b1: 1'b0);
assign j_V_fu_871_p2 = (p_025_0_i_reg_295 + ap_const_lv11_1);
assign k_buf_0_val_0_address0 = tmp_13_fu_1042_p1;
assign k_buf_0_val_0_address1 = k_buf_0_val_0_addr_reg_1783;
assign k_buf_0_val_0_d1 = p_src_data_stream_V_dout;
assign k_buf_0_val_1_address0 = tmp_13_fu_1042_p1;
assign k_buf_0_val_1_address1 = k_buf_0_val_1_addr_reg_1789;
assign k_buf_0_val_1_d1 = k_buf_0_val_0_q0;
assign k_buf_0_val_2_address0 = tmp_13_fu_1042_p1;
assign k_buf_0_val_2_address1 = k_buf_0_val_2_addr_reg_1795;
assign k_buf_0_val_2_d1 = k_buf_0_val_1_q0;
assign len_cast4_i30_cast_fu_433_p1 = tmp_1_fu_359_p1;
assign len_cast4_i_cast_fu_409_p1 = tmp_2_fu_363_p1;
assign locy_1_t_fu_836_p2 = (tmp_32_reg_1678 - p_assign_2_i2_fu_831_p3);
assign locy_2_t_fu_857_p2 = (tmp_32_reg_1678 - newSel1_fu_852_p3);
assign newSel1_fu_852_p3 = ((sel_tmp7_i3_reg_1690)? tmp_36_reg_1685: newSel_reg_1695);
assign newSel_fu_803_p3 = ((or_cond_i3_fu_739_p2)? tmp_34_fu_745_p1: p_assign_1_cast_i1_fu_780_p2);
assign not_i_i_i_fu_1406_p2 = (tmp_28_fu_1396_p4 != ap_const_lv3_0? 1'b1: 1'b0);
assign or_cond219_i_fu_893_p2 = (tmp_7_reg_1642 & icmp1_fu_887_p2);
assign or_cond6_fu_525_p2 = (icmp_fu_514_p2 & tmp_14_fu_520_p2);
assign or_cond7_fu_989_p2 = (tmp_17_fu_978_p2 & tmp_18_fu_984_p2);
assign or_cond_i1_fu_927_p2 = (tmp_i_fu_922_p2 & rev2_fu_916_p2);
assign or_cond_i2_fu_638_p2 = (tmp_i2_fu_633_p2 & rev_fu_627_p2);
assign or_cond_i3_fu_739_p2 = (tmp_i3_fu_734_p2 & rev1_fu_728_p2);
assign overflow_fu_1429_p2 = (not_i_i_i_reg_1833 & tmp_i_i_fu_1424_p2);
assign p_Val2_114_2_fu_1326_p3 = {{src_kernel_win_0_val_1_1_fu_154}, {ap_const_lv1_0}};
assign p_Val2_1_fu_1378_p2 = ($signed(tmp27_fu_1372_p2) + $signed(tmp25_fu_1356_p2));
assign p_Val2_2_fu_1342_p2 = (ap_const_lv9_0 - OP1_V_2_cast_fu_1338_p1);
assign p_Val2_3_0_2_cast_cast_fu_1300_p1 = $signed(p_Val2_3_0_2_fu_1294_p2);
assign p_Val2_3_0_2_fu_1294_p2 = (tmp_147_0_2_cast_fu_1290_p1 - OP1_V_0_cast_fu_1286_p1);
assign p_Val2_3_fu_1392_p1 = p_Val2_1_fu_1378_p2[7:0];
assign p_Val2_s_fu_1316_p2 = (ap_const_lv10_0 - p_shl_cast_fu_1312_p1);
assign p_assign_1_cast_i1_fu_780_p2 = (tmp_5_i2_reg_1628 - tmp_36_fu_771_p1);
assign p_assign_1_cast_i_fu_679_p2 = (tmp_5_i2_reg_1628 - tmp_31_fu_670_p1);
assign p_assign_1_fu_1015_p2 = ($signed(tmp_5_cast_i_reg_1609) - $signed(p_p2_cast1_i_cast_fu_1011_p1));
assign p_assign_2_fu_564_p2 = (tmp_5_i1_reg_1623 - p_p2_cast1_i40_cast_fu_555_p1);
assign p_assign_2_i2_fu_831_p3 = ((sel_tmp7_i2_reg_1673)? tmp_31_reg_1663: sel_tmp_i2_reg_1668);
assign p_assign_2_i_fu_1027_p3 = ((sel_tmp7_i_reg_1760)? p_p2_cast1_i_cast_fu_1011_p1: sel_tmp_i_fu_1020_p3);
assign p_assign_3_fu_656_p2 = (ap_const_lv12_5 - tmp_18_cast_fu_471_p1);
assign p_assign_4_fu_757_p2 = (ap_const_lv12_6 - tmp_18_cast_fu_471_p1);
assign p_assign_fu_941_p2 = (ap_const_lv12_1 - tmp_21_cast_fu_862_p1);
assign p_cast_i_cast_fu_1005_p1 = $signed(ImagLoc_x_reg_1741);
assign p_dst_data_stream_V_din = ((tmp_i_i_38_fu_1442_p2)? p_mux_i_i_cast_fu_1434_p3: p_Val2_3_reg_1828);
assign p_i_fu_539_p3 = ((tmp_14_fu_520_p2)? ap_const_lv11_2: ref_reg_1593);
assign p_mux_i_i_cast_fu_1434_p3 = ((tmp_i_i_fu_1424_p2)? ap_const_lv8_FF: ap_const_lv8_0);
assign p_neg226_i_cast_fu_393_p2 = (tmp_3_fu_389_p1 ^ ap_const_lv2_3);
assign p_p2_cast1_i40_cast_fu_555_p1 = tmp_16_fu_551_p1;
assign p_p2_cast1_i_cast_fu_1011_p1 = $unsigned(p_p2_i_cast_fu_1008_p1);
assign p_p2_i1_fu_662_p3 = ((tmp_30_fu_648_p3)? p_assign_3_fu_656_p2: y_1_fu_613_p2);
assign p_p2_i2_fu_763_p3 = ((tmp_35_fu_749_p3)? p_assign_4_fu_757_p2: y_1_1_fu_714_p2);
assign p_p2_i_cast_fu_1008_p1 = $signed(p_p2_i_reg_1755);
assign p_p2_i_fu_947_p3 = ((tmp_40_fu_933_p3)? p_assign_fu_941_p2: ImagLoc_x_fu_898_p2);
assign p_shl_cast_fu_1312_p1 = p_shl_fu_1304_p3;
assign p_shl_fu_1304_p3 = {{src_kernel_win_0_val_1_2_fu_158}, {ap_const_lv1_0}};
assign ref_cast_fu_405_p1 = ref_fu_399_p2;
assign ref_fu_399_p2 = ($signed(tmp_1_fu_359_p1) + $signed(ap_const_lv11_7FF));
assign rev1_fu_728_p2 = (tmp_33_fu_720_p3 ^ ap_const_lv1_1);
assign rev2_fu_916_p2 = (tmp_39_fu_908_p3 ^ ap_const_lv1_1);
assign rev_fu_627_p2 = (tmp_27_fu_619_p3 ^ ap_const_lv1_1);
assign right_border_buf_0_val_1_2_11_fu_1152_p3 = ((sel_tmp2_fu_1130_p2)? right_border_buf_0_val_1_2_1_fu_174: right_border_buf_0_val_1_2_fu_1144_p3);
assign right_border_buf_0_val_1_2_3_fu_1205_p3 = ((sel_tmp6_fu_1200_p2)? right_border_buf_0_val_1_2_7_fu_182: k_buf_0_val_1_q0);
assign right_border_buf_0_val_1_2_4_fu_1218_p3 = ((sel_tmp7_fu_1213_p2)? right_border_buf_0_val_1_2_7_fu_182: right_border_buf_0_val_1_2_3_fu_1205_p3);
assign right_border_buf_0_val_1_2_5_fu_1227_p3 = ((sel_tmp6_fu_1200_p2)? k_buf_0_val_1_q0: right_border_buf_0_val_1_2_2_fu_178);
assign right_border_buf_0_val_1_2_6_fu_1235_p3 = ((sel_tmp7_fu_1213_p2)? right_border_buf_0_val_1_2_2_fu_178: right_border_buf_0_val_1_2_5_fu_1227_p3);
assign right_border_buf_0_val_1_2_8_fu_1244_p3 = ((sel_tmp7_fu_1213_p2)? k_buf_0_val_1_q0: right_border_buf_0_val_1_2_1_fu_174);
assign right_border_buf_0_val_1_2_fu_1144_p3 = ((sel_tmp_fu_1117_p2)? right_border_buf_0_val_1_2_2_fu_178: right_border_buf_0_val_1_2_7_fu_182);
assign sel_tmp1_fu_825_p2 = (tmp_26_fu_817_p2 == ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp2_fu_1130_p2 = (col_assign_2_reg_1801 == ap_const_lv2_0? 1'b1: 1'b0);
assign sel_tmp3_fu_841_p2 = (tmp_32_reg_1678 == p_assign_2_i2_fu_831_p3? 1'b1: 1'b0);
assign sel_tmp4_fu_1083_p3 = ((sel_tmp3_reg_1714)? k_buf_0_val_0_q0: k_buf_0_val_2_q0);
assign sel_tmp5_fu_846_p2 = (locy_1_t_fu_836_p2 == ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp6_fu_1200_p2 = (ap_reg_ppstg_col_assign_reg_1777_pp0_it1 == ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp6_i1_fu_569_p2 = (tmp_i1_fu_546_p2 ^ ap_const_lv1_1);
assign sel_tmp6_i2_fu_698_p2 = (tmp_27_fu_619_p3 | tmp_i2_not_fu_692_p2);
assign sel_tmp6_i3_fu_791_p2 = (tmp_33_fu_720_p3 | tmp_i3_not_fu_785_p2);
assign sel_tmp6_i_fu_966_p2 = (tmp_39_fu_908_p3 | tmp_i_not_fu_960_p2);
assign sel_tmp7_fu_1213_p2 = (ap_reg_ppstg_col_assign_reg_1777_pp0_it1 == ap_const_lv2_0? 1'b1: 1'b0);
assign sel_tmp7_i1_fu_575_p2 = (tmp_3_i1_fu_559_p2 & sel_tmp6_i1_fu_569_p2);
assign sel_tmp7_i2_fu_704_p2 = (tmp_3_i2_fu_674_p2 & sel_tmp6_i2_fu_698_p2);
assign sel_tmp7_i3_fu_797_p2 = (tmp_3_i3_fu_775_p2 & sel_tmp6_i3_fu_791_p2);
assign sel_tmp7_i_fu_972_p2 = (tmp_3_i_fu_955_p2 & sel_tmp6_i_fu_966_p2);
assign sel_tmp8_fu_821_p2 = (tmp_19_reg_1651 == tmp_25_reg_1657? 1'b1: 1'b0);
assign sel_tmp9_fu_1068_p3 = ((sel_tmp8_reg_1704)? k_buf_0_val_0_q0: k_buf_0_val_2_q0);
assign sel_tmp_fu_1117_p2 = (col_assign_2_reg_1801 == ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp_i2_fu_684_p3 = ((or_cond_i2_fu_638_p2)? tmp_29_fu_644_p1: p_assign_1_cast_i_fu_679_p2);
assign sel_tmp_i_fu_1020_p3 = ((or_cond_i1_reg_1746)? p_cast_i_cast_fu_1005_p1: p_assign_1_fu_1015_p2);
assign src_kernel_win_0_val_0_0_fu_1075_p3 = ((sel_tmp1_reg_1709)? k_buf_0_val_1_q0: sel_tmp9_fu_1068_p3);
assign src_kernel_win_0_val_1_0_fu_1090_p3 = ((sel_tmp5_reg_1719)? k_buf_0_val_1_q0: sel_tmp4_fu_1083_p3);
assign tmp132_cast_fu_1368_p1 = tmp26_fu_1362_p2;
assign tmp25_fu_1356_p2 = ($signed(tmp_147_1_cast_fu_1322_p1) + $signed(tmp_147_2_cast_fu_1348_p1));
assign tmp26_fu_1362_p2 = ($signed(p_Val2_3_0_2_cast_cast_fu_1300_p1) + $signed(tmp_147_2_2_cast_cast_fu_1352_p1));
assign tmp27_fu_1372_p2 = ($signed(tmp132_cast_fu_1368_p1) + $signed(tmp_147_1_cast_37_fu_1334_p1));
assign tmp_10_fu_437_p2 = p_src_rows_V_read << ap_const_lv12_1;
assign tmp_11_fu_453_p1 = p_src_rows_V_read[0:0];
assign tmp_12_fu_504_p4 = {{ImagLoc_y_fu_492_p2[ap_const_lv32_B : ap_const_lv32_1]}};
assign tmp_13_fu_1042_p1 = $unsigned(x_fu_1034_p1);
assign tmp_147_0_2_cast_fu_1290_p1 = src_kernel_win_0_val_2_1_fu_150;
assign tmp_147_1_cast_37_fu_1334_p1 = p_Val2_114_2_fu_1326_p3;
assign tmp_147_1_cast_fu_1322_p1 = $signed(p_Val2_s_fu_1316_p2);
assign tmp_147_2_2_cast_cast_fu_1352_p1 = src_kernel_win_0_val_0_1_fu_138;
assign tmp_147_2_cast_fu_1348_p1 = $signed(p_Val2_2_fu_1342_p2);
assign tmp_14_fu_520_p2 = ($signed(ImagLoc_y_fu_492_p2) < $signed(ref_cast_reg_1598)? 1'b1: 1'b0);
assign tmp_16_fu_551_p1 = ImagLoc_y_fu_492_p2[10:0];
assign tmp_17_cast_fu_385_p1 = tmp_4_fu_379_p2;
assign tmp_17_fu_978_p2 = (p_025_0_i_reg_295 != ap_const_lv11_0? 1'b1: 1'b0);
assign tmp_18_cast_fu_471_p1 = p_012_0_i_reg_284;
assign tmp_18_fu_984_p2 = ($signed(ImagLoc_x_fu_898_p2) < $signed(p_src_cols_V_read)? 1'b1: 1'b0);
assign tmp_19_fu_581_p1 = p_i_fu_539_p3[1:0];
assign tmp_1_fu_359_p1 = p_src_rows_V_read[10:0];
assign tmp_20_fu_995_p2 = ($signed(ImagLoc_x_fu_898_p2) < $signed(tmp_17_cast_reg_1582)? 1'b1: 1'b0);
assign tmp_21_cast_fu_862_p1 = p_025_0_i_reg_295;
assign tmp_21_fu_585_p1 = ImagLoc_y_fu_492_p2[1:0];
assign tmp_22_fu_589_p1 = ImagLoc_y_fu_492_p2[1:0];
assign tmp_23_fu_593_p1 = p_assign_2_fu_564_p2[1:0];
assign tmp_24_fu_597_p3 = ((tmp_i1_fu_546_p2)? tmp_22_fu_589_p1: tmp_23_fu_593_p1);
assign tmp_25_fu_605_p3 = ((sel_tmp7_i1_fu_575_p2)? tmp_21_fu_585_p1: tmp_24_fu_597_p3);
assign tmp_26_fu_817_p2 = (tmp_19_reg_1651 - tmp_25_reg_1657);
assign tmp_27_fu_619_p3 = y_1_fu_613_p2[ap_const_lv32_B];
assign tmp_28_fu_1396_p4 = {{p_Val2_1_fu_1378_p2[ap_const_lv32_A : ap_const_lv32_8]}};
assign tmp_29_fu_644_p1 = y_1_fu_613_p2[1:0];
assign tmp_2_fu_363_p1 = p_src_cols_V_read[10:0];
assign tmp_30_fu_648_p3 = y_1_fu_613_p2[ap_const_lv32_B];
assign tmp_31_fu_670_p1 = p_p2_i1_fu_662_p3[1:0];
assign tmp_32_fu_710_p1 = p_i_fu_539_p3[1:0];
assign tmp_33_fu_720_p3 = y_1_1_fu_714_p2[ap_const_lv32_B];
assign tmp_34_fu_745_p1 = y_1_1_fu_714_p2[1:0];
assign tmp_35_fu_749_p3 = y_1_1_fu_714_p2[ap_const_lv32_B];
assign tmp_36_fu_771_p1 = p_p2_i2_fu_763_p3[1:0];
assign tmp_37_fu_877_p4 = {{p_025_0_i_reg_295[ap_const_lv32_A : ap_const_lv32_1]}};
assign tmp_38_fu_904_p1 = ImagLoc_x_fu_898_p2[1:0];
assign tmp_39_fu_908_p3 = ImagLoc_x_fu_898_p2[ap_const_lv32_B];
assign tmp_3_fu_389_p1 = p_src_cols_V_read[1:0];
assign tmp_3_i1_fu_559_p2 = (tmp_16_fu_551_p1 < tmp_1_reg_1567? 1'b1: 1'b0);
assign tmp_3_i2_fu_674_p2 = (p_p2_i1_fu_662_p3 < len_cast4_i30_cast_reg_1614? 1'b1: 1'b0);
assign tmp_3_i3_fu_775_p2 = (p_p2_i2_fu_763_p3 < len_cast4_i30_cast_reg_1614? 1'b1: 1'b0);
assign tmp_3_i_fu_955_p2 = (p_p2_i_fu_947_p3 < len_cast4_i_cast_reg_1603? 1'b1: 1'b0);
assign tmp_40_fu_933_p3 = ImagLoc_x_fu_898_p2[ap_const_lv32_B];
assign tmp_41_fu_1038_p1 = p_assign_2_i_fu_1027_p3[1:0];
assign tmp_4_cast_i46_cast_fu_443_p1 = tmp_10_fu_437_p2;
assign tmp_4_cast_i_cast_fu_419_p1 = tmp_5_fu_413_p2;
assign tmp_4_fu_379_p2 = ($signed(tmp_2_fu_363_p1) + $signed(ap_const_lv11_7FD));
assign tmp_4_i2_fu_457_p3 = {{tmp_11_fu_453_p1}, {ap_const_lv1_0}};
assign tmp_5_cast_i_fu_429_p1 = $signed(tmp_5_i_fu_423_p2);
assign tmp_5_fu_413_p2 = p_src_cols_V_read << ap_const_lv12_1;
assign tmp_5_i1_fu_447_p2 = (tmp_4_cast_i46_cast_fu_443_p1 + ap_const_lv13_2);
assign tmp_5_i2_fu_465_p2 = (tmp_4_i2_fu_457_p3 ^ ap_const_lv2_2);
assign tmp_5_i_fu_423_p2 = ($signed(tmp_4_cast_i_cast_fu_419_p1) + $signed(ap_const_lv13_1FFE));
assign tmp_6_fu_475_p2 = (p_012_0_i_reg_284 < heightloop_reg_1572? 1'b1: 1'b0);
assign tmp_7_fu_486_p2 = (p_012_0_i_reg_284 > ap_const_lv11_4? 1'b1: 1'b0);
assign tmp_8_fu_866_p2 = (p_025_0_i_reg_295 < widthloop_reg_1577? 1'b1: 1'b0);
assign tmp_i1_fu_546_p2 = ($signed(ImagLoc_y_fu_492_p2) < $signed(len_cast4_i30_cast_reg_1614)? 1'b1: 1'b0);
assign tmp_i2_fu_633_p2 = ($signed(y_1_fu_613_p2) < $signed(len_cast4_i30_cast_reg_1614)? 1'b1: 1'b0);
assign tmp_i2_not_fu_692_p2 = (tmp_i2_fu_633_p2 ^ ap_const_lv1_1);
assign tmp_i3_fu_734_p2 = ($signed(y_1_1_fu_714_p2) < $signed(len_cast4_i30_cast_reg_1614)? 1'b1: 1'b0);
assign tmp_i3_not_fu_785_p2 = (tmp_i3_fu_734_p2 ^ ap_const_lv1_1);
assign tmp_i_fu_922_p2 = ($signed(ImagLoc_x_fu_898_p2) < $signed(len_cast4_i_cast_reg_1603)? 1'b1: 1'b0);
assign tmp_i_i_38_fu_1442_p2 = (isneg_reg_1822 | overflow_fu_1429_p2);
assign tmp_i_i_fu_1424_p2 = (isneg_reg_1822 ^ ap_const_lv1_1);
assign tmp_i_not_fu_960_p2 = (tmp_i_fu_922_p2 ^ ap_const_lv1_1);
assign tmp_s_fu_498_p2 = ($signed(ImagLoc_y_fu_492_p2) < $signed(12'b111111111111)? 1'b1: 1'b0);
assign widthloop_fu_373_p2 = (tmp_2_fu_363_p1 + ap_const_lv11_2);
assign x_fu_1034_p1 = $signed(p_assign_2_i_fu_1027_p3);
assign y_1_1_fu_714_p2 = ($signed(tmp_18_cast_fu_471_p1) + $signed(ap_const_lv12_FFA));
assign y_1_fu_613_p2 = ($signed(tmp_18_cast_fu_471_p1) + $signed(ap_const_lv12_FFB));
always @ (posedge ap_clk)
begin
    tmp_17_cast_reg_1582[11] <= 1'b0;
    ref_cast_reg_1598[11] <= 1'b0;
    len_cast4_i_cast_reg_1603[11] <= 1'b0;
    tmp_5_cast_i_reg_1609[0] <= 1'b0;
    len_cast4_i30_cast_reg_1614[11] <= 1'b0;
    tmp_5_i1_reg_1623[0] <= 1'b0;
end



endmodule //image_filter_Filter2D

