// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================


extern void image_filter ( hls::stream< ap_axiu< 32 ,1 ,1 ,1 > > & INPUT_STREAM,  hls::stream< ap_axiu< 32 ,1 ,1 ,1 > > & OUTPUT_STREAM,  int rows,  int cols);

