-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2014.4
-- Copyright (C) 2014 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity image_filter_Filter2D is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_src_rows_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
    p_src_cols_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
    p_src_data_stream_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    p_src_data_stream_V_empty_n : IN STD_LOGIC;
    p_src_data_stream_V_read : OUT STD_LOGIC;
    p_dst_data_stream_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_dst_data_stream_V_full_n : IN STD_LOGIC;
    p_dst_data_stream_V_write : OUT STD_LOGIC );
end;


architecture behav of image_filter_Filter2D is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_st2_fsm_1 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_st3_fsm_2 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_pp0_stg0_fsm_3 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_st9_fsm_4 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv11_5 : STD_LOGIC_VECTOR (10 downto 0) := "00000000101";
    constant ap_const_lv11_2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_const_lv11_7FD : STD_LOGIC_VECTOR (10 downto 0) := "11111111101";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv13_1FFE : STD_LOGIC_VECTOR (12 downto 0) := "1111111111110";
    constant ap_const_lv13_2 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000010";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv11_4 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_const_lv12_FFC : STD_LOGIC_VECTOR (11 downto 0) := "111111111100";
    constant ap_const_lv12_FFF : STD_LOGIC_VECTOR (11 downto 0) := "111111111111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv12_FFB : STD_LOGIC_VECTOR (11 downto 0) := "111111111011";
    constant ap_const_lv12_5 : STD_LOGIC_VECTOR (11 downto 0) := "000000000101";
    constant ap_const_lv12_FFA : STD_LOGIC_VECTOR (11 downto 0) := "111111111010";
    constant ap_const_lv12_6 : STD_LOGIC_VECTOR (11 downto 0) := "000000000110";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st1_fsm_0 : STD_LOGIC;
    signal ap_sig_bdd_23 : BOOLEAN;
    signal p_025_0_i_reg_295 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_1_fu_359_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_1_reg_1567 : STD_LOGIC_VECTOR (10 downto 0);
    signal heightloop_fu_367_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal heightloop_reg_1572 : STD_LOGIC_VECTOR (10 downto 0);
    signal widthloop_fu_373_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal widthloop_reg_1577 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_17_cast_fu_385_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_17_cast_reg_1582 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_neg226_i_cast_fu_393_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_neg226_i_cast_reg_1587 : STD_LOGIC_VECTOR (1 downto 0);
    signal ref_fu_399_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ref_reg_1593 : STD_LOGIC_VECTOR (10 downto 0);
    signal ref_cast_fu_405_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ref_cast_reg_1598 : STD_LOGIC_VECTOR (11 downto 0);
    signal len_cast4_i_cast_fu_409_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal len_cast4_i_cast_reg_1603 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_5_cast_i_fu_429_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_5_cast_i_reg_1609 : STD_LOGIC_VECTOR (14 downto 0);
    signal len_cast4_i30_cast_fu_433_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal len_cast4_i30_cast_reg_1614 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_5_i1_fu_447_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_5_i1_reg_1623 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_5_i2_fu_465_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_i2_reg_1628 : STD_LOGIC_VECTOR (1 downto 0);
    signal i_V_fu_480_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_V_reg_1637 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_cseq_ST_st2_fsm_1 : STD_LOGIC;
    signal ap_sig_bdd_76 : BOOLEAN;
    signal tmp_7_fu_486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_reg_1642 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_475_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_reg_1647 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_fu_581_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_19_reg_1651 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_25_fu_605_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_25_reg_1657 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_31_fu_670_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_31_reg_1663 : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp_i2_fu_684_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp_i2_reg_1668 : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp7_i2_fu_704_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_i2_reg_1673 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_32_fu_710_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_32_reg_1678 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_36_fu_771_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_36_reg_1685 : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp7_i3_fu_797_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_i3_reg_1690 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel_fu_803_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal newSel_reg_1695 : STD_LOGIC_VECTOR (1 downto 0);
    signal brmerge_fu_811_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_reg_1700 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp8_fu_821_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp8_reg_1704 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st3_fsm_2 : STD_LOGIC;
    signal ap_sig_bdd_114 : BOOLEAN;
    signal sel_tmp1_fu_825_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_reg_1709 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp3_fu_841_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp3_reg_1714 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp5_fu_846_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp5_reg_1719 : STD_LOGIC_VECTOR (0 downto 0);
    signal locy_2_t_fu_857_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal locy_2_t_reg_1724 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_8_fu_866_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_1728 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_pp0_stg0_fsm_3 : STD_LOGIC;
    signal ap_sig_bdd_131 : BOOLEAN;
    signal ap_reg_ppiten_pp0_it0 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it1 : STD_LOGIC := '0';
    signal ap_reg_ppstg_tmp_8_reg_1728_pp0_it1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond7_reg_1769 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_or_cond7_reg_1769_pp0_it1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_bdd_150 : BOOLEAN;
    signal ap_reg_ppiten_pp0_it2 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it3 : STD_LOGIC := '0';
    signal or_cond219_i_reg_1737 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_bdd_162 : BOOLEAN;
    signal ap_reg_ppiten_pp0_it4 : STD_LOGIC := '0';
    signal ap_reg_ppstg_tmp_8_reg_1728_pp0_it2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_V_fu_871_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal or_cond219_i_fu_893_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ImagLoc_x_fu_898_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ImagLoc_x_reg_1741 : STD_LOGIC_VECTOR (11 downto 0);
    signal or_cond_i1_fu_927_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i1_reg_1746 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_40_fu_933_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_40_reg_1751 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_tmp_40_reg_1751_pp0_it1 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_p2_i_fu_947_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_p2_i_reg_1755 : STD_LOGIC_VECTOR (11 downto 0);
    signal sel_tmp7_i_fu_972_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_i_reg_1760 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_fu_984_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_reg_1765 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_tmp_18_reg_1765_pp0_it1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond7_fu_989_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_fu_995_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_reg_1773 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_tmp_20_reg_1773_pp0_it1 : STD_LOGIC_VECTOR (0 downto 0);
    signal col_assign_fu_1000_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal col_assign_reg_1777 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_reg_ppstg_col_assign_reg_1777_pp0_it1 : STD_LOGIC_VECTOR (1 downto 0);
    signal k_buf_0_val_0_addr_reg_1783 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_1_addr_reg_1789 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_2_addr_reg_1795 : STD_LOGIC_VECTOR (10 downto 0);
    signal col_assign_2_fu_1049_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal col_assign_2_reg_1801 : STD_LOGIC_VECTOR (1 downto 0);
    signal src_kernel_win_0_val_0_1_6_reg_1807 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_2_1_9_reg_1812 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_1_1_6_reg_1817 : STD_LOGIC_VECTOR (7 downto 0);
    signal isneg_reg_1822 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_3_fu_1392_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Val2_3_reg_1828 : STD_LOGIC_VECTOR (7 downto 0);
    signal not_i_i_i_fu_1406_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_i_i_i_reg_1833 : STD_LOGIC_VECTOR (0 downto 0);
    signal k_buf_0_val_0_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_0_ce0 : STD_LOGIC;
    signal k_buf_0_val_0_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_0_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_0_ce1 : STD_LOGIC;
    signal k_buf_0_val_0_we1 : STD_LOGIC;
    signal k_buf_0_val_0_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_1_ce0 : STD_LOGIC;
    signal k_buf_0_val_1_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_1_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_1_ce1 : STD_LOGIC;
    signal k_buf_0_val_1_we1 : STD_LOGIC;
    signal k_buf_0_val_1_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_2_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_2_ce0 : STD_LOGIC;
    signal k_buf_0_val_2_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_2_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_2_ce1 : STD_LOGIC;
    signal k_buf_0_val_2_we1 : STD_LOGIC;
    signal k_buf_0_val_2_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_012_0_i_reg_284 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_cseq_ST_st9_fsm_4 : STD_LOGIC;
    signal ap_sig_bdd_298 : BOOLEAN;
    signal tmp_13_fu_1042_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal src_kernel_win_0_val_0_1_fu_138 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_0_0_fu_1075_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_0_0_9_fu_1135_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_0_2_fu_142 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_0_0_3_fu_146 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_2_1_fu_150 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_1_1_fu_154 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_1_0_fu_1090_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_1_2_11_fu_1152_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_1_2_fu_158 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_0_0_5_fu_162 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_2_2_fu_166 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_0_0_6_fu_170 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_1_2_1_fu_174 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_1_2_8_fu_1244_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_1_2_2_fu_178 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_1_2_6_fu_1235_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_1_2_7_fu_182 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_1_2_4_fu_1218_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_0_0_fu_198 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_0_1_fu_202 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_0_2_fu_206 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_363_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_4_fu_379_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_3_fu_389_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_fu_413_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_4_cast_i_cast_fu_419_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_5_i_fu_423_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_10_fu_437_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_4_cast_i46_cast_fu_443_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_11_fu_453_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_i2_fu_457_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_18_cast_fu_471_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ImagLoc_y_fu_492_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_12_fu_504_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_fu_514_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_520_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_551_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_p2_cast1_i40_cast_fu_555_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_i1_fu_546_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_i1_fu_559_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_i1_fu_569_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_i_fu_539_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_assign_2_fu_564_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_22_fu_589_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_23_fu_593_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp7_i1_fu_575_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_fu_585_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_24_fu_597_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal y_1_fu_613_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_27_fu_619_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i2_fu_633_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev_fu_627_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_fu_648_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_assign_3_fu_656_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_p2_i1_fu_662_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal or_cond_i2_fu_638_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_fu_644_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_assign_1_cast_i_fu_679_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_i2_not_fu_692_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_i2_fu_674_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_i2_fu_698_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_1_1_fu_714_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_33_fu_720_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i3_fu_734_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev1_fu_728_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_35_fu_749_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_assign_4_fu_757_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_p2_i2_fu_763_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_i3_not_fu_785_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_i3_fu_775_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_i3_fu_791_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i3_fu_739_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_fu_745_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_assign_1_cast_i1_fu_780_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_498_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond6_fu_525_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_fu_817_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_assign_2_i2_fu_831_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal locy_1_t_fu_836_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal newSel1_fu_852_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_37_fu_877_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp1_fu_887_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_cast_fu_862_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_39_fu_908_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_fu_922_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev2_fu_916_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_assign_fu_941_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_i_not_fu_960_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_i_fu_955_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_i_fu_966_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_fu_978_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_38_fu_904_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_p2_i_cast_fu_1008_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_p2_cast1_i_cast_fu_1011_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_cast_i_cast_fu_1005_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_assign_1_fu_1015_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal sel_tmp_i_fu_1020_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_assign_2_i_fu_1027_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal x_fu_1034_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_41_fu_1038_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp9_fu_1068_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sel_tmp4_fu_1083_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sel_tmp_fu_1117_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_1130_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal col_buf_0_val_0_0_2_fu_1122_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_1_2_fu_1144_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sel_tmp6_fu_1200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_1213_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal right_border_buf_0_val_1_2_3_fu_1205_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_1_2_5_fu_1227_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_147_0_2_cast_fu_1290_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal OP1_V_0_cast_fu_1286_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Val2_3_0_2_fu_1294_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl_fu_1304_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl_cast_fu_1312_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_Val2_s_fu_1316_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_Val2_114_2_fu_1326_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal OP1_V_2_cast_fu_1338_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Val2_2_fu_1342_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_147_1_cast_fu_1322_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_147_2_cast_fu_1348_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Val2_3_0_2_cast_cast_fu_1300_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_147_2_2_cast_cast_fu_1352_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp26_fu_1362_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp132_cast_fu_1368_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_147_1_cast_37_fu_1334_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp27_fu_1372_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp25_fu_1356_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Val2_1_fu_1378_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_28_fu_1396_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_i_i_fu_1424_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_fu_1429_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_i_38_fu_1442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_mux_i_i_cast_fu_1434_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);

    component image_filter_Filter2D_1_k_buf_0_val_0 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    k_buf_0_val_0_U : component image_filter_Filter2D_1_k_buf_0_val_0
    generic map (
        DataWidth => 8,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_0_address0,
        ce0 => k_buf_0_val_0_ce0,
        q0 => k_buf_0_val_0_q0,
        address1 => k_buf_0_val_0_address1,
        ce1 => k_buf_0_val_0_ce1,
        we1 => k_buf_0_val_0_we1,
        d1 => k_buf_0_val_0_d1);

    k_buf_0_val_1_U : component image_filter_Filter2D_1_k_buf_0_val_0
    generic map (
        DataWidth => 8,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_1_address0,
        ce0 => k_buf_0_val_1_ce0,
        q0 => k_buf_0_val_1_q0,
        address1 => k_buf_0_val_1_address1,
        ce1 => k_buf_0_val_1_ce1,
        we1 => k_buf_0_val_1_we1,
        d1 => k_buf_0_val_1_d1);

    k_buf_0_val_2_U : component image_filter_Filter2D_1_k_buf_0_val_0
    generic map (
        DataWidth => 8,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_2_address0,
        ce0 => k_buf_0_val_2_ce0,
        q0 => k_buf_0_val_2_q0,
        address1 => k_buf_0_val_2_address1,
        ce1 => k_buf_0_val_2_ce1,
        we1 => k_buf_0_val_2_we1,
        d1 => k_buf_0_val_2_d1);





    -- the current state (ap_CS_fsm) of the state machine. --
    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it0 assign process. --
    ap_reg_ppiten_pp0_it0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = tmp_8_fu_866_p2))) then 
                    ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then 
                    ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it1 assign process. --
    ap_reg_ppiten_pp0_it1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
                elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then 
                    ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it2 assign process. --
    ap_reg_ppiten_pp0_it2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
            else
                if (not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4))))) then 
                    ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it3 assign process. --
    ap_reg_ppiten_pp0_it3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
            else
                if (not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4))))) then
                    if (not((ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) then 
                        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
                    elsif ((ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) then 
                        ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it4 assign process. --
    ap_reg_ppiten_pp0_it4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
            else
                if (not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4))))) then 
                    ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
                elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then 
                    ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    -- p_012_0_i_reg_284 assign process. --
    p_012_0_i_reg_284_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st9_fsm_4)) then 
                p_012_0_i_reg_284 <= i_V_reg_1637;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_start = ap_const_logic_0)))) then 
                p_012_0_i_reg_284 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;

    -- p_025_0_i_reg_295 assign process. --
    p_025_0_i_reg_295_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_lv1_0 = tmp_8_fu_866_p2)))) then 
                p_025_0_i_reg_295 <= j_V_fu_871_p2;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then 
                p_025_0_i_reg_295 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;

    -- src_kernel_win_0_val_0_1_fu_138 assign process. --
    src_kernel_win_0_val_0_1_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4))))) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and (ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_40_reg_1751_pp0_it1))))) then 
                src_kernel_win_0_val_0_1_fu_138 <= k_buf_0_val_0_q0;
            elsif (((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and (ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_40_reg_1751_pp0_it1) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_18_reg_1765_pp0_it1) and (col_assign_2_reg_1801 = ap_const_lv2_1)) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and (ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_40_reg_1751_pp0_it1) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_18_reg_1765_pp0_it1) and (col_assign_2_reg_1801 = ap_const_lv2_0)) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and (ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_40_reg_1751_pp0_it1) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_18_reg_1765_pp0_it1) and not((col_assign_2_reg_1801 = ap_const_lv2_1)) and not((col_assign_2_reg_1801 = ap_const_lv2_0))))) then 
                src_kernel_win_0_val_0_1_fu_138 <= col_buf_0_val_0_0_9_fu_1135_p3;
            elsif (((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and (ap_const_lv1_0 = brmerge_reg_1700) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = tmp_15_reg_1647) and (locy_2_t_reg_1724 = ap_const_lv2_1)) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and (ap_const_lv1_0 = brmerge_reg_1700) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = tmp_15_reg_1647) and (locy_2_t_reg_1724 = ap_const_lv2_0)) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and (ap_const_lv1_0 = brmerge_reg_1700) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = tmp_15_reg_1647) and not((locy_2_t_reg_1724 = ap_const_lv2_1)) and not((locy_2_t_reg_1724 = ap_const_lv2_0))))) then 
                src_kernel_win_0_val_0_1_fu_138 <= src_kernel_win_0_val_0_0_fu_1075_p3;
            end if; 
        end if;
    end process;

    -- src_kernel_win_0_val_1_1_fu_154 assign process. --
    src_kernel_win_0_val_1_1_fu_154_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4))))) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and (ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_40_reg_1751_pp0_it1))))) then 
                src_kernel_win_0_val_1_1_fu_154 <= k_buf_0_val_1_q0;
            elsif (((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and (ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_40_reg_1751_pp0_it1) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_18_reg_1765_pp0_it1) and (col_assign_2_reg_1801 = ap_const_lv2_1)) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and (ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_40_reg_1751_pp0_it1) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_18_reg_1765_pp0_it1) and (col_assign_2_reg_1801 = ap_const_lv2_0)) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and (ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_40_reg_1751_pp0_it1) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_18_reg_1765_pp0_it1) and not((col_assign_2_reg_1801 = ap_const_lv2_1)) and not((col_assign_2_reg_1801 = ap_const_lv2_0))))) then 
                src_kernel_win_0_val_1_1_fu_154 <= right_border_buf_0_val_1_2_11_fu_1152_p3;
            elsif (((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and (ap_const_lv1_0 = brmerge_reg_1700) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = tmp_15_reg_1647) and (locy_2_t_reg_1724 = ap_const_lv2_1)) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and (ap_const_lv1_0 = brmerge_reg_1700) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = tmp_15_reg_1647) and (locy_2_t_reg_1724 = ap_const_lv2_0)) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and (ap_const_lv1_0 = brmerge_reg_1700) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = tmp_15_reg_1647) and not((locy_2_t_reg_1724 = ap_const_lv2_1)) and not((locy_2_t_reg_1724 = ap_const_lv2_0))))) then 
                src_kernel_win_0_val_1_1_fu_154 <= src_kernel_win_0_val_1_0_fu_1090_p3;
            end if; 
        end if;
    end process;

    -- src_kernel_win_0_val_2_1_fu_150 assign process. --
    src_kernel_win_0_val_2_1_fu_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and (ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_40_reg_1751_pp0_it1) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_18_reg_1765_pp0_it1) and not((col_assign_2_reg_1801 = ap_const_lv2_1)) and not((col_assign_2_reg_1801 = ap_const_lv2_0)))) then 
                src_kernel_win_0_val_2_1_fu_150 <= right_border_buf_0_val_0_2_fu_206;
            elsif ((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and (ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_40_reg_1751_pp0_it1) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_18_reg_1765_pp0_it1) and (col_assign_2_reg_1801 = ap_const_lv2_0))) then 
                src_kernel_win_0_val_2_1_fu_150 <= right_border_buf_0_val_0_0_fu_198;
            elsif ((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and (ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_40_reg_1751_pp0_it1) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_18_reg_1765_pp0_it1) and (col_assign_2_reg_1801 = ap_const_lv2_1))) then 
                src_kernel_win_0_val_2_1_fu_150 <= right_border_buf_0_val_0_1_fu_202;
            elsif (((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4))))) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and (ap_const_lv1_0 = brmerge_reg_1700) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = tmp_15_reg_1647) and not((locy_2_t_reg_1724 = ap_const_lv2_1)) and not((locy_2_t_reg_1724 = ap_const_lv2_0))) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and (ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_40_reg_1751_pp0_it1))))) then 
                src_kernel_win_0_val_2_1_fu_150 <= k_buf_0_val_2_q0;
            elsif ((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and (ap_const_lv1_0 = brmerge_reg_1700) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = tmp_15_reg_1647) and (locy_2_t_reg_1724 = ap_const_lv2_0))) then 
                src_kernel_win_0_val_2_1_fu_150 <= k_buf_0_val_0_q0;
            elsif ((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and (ap_const_lv1_0 = brmerge_reg_1700) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = tmp_15_reg_1647) and (locy_2_t_reg_1724 = ap_const_lv2_1))) then 
                src_kernel_win_0_val_2_1_fu_150 <= k_buf_0_val_1_q0;
            end if; 
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_lv1_0 = tmp_8_fu_866_p2)))) then
                ImagLoc_x_reg_1741 <= ImagLoc_x_fu_898_p2;
                or_cond219_i_reg_1737 <= or_cond219_i_fu_893_p2;
                or_cond_i1_reg_1746 <= or_cond_i1_fu_927_p2;
                p_p2_i_reg_1755 <= p_p2_i_fu_947_p3;
                sel_tmp7_i_reg_1760 <= sel_tmp7_i_fu_972_p2;
                tmp_40_reg_1751 <= ImagLoc_x_fu_898_p2(11 downto 11);
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then
                ap_reg_ppstg_col_assign_reg_1777_pp0_it1 <= col_assign_reg_1777;
                ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it1 <= or_cond219_i_reg_1737;
                ap_reg_ppstg_or_cond7_reg_1769_pp0_it1 <= or_cond7_reg_1769;
                ap_reg_ppstg_tmp_18_reg_1765_pp0_it1 <= tmp_18_reg_1765;
                ap_reg_ppstg_tmp_20_reg_1773_pp0_it1 <= tmp_20_reg_1773;
                ap_reg_ppstg_tmp_40_reg_1751_pp0_it1 <= tmp_40_reg_1751;
                ap_reg_ppstg_tmp_8_reg_1728_pp0_it1 <= tmp_8_reg_1728;
                tmp_8_reg_1728 <= tmp_8_fu_866_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4))))) then
                ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it2 <= ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it1;
                ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it3 <= ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it2;
                ap_reg_ppstg_tmp_8_reg_1728_pp0_it2 <= ap_reg_ppstg_tmp_8_reg_1728_pp0_it1;
                src_kernel_win_0_val_0_1_6_reg_1807 <= src_kernel_win_0_val_0_1_fu_138;
                src_kernel_win_0_val_1_1_6_reg_1817 <= src_kernel_win_0_val_1_1_fu_154;
                src_kernel_win_0_val_2_1_9_reg_1812 <= src_kernel_win_0_val_2_1_fu_150;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((tmp_6_fu_475_p2 = ap_const_lv1_0)))) then
                brmerge_reg_1700 <= brmerge_fu_811_p2;
                newSel_reg_1695 <= newSel_fu_803_p3;
                sel_tmp7_i2_reg_1673 <= sel_tmp7_i2_fu_704_p2;
                sel_tmp7_i3_reg_1690 <= sel_tmp7_i3_fu_797_p2;
                sel_tmp_i2_reg_1668 <= sel_tmp_i2_fu_684_p3;
                tmp_15_reg_1647 <= ImagLoc_y_fu_492_p2(11 downto 11);
                tmp_19_reg_1651 <= tmp_19_fu_581_p1;
                tmp_25_reg_1657 <= tmp_25_fu_605_p3;
                tmp_31_reg_1663 <= tmp_31_fu_670_p1;
                tmp_32_reg_1678 <= tmp_32_fu_710_p1;
                tmp_36_reg_1685 <= tmp_36_fu_771_p1;
                tmp_7_reg_1642 <= tmp_7_fu_486_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not((ap_const_lv1_0 = brmerge_reg_1700)) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_lv1_0 = tmp_8_reg_1728)) and (ap_const_lv1_0 = or_cond7_reg_1769) and (ap_const_lv1_0 = tmp_40_reg_1751) and (ap_const_lv1_0 = tmp_18_reg_1765))) then
                col_assign_2_reg_1801 <= col_assign_2_fu_1049_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not((ap_const_lv1_0 = brmerge_reg_1700)) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_lv1_0 = tmp_8_fu_866_p2)) and not((ap_const_lv1_0 = or_cond7_fu_989_p2)) and (ap_const_lv1_0 = tmp_20_fu_995_p2))) then
                col_assign_reg_1777 <= col_assign_fu_1000_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_20_reg_1773_pp0_it1) and not((ap_reg_ppstg_col_assign_reg_1777_pp0_it1 = ap_const_lv2_1)) and not((ap_reg_ppstg_col_assign_reg_1777_pp0_it1 = ap_const_lv2_0)))) then
                col_buf_0_val_0_0_3_fu_146 <= k_buf_0_val_0_q0;
                right_border_buf_0_val_0_2_fu_206 <= k_buf_0_val_2_q0;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_20_reg_1773_pp0_it1) and (ap_reg_ppstg_col_assign_reg_1777_pp0_it1 = ap_const_lv2_1))) then
                col_buf_0_val_0_0_5_fu_162 <= k_buf_0_val_0_q0;
                right_border_buf_0_val_0_1_fu_202 <= k_buf_0_val_2_q0;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_20_reg_1773_pp0_it1) and (ap_reg_ppstg_col_assign_reg_1777_pp0_it1 = ap_const_lv2_0))) then
                col_buf_0_val_0_0_6_fu_170 <= k_buf_0_val_0_q0;
                right_border_buf_0_val_0_0_fu_198 <= k_buf_0_val_2_q0;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_start = ap_const_logic_0)))) then
                heightloop_reg_1572 <= heightloop_fu_367_p2;
                len_cast4_i30_cast_reg_1614(0) <= len_cast4_i30_cast_fu_433_p1(0);
    len_cast4_i30_cast_reg_1614(1) <= len_cast4_i30_cast_fu_433_p1(1);
    len_cast4_i30_cast_reg_1614(2) <= len_cast4_i30_cast_fu_433_p1(2);
    len_cast4_i30_cast_reg_1614(3) <= len_cast4_i30_cast_fu_433_p1(3);
    len_cast4_i30_cast_reg_1614(4) <= len_cast4_i30_cast_fu_433_p1(4);
    len_cast4_i30_cast_reg_1614(5) <= len_cast4_i30_cast_fu_433_p1(5);
    len_cast4_i30_cast_reg_1614(6) <= len_cast4_i30_cast_fu_433_p1(6);
    len_cast4_i30_cast_reg_1614(7) <= len_cast4_i30_cast_fu_433_p1(7);
    len_cast4_i30_cast_reg_1614(8) <= len_cast4_i30_cast_fu_433_p1(8);
    len_cast4_i30_cast_reg_1614(9) <= len_cast4_i30_cast_fu_433_p1(9);
    len_cast4_i30_cast_reg_1614(10) <= len_cast4_i30_cast_fu_433_p1(10);
                len_cast4_i_cast_reg_1603(0) <= len_cast4_i_cast_fu_409_p1(0);
    len_cast4_i_cast_reg_1603(1) <= len_cast4_i_cast_fu_409_p1(1);
    len_cast4_i_cast_reg_1603(2) <= len_cast4_i_cast_fu_409_p1(2);
    len_cast4_i_cast_reg_1603(3) <= len_cast4_i_cast_fu_409_p1(3);
    len_cast4_i_cast_reg_1603(4) <= len_cast4_i_cast_fu_409_p1(4);
    len_cast4_i_cast_reg_1603(5) <= len_cast4_i_cast_fu_409_p1(5);
    len_cast4_i_cast_reg_1603(6) <= len_cast4_i_cast_fu_409_p1(6);
    len_cast4_i_cast_reg_1603(7) <= len_cast4_i_cast_fu_409_p1(7);
    len_cast4_i_cast_reg_1603(8) <= len_cast4_i_cast_fu_409_p1(8);
    len_cast4_i_cast_reg_1603(9) <= len_cast4_i_cast_fu_409_p1(9);
    len_cast4_i_cast_reg_1603(10) <= len_cast4_i_cast_fu_409_p1(10);
                p_neg226_i_cast_reg_1587 <= p_neg226_i_cast_fu_393_p2;
                ref_cast_reg_1598(0) <= ref_cast_fu_405_p1(0);
    ref_cast_reg_1598(1) <= ref_cast_fu_405_p1(1);
    ref_cast_reg_1598(2) <= ref_cast_fu_405_p1(2);
    ref_cast_reg_1598(3) <= ref_cast_fu_405_p1(3);
    ref_cast_reg_1598(4) <= ref_cast_fu_405_p1(4);
    ref_cast_reg_1598(5) <= ref_cast_fu_405_p1(5);
    ref_cast_reg_1598(6) <= ref_cast_fu_405_p1(6);
    ref_cast_reg_1598(7) <= ref_cast_fu_405_p1(7);
    ref_cast_reg_1598(8) <= ref_cast_fu_405_p1(8);
    ref_cast_reg_1598(9) <= ref_cast_fu_405_p1(9);
    ref_cast_reg_1598(10) <= ref_cast_fu_405_p1(10);
                ref_reg_1593 <= ref_fu_399_p2;
                tmp_17_cast_reg_1582(0) <= tmp_17_cast_fu_385_p1(0);
    tmp_17_cast_reg_1582(1) <= tmp_17_cast_fu_385_p1(1);
    tmp_17_cast_reg_1582(2) <= tmp_17_cast_fu_385_p1(2);
    tmp_17_cast_reg_1582(3) <= tmp_17_cast_fu_385_p1(3);
    tmp_17_cast_reg_1582(4) <= tmp_17_cast_fu_385_p1(4);
    tmp_17_cast_reg_1582(5) <= tmp_17_cast_fu_385_p1(5);
    tmp_17_cast_reg_1582(6) <= tmp_17_cast_fu_385_p1(6);
    tmp_17_cast_reg_1582(7) <= tmp_17_cast_fu_385_p1(7);
    tmp_17_cast_reg_1582(8) <= tmp_17_cast_fu_385_p1(8);
    tmp_17_cast_reg_1582(9) <= tmp_17_cast_fu_385_p1(9);
    tmp_17_cast_reg_1582(10) <= tmp_17_cast_fu_385_p1(10);
                tmp_1_reg_1567 <= tmp_1_fu_359_p1;
                tmp_5_cast_i_reg_1609(1) <= tmp_5_cast_i_fu_429_p1(1);
    tmp_5_cast_i_reg_1609(2) <= tmp_5_cast_i_fu_429_p1(2);
    tmp_5_cast_i_reg_1609(3) <= tmp_5_cast_i_fu_429_p1(3);
    tmp_5_cast_i_reg_1609(4) <= tmp_5_cast_i_fu_429_p1(4);
    tmp_5_cast_i_reg_1609(5) <= tmp_5_cast_i_fu_429_p1(5);
    tmp_5_cast_i_reg_1609(6) <= tmp_5_cast_i_fu_429_p1(6);
    tmp_5_cast_i_reg_1609(7) <= tmp_5_cast_i_fu_429_p1(7);
    tmp_5_cast_i_reg_1609(8) <= tmp_5_cast_i_fu_429_p1(8);
    tmp_5_cast_i_reg_1609(9) <= tmp_5_cast_i_fu_429_p1(9);
    tmp_5_cast_i_reg_1609(10) <= tmp_5_cast_i_fu_429_p1(10);
    tmp_5_cast_i_reg_1609(11) <= tmp_5_cast_i_fu_429_p1(11);
    tmp_5_cast_i_reg_1609(12) <= tmp_5_cast_i_fu_429_p1(12);
    tmp_5_cast_i_reg_1609(13) <= tmp_5_cast_i_fu_429_p1(13);
    tmp_5_cast_i_reg_1609(14) <= tmp_5_cast_i_fu_429_p1(14);
                tmp_5_i1_reg_1623(1) <= tmp_5_i1_fu_447_p2(1);
    tmp_5_i1_reg_1623(2) <= tmp_5_i1_fu_447_p2(2);
    tmp_5_i1_reg_1623(3) <= tmp_5_i1_fu_447_p2(3);
    tmp_5_i1_reg_1623(4) <= tmp_5_i1_fu_447_p2(4);
    tmp_5_i1_reg_1623(5) <= tmp_5_i1_fu_447_p2(5);
    tmp_5_i1_reg_1623(6) <= tmp_5_i1_fu_447_p2(6);
    tmp_5_i1_reg_1623(7) <= tmp_5_i1_fu_447_p2(7);
    tmp_5_i1_reg_1623(8) <= tmp_5_i1_fu_447_p2(8);
    tmp_5_i1_reg_1623(9) <= tmp_5_i1_fu_447_p2(9);
    tmp_5_i1_reg_1623(10) <= tmp_5_i1_fu_447_p2(10);
    tmp_5_i1_reg_1623(11) <= tmp_5_i1_fu_447_p2(11);
    tmp_5_i1_reg_1623(12) <= tmp_5_i1_fu_447_p2(12);
                tmp_5_i2_reg_1628 <= tmp_5_i2_fu_465_p2;
                widthloop_reg_1577 <= widthloop_fu_373_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then
                i_V_reg_1637 <= i_V_fu_480_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it2)))) then
                isneg_reg_1822 <= p_Val2_1_fu_1378_p2(10 downto 10);
                not_i_i_i_reg_1833 <= not_i_i_i_fu_1406_p2;
                p_Val2_3_reg_1828 <= p_Val2_3_fu_1392_p1;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_lv1_0 = tmp_8_reg_1728)))) then
                k_buf_0_val_0_addr_reg_1783 <= tmp_13_fu_1042_p1(11 - 1 downto 0);
                k_buf_0_val_1_addr_reg_1789 <= tmp_13_fu_1042_p1(11 - 1 downto 0);
                k_buf_0_val_2_addr_reg_1795 <= tmp_13_fu_1042_p1(11 - 1 downto 0);
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then
                locy_2_t_reg_1724 <= locy_2_t_fu_857_p2;
                sel_tmp1_reg_1709 <= sel_tmp1_fu_825_p2;
                sel_tmp3_reg_1714 <= sel_tmp3_fu_841_p2;
                sel_tmp5_reg_1719 <= sel_tmp5_fu_846_p2;
                sel_tmp8_reg_1704 <= sel_tmp8_fu_821_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not((ap_const_lv1_0 = brmerge_reg_1700)) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_lv1_0 = tmp_8_fu_866_p2)))) then
                or_cond7_reg_1769 <= or_cond7_fu_989_p2;
                tmp_18_reg_1765 <= tmp_18_fu_984_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_20_reg_1773_pp0_it1) and not((ap_reg_ppstg_col_assign_reg_1777_pp0_it1 = ap_const_lv2_1)) and not((ap_reg_ppstg_col_assign_reg_1777_pp0_it1 = ap_const_lv2_0))) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_20_reg_1773_pp0_it1) and (ap_reg_ppstg_col_assign_reg_1777_pp0_it1 = ap_const_lv2_1)) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_20_reg_1773_pp0_it1) and (ap_reg_ppstg_col_assign_reg_1777_pp0_it1 = ap_const_lv2_0)))) then
                right_border_buf_0_val_1_2_1_fu_174 <= right_border_buf_0_val_1_2_8_fu_1244_p3;
                right_border_buf_0_val_1_2_2_fu_178 <= right_border_buf_0_val_1_2_6_fu_1235_p3;
                right_border_buf_0_val_1_2_7_fu_182 <= right_border_buf_0_val_1_2_4_fu_1218_p3;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_reg_ppiten_pp0_it3) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it2)))) then
                src_kernel_win_0_val_0_2_fu_142 <= src_kernel_win_0_val_0_1_6_reg_1807;
                src_kernel_win_0_val_1_2_fu_158 <= src_kernel_win_0_val_1_1_6_reg_1817;
                src_kernel_win_0_val_2_2_fu_166 <= src_kernel_win_0_val_2_1_9_reg_1812;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not((ap_const_lv1_0 = brmerge_reg_1700)) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_lv1_0 = tmp_8_fu_866_p2)) and not((ap_const_lv1_0 = or_cond7_fu_989_p2)))) then
                tmp_20_reg_1773 <= tmp_20_fu_995_p2;
            end if;
        end if;
    end process;
    tmp_17_cast_reg_1582(11) <= '0';
    ref_cast_reg_1598(11) <= '0';
    len_cast4_i_cast_reg_1603(11) <= '0';
    tmp_5_cast_i_reg_1609(0) <= '0';
    len_cast4_i30_cast_reg_1614(11) <= '0';
    tmp_5_i1_reg_1623(0) <= '0';

    -- the next state (ap_NS_fsm) of the state machine. --
    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, tmp_6_fu_475_p2, ap_reg_ppiten_pp0_it1, ap_sig_bdd_150, ap_reg_ppiten_pp0_it2, ap_reg_ppiten_pp0_it3, ap_sig_bdd_162, ap_reg_ppiten_pp0_it4)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                if (not((ap_start = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                end if;
            when ap_ST_st2_fsm_1 => 
                if ((tmp_6_fu_475_p2 = ap_const_lv1_0)) then
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                else
                    ap_NS_fsm <= ap_ST_st3_fsm_2;
                end if;
            when ap_ST_st3_fsm_2 => 
                ap_NS_fsm <= ap_ST_pp0_stg0_fsm_3;
            when ap_ST_pp0_stg0_fsm_3 => 
                if ((not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it4) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it3)))) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it3)))))) then
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_3;
                elsif ((((ap_const_logic_1 = ap_reg_ppiten_pp0_it4) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it3))) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it3))))) then
                    ap_NS_fsm <= ap_ST_st9_fsm_4;
                else
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_3;
                end if;
            when ap_ST_st9_fsm_4 => 
                ap_NS_fsm <= ap_ST_st2_fsm_1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ImagLoc_x_fu_898_p2 <= std_logic_vector(unsigned(tmp_21_cast_fu_862_p1) + unsigned(ap_const_lv12_FFF));
    ImagLoc_y_fu_492_p2 <= std_logic_vector(unsigned(tmp_18_cast_fu_471_p1) + unsigned(ap_const_lv12_FFC));
    OP1_V_0_cast_fu_1286_p1 <= std_logic_vector(resize(unsigned(src_kernel_win_0_val_2_2_fu_166),9));
    OP1_V_2_cast_fu_1338_p1 <= std_logic_vector(resize(unsigned(src_kernel_win_0_val_0_2_fu_142),9));

    -- ap_done assign process. --
    ap_done_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0, ap_sig_cseq_ST_st2_fsm_1, tmp_6_fu_475_p2)
    begin
        if (((not((ap_const_logic_1 = ap_start)) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (tmp_6_fu_475_p2 = ap_const_lv1_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_idle assign process. --
    ap_idle_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0)
    begin
        if ((not((ap_const_logic_1 = ap_start)) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_ready assign process. --
    ap_ready_assign_proc : process(ap_sig_cseq_ST_st2_fsm_1, tmp_6_fu_475_p2)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (tmp_6_fu_475_p2 = ap_const_lv1_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_bdd_114 assign process. --
    ap_sig_bdd_114_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_114 <= (ap_const_lv1_1 = ap_CS_fsm(2 downto 2));
    end process;


    -- ap_sig_bdd_131 assign process. --
    ap_sig_bdd_131_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_131 <= (ap_const_lv1_1 = ap_CS_fsm(3 downto 3));
    end process;


    -- ap_sig_bdd_150 assign process. --
    ap_sig_bdd_150_assign_proc : process(p_src_data_stream_V_empty_n, brmerge_reg_1700, ap_reg_ppstg_tmp_8_reg_1728_pp0_it1, ap_reg_ppstg_or_cond7_reg_1769_pp0_it1)
    begin
                ap_sig_bdd_150 <= ((p_src_data_stream_V_empty_n = ap_const_logic_0) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1)));
    end process;


    -- ap_sig_bdd_162 assign process. --
    ap_sig_bdd_162_assign_proc : process(p_dst_data_stream_V_full_n, ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it3)
    begin
                ap_sig_bdd_162 <= ((p_dst_data_stream_V_full_n = ap_const_logic_0) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it3)));
    end process;


    -- ap_sig_bdd_23 assign process. --
    ap_sig_bdd_23_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_23 <= (ap_CS_fsm(0 downto 0) = ap_const_lv1_1);
    end process;


    -- ap_sig_bdd_298 assign process. --
    ap_sig_bdd_298_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_298 <= (ap_const_lv1_1 = ap_CS_fsm(4 downto 4));
    end process;


    -- ap_sig_bdd_76 assign process. --
    ap_sig_bdd_76_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_76 <= (ap_const_lv1_1 = ap_CS_fsm(1 downto 1));
    end process;


    -- ap_sig_cseq_ST_pp0_stg0_fsm_3 assign process. --
    ap_sig_cseq_ST_pp0_stg0_fsm_3_assign_proc : process(ap_sig_bdd_131)
    begin
        if (ap_sig_bdd_131) then 
            ap_sig_cseq_ST_pp0_stg0_fsm_3 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_pp0_stg0_fsm_3 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st1_fsm_0 assign process. --
    ap_sig_cseq_ST_st1_fsm_0_assign_proc : process(ap_sig_bdd_23)
    begin
        if (ap_sig_bdd_23) then 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st2_fsm_1 assign process. --
    ap_sig_cseq_ST_st2_fsm_1_assign_proc : process(ap_sig_bdd_76)
    begin
        if (ap_sig_bdd_76) then 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st3_fsm_2 assign process. --
    ap_sig_cseq_ST_st3_fsm_2_assign_proc : process(ap_sig_bdd_114)
    begin
        if (ap_sig_bdd_114) then 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st9_fsm_4 assign process. --
    ap_sig_cseq_ST_st9_fsm_4_assign_proc : process(ap_sig_bdd_298)
    begin
        if (ap_sig_bdd_298) then 
            ap_sig_cseq_ST_st9_fsm_4 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st9_fsm_4 <= ap_const_logic_0;
        end if; 
    end process;

    brmerge_fu_811_p2 <= (tmp_s_fu_498_p2 or or_cond6_fu_525_p2);
    col_assign_2_fu_1049_p2 <= std_logic_vector(unsigned(tmp_41_fu_1038_p1) + unsigned(p_neg226_i_cast_reg_1587));
    col_assign_fu_1000_p2 <= std_logic_vector(unsigned(tmp_38_fu_904_p1) + unsigned(p_neg226_i_cast_reg_1587));
    col_buf_0_val_0_0_2_fu_1122_p3 <= 
        col_buf_0_val_0_0_5_fu_162 when (sel_tmp_fu_1117_p2(0) = '1') else 
        col_buf_0_val_0_0_3_fu_146;
    col_buf_0_val_0_0_9_fu_1135_p3 <= 
        col_buf_0_val_0_0_6_fu_170 when (sel_tmp2_fu_1130_p2(0) = '1') else 
        col_buf_0_val_0_0_2_fu_1122_p3;
    heightloop_fu_367_p2 <= std_logic_vector(unsigned(tmp_1_fu_359_p1) + unsigned(ap_const_lv11_5));
    i_V_fu_480_p2 <= std_logic_vector(unsigned(p_012_0_i_reg_284) + unsigned(ap_const_lv11_1));
    icmp1_fu_887_p2 <= "0" when (tmp_37_fu_877_p4 = ap_const_lv10_0) else "1";
    icmp_fu_514_p2 <= "1" when (signed(tmp_12_fu_504_p4) > signed(ap_const_lv11_0)) else "0";
    j_V_fu_871_p2 <= std_logic_vector(unsigned(p_025_0_i_reg_295) + unsigned(ap_const_lv11_1));
    k_buf_0_val_0_address0 <= tmp_13_fu_1042_p1(11 - 1 downto 0);
    k_buf_0_val_0_address1 <= k_buf_0_val_0_addr_reg_1783;

    -- k_buf_0_val_0_ce0 assign process. --
    k_buf_0_val_0_ce0_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_3, ap_reg_ppiten_pp0_it1, ap_sig_bdd_150, ap_reg_ppiten_pp0_it2, ap_sig_bdd_162, ap_reg_ppiten_pp0_it4)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then 
            k_buf_0_val_0_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    -- k_buf_0_val_0_ce1 assign process. --
    k_buf_0_val_0_ce1_assign_proc : process(ap_sig_bdd_150, ap_reg_ppiten_pp0_it2, ap_sig_bdd_162, ap_reg_ppiten_pp0_it4)
    begin
        if (((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then 
            k_buf_0_val_0_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    k_buf_0_val_0_d1 <= p_src_data_stream_V_dout;

    -- k_buf_0_val_0_we1 assign process. --
    k_buf_0_val_0_we1_assign_proc : process(brmerge_reg_1700, ap_reg_ppstg_tmp_8_reg_1728_pp0_it1, ap_reg_ppstg_or_cond7_reg_1769_pp0_it1, ap_sig_bdd_150, ap_reg_ppiten_pp0_it2, ap_sig_bdd_162, ap_reg_ppiten_pp0_it4)
    begin
        if (((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4))))))) then 
            k_buf_0_val_0_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_0_we1 <= ap_const_logic_0;
        end if; 
    end process;

    k_buf_0_val_1_address0 <= tmp_13_fu_1042_p1(11 - 1 downto 0);
    k_buf_0_val_1_address1 <= k_buf_0_val_1_addr_reg_1789;

    -- k_buf_0_val_1_ce0 assign process. --
    k_buf_0_val_1_ce0_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_3, ap_reg_ppiten_pp0_it1, ap_sig_bdd_150, ap_reg_ppiten_pp0_it2, ap_sig_bdd_162, ap_reg_ppiten_pp0_it4)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then 
            k_buf_0_val_1_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    -- k_buf_0_val_1_ce1 assign process. --
    k_buf_0_val_1_ce1_assign_proc : process(brmerge_reg_1700, ap_reg_ppstg_tmp_8_reg_1728_pp0_it1, ap_reg_ppstg_or_cond7_reg_1769_pp0_it1, ap_sig_bdd_150, ap_reg_ppiten_pp0_it2, ap_sig_bdd_162, ap_reg_ppiten_pp0_it4, ap_reg_ppstg_tmp_20_reg_1773_pp0_it1)
    begin
        if (((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_20_reg_1773_pp0_it1)) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_20_reg_1773_pp0_it1))))) then 
            k_buf_0_val_1_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    k_buf_0_val_1_d1 <= k_buf_0_val_0_q0;

    -- k_buf_0_val_1_we1 assign process. --
    k_buf_0_val_1_we1_assign_proc : process(brmerge_reg_1700, ap_reg_ppstg_tmp_8_reg_1728_pp0_it1, ap_reg_ppstg_or_cond7_reg_1769_pp0_it1, ap_sig_bdd_150, ap_reg_ppiten_pp0_it2, ap_sig_bdd_162, ap_reg_ppiten_pp0_it4, ap_reg_ppstg_tmp_20_reg_1773_pp0_it1)
    begin
        if (((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_20_reg_1773_pp0_it1)) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_20_reg_1773_pp0_it1))))) then 
            k_buf_0_val_1_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_1_we1 <= ap_const_logic_0;
        end if; 
    end process;

    k_buf_0_val_2_address0 <= tmp_13_fu_1042_p1(11 - 1 downto 0);
    k_buf_0_val_2_address1 <= k_buf_0_val_2_addr_reg_1795;

    -- k_buf_0_val_2_ce0 assign process. --
    k_buf_0_val_2_ce0_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_3, ap_reg_ppiten_pp0_it1, ap_sig_bdd_150, ap_reg_ppiten_pp0_it2, ap_sig_bdd_162, ap_reg_ppiten_pp0_it4)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then 
            k_buf_0_val_2_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    -- k_buf_0_val_2_ce1 assign process. --
    k_buf_0_val_2_ce1_assign_proc : process(brmerge_reg_1700, ap_reg_ppstg_tmp_8_reg_1728_pp0_it1, ap_reg_ppstg_or_cond7_reg_1769_pp0_it1, ap_sig_bdd_150, ap_reg_ppiten_pp0_it2, ap_sig_bdd_162, ap_reg_ppiten_pp0_it4, ap_reg_ppstg_tmp_20_reg_1773_pp0_it1)
    begin
        if (((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_20_reg_1773_pp0_it1)) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_20_reg_1773_pp0_it1))))) then 
            k_buf_0_val_2_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    k_buf_0_val_2_d1 <= k_buf_0_val_1_q0;

    -- k_buf_0_val_2_we1 assign process. --
    k_buf_0_val_2_we1_assign_proc : process(brmerge_reg_1700, ap_reg_ppstg_tmp_8_reg_1728_pp0_it1, ap_reg_ppstg_or_cond7_reg_1769_pp0_it1, ap_sig_bdd_150, ap_reg_ppiten_pp0_it2, ap_sig_bdd_162, ap_reg_ppiten_pp0_it4, ap_reg_ppstg_tmp_20_reg_1773_pp0_it1)
    begin
        if (((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_20_reg_1773_pp0_it1)) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_20_reg_1773_pp0_it1))))) then 
            k_buf_0_val_2_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_2_we1 <= ap_const_logic_0;
        end if; 
    end process;

    len_cast4_i30_cast_fu_433_p1 <= std_logic_vector(resize(unsigned(tmp_1_fu_359_p1),12));
    len_cast4_i_cast_fu_409_p1 <= std_logic_vector(resize(unsigned(tmp_2_fu_363_p1),12));
    locy_1_t_fu_836_p2 <= std_logic_vector(unsigned(tmp_32_reg_1678) - unsigned(p_assign_2_i2_fu_831_p3));
    locy_2_t_fu_857_p2 <= std_logic_vector(unsigned(tmp_32_reg_1678) - unsigned(newSel1_fu_852_p3));
    newSel1_fu_852_p3 <= 
        tmp_36_reg_1685 when (sel_tmp7_i3_reg_1690(0) = '1') else 
        newSel_reg_1695;
    newSel_fu_803_p3 <= 
        tmp_34_fu_745_p1 when (or_cond_i3_fu_739_p2(0) = '1') else 
        p_assign_1_cast_i1_fu_780_p2;
    not_i_i_i_fu_1406_p2 <= "0" when (tmp_28_fu_1396_p4 = ap_const_lv3_0) else "1";
    or_cond219_i_fu_893_p2 <= (tmp_7_reg_1642 and icmp1_fu_887_p2);
    or_cond6_fu_525_p2 <= (icmp_fu_514_p2 and tmp_14_fu_520_p2);
    or_cond7_fu_989_p2 <= (tmp_17_fu_978_p2 and tmp_18_fu_984_p2);
    or_cond_i1_fu_927_p2 <= (tmp_i_fu_922_p2 and rev2_fu_916_p2);
    or_cond_i2_fu_638_p2 <= (tmp_i2_fu_633_p2 and rev_fu_627_p2);
    or_cond_i3_fu_739_p2 <= (tmp_i3_fu_734_p2 and rev1_fu_728_p2);
    overflow_fu_1429_p2 <= (not_i_i_i_reg_1833 and tmp_i_i_fu_1424_p2);
    p_Val2_114_2_fu_1326_p3 <= (src_kernel_win_0_val_1_1_fu_154 & ap_const_lv1_0);
    p_Val2_1_fu_1378_p2 <= std_logic_vector(signed(tmp27_fu_1372_p2) + signed(tmp25_fu_1356_p2));
    p_Val2_2_fu_1342_p2 <= std_logic_vector(unsigned(ap_const_lv9_0) - unsigned(OP1_V_2_cast_fu_1338_p1));
        p_Val2_3_0_2_cast_cast_fu_1300_p1 <= std_logic_vector(resize(signed(p_Val2_3_0_2_fu_1294_p2),10));

    p_Val2_3_0_2_fu_1294_p2 <= std_logic_vector(unsigned(tmp_147_0_2_cast_fu_1290_p1) - unsigned(OP1_V_0_cast_fu_1286_p1));
    p_Val2_3_fu_1392_p1 <= p_Val2_1_fu_1378_p2(8 - 1 downto 0);
    p_Val2_s_fu_1316_p2 <= std_logic_vector(unsigned(ap_const_lv10_0) - unsigned(p_shl_cast_fu_1312_p1));
    p_assign_1_cast_i1_fu_780_p2 <= std_logic_vector(unsigned(tmp_5_i2_reg_1628) - unsigned(tmp_36_fu_771_p1));
    p_assign_1_cast_i_fu_679_p2 <= std_logic_vector(unsigned(tmp_5_i2_reg_1628) - unsigned(tmp_31_fu_670_p1));
    p_assign_1_fu_1015_p2 <= std_logic_vector(signed(tmp_5_cast_i_reg_1609) - signed(p_p2_cast1_i_cast_fu_1011_p1));
    p_assign_2_fu_564_p2 <= std_logic_vector(unsigned(tmp_5_i1_reg_1623) - unsigned(p_p2_cast1_i40_cast_fu_555_p1));
    p_assign_2_i2_fu_831_p3 <= 
        tmp_31_reg_1663 when (sel_tmp7_i2_reg_1673(0) = '1') else 
        sel_tmp_i2_reg_1668;
    p_assign_2_i_fu_1027_p3 <= 
        p_p2_cast1_i_cast_fu_1011_p1 when (sel_tmp7_i_reg_1760(0) = '1') else 
        sel_tmp_i_fu_1020_p3;
    p_assign_3_fu_656_p2 <= std_logic_vector(unsigned(ap_const_lv12_5) - unsigned(tmp_18_cast_fu_471_p1));
    p_assign_4_fu_757_p2 <= std_logic_vector(unsigned(ap_const_lv12_6) - unsigned(tmp_18_cast_fu_471_p1));
    p_assign_fu_941_p2 <= std_logic_vector(unsigned(ap_const_lv12_1) - unsigned(tmp_21_cast_fu_862_p1));
        p_cast_i_cast_fu_1005_p1 <= std_logic_vector(resize(signed(ImagLoc_x_reg_1741),15));

    p_dst_data_stream_V_din <= 
        p_mux_i_i_cast_fu_1434_p3 when (tmp_i_i_38_fu_1442_p2(0) = '1') else 
        p_Val2_3_reg_1828;

    -- p_dst_data_stream_V_write assign process. --
    p_dst_data_stream_V_write_assign_proc : process(ap_sig_bdd_150, ap_reg_ppiten_pp0_it2, ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it3, ap_sig_bdd_162, ap_reg_ppiten_pp0_it4)
    begin
        if ((not((ap_const_lv1_0 = ap_reg_ppstg_or_cond219_i_reg_1737_pp0_it3)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then 
            p_dst_data_stream_V_write <= ap_const_logic_1;
        else 
            p_dst_data_stream_V_write <= ap_const_logic_0;
        end if; 
    end process;

    p_i_fu_539_p3 <= 
        ap_const_lv11_2 when (tmp_14_fu_520_p2(0) = '1') else 
        ref_reg_1593;
    p_mux_i_i_cast_fu_1434_p3 <= 
        ap_const_lv8_FF when (tmp_i_i_fu_1424_p2(0) = '1') else 
        ap_const_lv8_0;
    p_neg226_i_cast_fu_393_p2 <= (tmp_3_fu_389_p1 xor ap_const_lv2_3);
    p_p2_cast1_i40_cast_fu_555_p1 <= std_logic_vector(resize(unsigned(tmp_16_fu_551_p1),13));
    p_p2_cast1_i_cast_fu_1011_p1 <= std_logic_vector(resize(unsigned(p_p2_i_cast_fu_1008_p1),15));
    p_p2_i1_fu_662_p3 <= 
        p_assign_3_fu_656_p2 when (tmp_30_fu_648_p3(0) = '1') else 
        y_1_fu_613_p2;
    p_p2_i2_fu_763_p3 <= 
        p_assign_4_fu_757_p2 when (tmp_35_fu_749_p3(0) = '1') else 
        y_1_1_fu_714_p2;
        p_p2_i_cast_fu_1008_p1 <= std_logic_vector(resize(signed(p_p2_i_reg_1755),14));

    p_p2_i_fu_947_p3 <= 
        p_assign_fu_941_p2 when (tmp_40_fu_933_p3(0) = '1') else 
        ImagLoc_x_fu_898_p2;
    p_shl_cast_fu_1312_p1 <= std_logic_vector(resize(unsigned(p_shl_fu_1304_p3),10));
    p_shl_fu_1304_p3 <= (src_kernel_win_0_val_1_2_fu_158 & ap_const_lv1_0);

    -- p_src_data_stream_V_read assign process. --
    p_src_data_stream_V_read_assign_proc : process(brmerge_reg_1700, ap_reg_ppstg_tmp_8_reg_1728_pp0_it1, ap_reg_ppstg_or_cond7_reg_1769_pp0_it1, ap_sig_bdd_150, ap_reg_ppiten_pp0_it2, ap_sig_bdd_162, ap_reg_ppiten_pp0_it4)
    begin
        if ((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_8_reg_1728_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1700)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond7_reg_1769_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_150 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_162 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then 
            p_src_data_stream_V_read <= ap_const_logic_1;
        else 
            p_src_data_stream_V_read <= ap_const_logic_0;
        end if; 
    end process;

    ref_cast_fu_405_p1 <= std_logic_vector(resize(unsigned(ref_fu_399_p2),12));
    ref_fu_399_p2 <= std_logic_vector(unsigned(tmp_1_fu_359_p1) + unsigned(ap_const_lv11_7FF));
    rev1_fu_728_p2 <= (tmp_33_fu_720_p3 xor ap_const_lv1_1);
    rev2_fu_916_p2 <= (tmp_39_fu_908_p3 xor ap_const_lv1_1);
    rev_fu_627_p2 <= (tmp_27_fu_619_p3 xor ap_const_lv1_1);
    right_border_buf_0_val_1_2_11_fu_1152_p3 <= 
        right_border_buf_0_val_1_2_1_fu_174 when (sel_tmp2_fu_1130_p2(0) = '1') else 
        right_border_buf_0_val_1_2_fu_1144_p3;
    right_border_buf_0_val_1_2_3_fu_1205_p3 <= 
        right_border_buf_0_val_1_2_7_fu_182 when (sel_tmp6_fu_1200_p2(0) = '1') else 
        k_buf_0_val_1_q0;
    right_border_buf_0_val_1_2_4_fu_1218_p3 <= 
        right_border_buf_0_val_1_2_7_fu_182 when (sel_tmp7_fu_1213_p2(0) = '1') else 
        right_border_buf_0_val_1_2_3_fu_1205_p3;
    right_border_buf_0_val_1_2_5_fu_1227_p3 <= 
        k_buf_0_val_1_q0 when (sel_tmp6_fu_1200_p2(0) = '1') else 
        right_border_buf_0_val_1_2_2_fu_178;
    right_border_buf_0_val_1_2_6_fu_1235_p3 <= 
        right_border_buf_0_val_1_2_2_fu_178 when (sel_tmp7_fu_1213_p2(0) = '1') else 
        right_border_buf_0_val_1_2_5_fu_1227_p3;
    right_border_buf_0_val_1_2_8_fu_1244_p3 <= 
        k_buf_0_val_1_q0 when (sel_tmp7_fu_1213_p2(0) = '1') else 
        right_border_buf_0_val_1_2_1_fu_174;
    right_border_buf_0_val_1_2_fu_1144_p3 <= 
        right_border_buf_0_val_1_2_2_fu_178 when (sel_tmp_fu_1117_p2(0) = '1') else 
        right_border_buf_0_val_1_2_7_fu_182;
    sel_tmp1_fu_825_p2 <= "1" when (tmp_26_fu_817_p2 = ap_const_lv2_1) else "0";
    sel_tmp2_fu_1130_p2 <= "1" when (col_assign_2_reg_1801 = ap_const_lv2_0) else "0";
    sel_tmp3_fu_841_p2 <= "1" when (tmp_32_reg_1678 = p_assign_2_i2_fu_831_p3) else "0";
    sel_tmp4_fu_1083_p3 <= 
        k_buf_0_val_0_q0 when (sel_tmp3_reg_1714(0) = '1') else 
        k_buf_0_val_2_q0;
    sel_tmp5_fu_846_p2 <= "1" when (locy_1_t_fu_836_p2 = ap_const_lv2_1) else "0";
    sel_tmp6_fu_1200_p2 <= "1" when (ap_reg_ppstg_col_assign_reg_1777_pp0_it1 = ap_const_lv2_1) else "0";
    sel_tmp6_i1_fu_569_p2 <= (tmp_i1_fu_546_p2 xor ap_const_lv1_1);
    sel_tmp6_i2_fu_698_p2 <= (tmp_27_fu_619_p3 or tmp_i2_not_fu_692_p2);
    sel_tmp6_i3_fu_791_p2 <= (tmp_33_fu_720_p3 or tmp_i3_not_fu_785_p2);
    sel_tmp6_i_fu_966_p2 <= (tmp_39_fu_908_p3 or tmp_i_not_fu_960_p2);
    sel_tmp7_fu_1213_p2 <= "1" when (ap_reg_ppstg_col_assign_reg_1777_pp0_it1 = ap_const_lv2_0) else "0";
    sel_tmp7_i1_fu_575_p2 <= (tmp_3_i1_fu_559_p2 and sel_tmp6_i1_fu_569_p2);
    sel_tmp7_i2_fu_704_p2 <= (tmp_3_i2_fu_674_p2 and sel_tmp6_i2_fu_698_p2);
    sel_tmp7_i3_fu_797_p2 <= (tmp_3_i3_fu_775_p2 and sel_tmp6_i3_fu_791_p2);
    sel_tmp7_i_fu_972_p2 <= (tmp_3_i_fu_955_p2 and sel_tmp6_i_fu_966_p2);
    sel_tmp8_fu_821_p2 <= "1" when (tmp_19_reg_1651 = tmp_25_reg_1657) else "0";
    sel_tmp9_fu_1068_p3 <= 
        k_buf_0_val_0_q0 when (sel_tmp8_reg_1704(0) = '1') else 
        k_buf_0_val_2_q0;
    sel_tmp_fu_1117_p2 <= "1" when (col_assign_2_reg_1801 = ap_const_lv2_1) else "0";
    sel_tmp_i2_fu_684_p3 <= 
        tmp_29_fu_644_p1 when (or_cond_i2_fu_638_p2(0) = '1') else 
        p_assign_1_cast_i_fu_679_p2;
    sel_tmp_i_fu_1020_p3 <= 
        p_cast_i_cast_fu_1005_p1 when (or_cond_i1_reg_1746(0) = '1') else 
        p_assign_1_fu_1015_p2;
    src_kernel_win_0_val_0_0_fu_1075_p3 <= 
        k_buf_0_val_1_q0 when (sel_tmp1_reg_1709(0) = '1') else 
        sel_tmp9_fu_1068_p3;
    src_kernel_win_0_val_1_0_fu_1090_p3 <= 
        k_buf_0_val_1_q0 when (sel_tmp5_reg_1719(0) = '1') else 
        sel_tmp4_fu_1083_p3;
        tmp132_cast_fu_1368_p1 <= std_logic_vector(resize(signed(tmp26_fu_1362_p2),11));

    tmp25_fu_1356_p2 <= std_logic_vector(signed(tmp_147_1_cast_fu_1322_p1) + signed(tmp_147_2_cast_fu_1348_p1));
    tmp26_fu_1362_p2 <= std_logic_vector(signed(p_Val2_3_0_2_cast_cast_fu_1300_p1) + signed(tmp_147_2_2_cast_cast_fu_1352_p1));
    tmp27_fu_1372_p2 <= std_logic_vector(signed(tmp132_cast_fu_1368_p1) + signed(tmp_147_1_cast_37_fu_1334_p1));
    tmp_10_fu_437_p2 <= std_logic_vector(shift_left(unsigned(p_src_rows_V_read),to_integer(unsigned('0' & ap_const_lv12_1(12-1 downto 0)))));
    tmp_11_fu_453_p1 <= p_src_rows_V_read(1 - 1 downto 0);
    tmp_12_fu_504_p4 <= ImagLoc_y_fu_492_p2(11 downto 1);
    tmp_13_fu_1042_p1 <= std_logic_vector(resize(unsigned(x_fu_1034_p1),64));
    tmp_147_0_2_cast_fu_1290_p1 <= std_logic_vector(resize(unsigned(src_kernel_win_0_val_2_1_fu_150),9));
    tmp_147_1_cast_37_fu_1334_p1 <= std_logic_vector(resize(unsigned(p_Val2_114_2_fu_1326_p3),11));
        tmp_147_1_cast_fu_1322_p1 <= std_logic_vector(resize(signed(p_Val2_s_fu_1316_p2),11));

    tmp_147_2_2_cast_cast_fu_1352_p1 <= std_logic_vector(resize(unsigned(src_kernel_win_0_val_0_1_fu_138),10));
        tmp_147_2_cast_fu_1348_p1 <= std_logic_vector(resize(signed(p_Val2_2_fu_1342_p2),11));

    tmp_14_fu_520_p2 <= "1" when (signed(ImagLoc_y_fu_492_p2) < signed(ref_cast_reg_1598)) else "0";
    tmp_16_fu_551_p1 <= ImagLoc_y_fu_492_p2(11 - 1 downto 0);
    tmp_17_cast_fu_385_p1 <= std_logic_vector(resize(unsigned(tmp_4_fu_379_p2),12));
    tmp_17_fu_978_p2 <= "0" when (p_025_0_i_reg_295 = ap_const_lv11_0) else "1";
    tmp_18_cast_fu_471_p1 <= std_logic_vector(resize(unsigned(p_012_0_i_reg_284),12));
    tmp_18_fu_984_p2 <= "1" when (signed(ImagLoc_x_fu_898_p2) < signed(p_src_cols_V_read)) else "0";
    tmp_19_fu_581_p1 <= p_i_fu_539_p3(2 - 1 downto 0);
    tmp_1_fu_359_p1 <= p_src_rows_V_read(11 - 1 downto 0);
    tmp_20_fu_995_p2 <= "1" when (signed(ImagLoc_x_fu_898_p2) < signed(tmp_17_cast_reg_1582)) else "0";
    tmp_21_cast_fu_862_p1 <= std_logic_vector(resize(unsigned(p_025_0_i_reg_295),12));
    tmp_21_fu_585_p1 <= ImagLoc_y_fu_492_p2(2 - 1 downto 0);
    tmp_22_fu_589_p1 <= ImagLoc_y_fu_492_p2(2 - 1 downto 0);
    tmp_23_fu_593_p1 <= p_assign_2_fu_564_p2(2 - 1 downto 0);
    tmp_24_fu_597_p3 <= 
        tmp_22_fu_589_p1 when (tmp_i1_fu_546_p2(0) = '1') else 
        tmp_23_fu_593_p1;
    tmp_25_fu_605_p3 <= 
        tmp_21_fu_585_p1 when (sel_tmp7_i1_fu_575_p2(0) = '1') else 
        tmp_24_fu_597_p3;
    tmp_26_fu_817_p2 <= std_logic_vector(unsigned(tmp_19_reg_1651) - unsigned(tmp_25_reg_1657));
    tmp_27_fu_619_p3 <= y_1_fu_613_p2(11 downto 11);
    tmp_28_fu_1396_p4 <= p_Val2_1_fu_1378_p2(10 downto 8);
    tmp_29_fu_644_p1 <= y_1_fu_613_p2(2 - 1 downto 0);
    tmp_2_fu_363_p1 <= p_src_cols_V_read(11 - 1 downto 0);
    tmp_30_fu_648_p3 <= y_1_fu_613_p2(11 downto 11);
    tmp_31_fu_670_p1 <= p_p2_i1_fu_662_p3(2 - 1 downto 0);
    tmp_32_fu_710_p1 <= p_i_fu_539_p3(2 - 1 downto 0);
    tmp_33_fu_720_p3 <= y_1_1_fu_714_p2(11 downto 11);
    tmp_34_fu_745_p1 <= y_1_1_fu_714_p2(2 - 1 downto 0);
    tmp_35_fu_749_p3 <= y_1_1_fu_714_p2(11 downto 11);
    tmp_36_fu_771_p1 <= p_p2_i2_fu_763_p3(2 - 1 downto 0);
    tmp_37_fu_877_p4 <= p_025_0_i_reg_295(10 downto 1);
    tmp_38_fu_904_p1 <= ImagLoc_x_fu_898_p2(2 - 1 downto 0);
    tmp_39_fu_908_p3 <= ImagLoc_x_fu_898_p2(11 downto 11);
    tmp_3_fu_389_p1 <= p_src_cols_V_read(2 - 1 downto 0);
    tmp_3_i1_fu_559_p2 <= "1" when (unsigned(tmp_16_fu_551_p1) < unsigned(tmp_1_reg_1567)) else "0";
    tmp_3_i2_fu_674_p2 <= "1" when (unsigned(p_p2_i1_fu_662_p3) < unsigned(len_cast4_i30_cast_reg_1614)) else "0";
    tmp_3_i3_fu_775_p2 <= "1" when (unsigned(p_p2_i2_fu_763_p3) < unsigned(len_cast4_i30_cast_reg_1614)) else "0";
    tmp_3_i_fu_955_p2 <= "1" when (unsigned(p_p2_i_fu_947_p3) < unsigned(len_cast4_i_cast_reg_1603)) else "0";
    tmp_40_fu_933_p3 <= ImagLoc_x_fu_898_p2(11 downto 11);
    tmp_41_fu_1038_p1 <= p_assign_2_i_fu_1027_p3(2 - 1 downto 0);
    tmp_4_cast_i46_cast_fu_443_p1 <= std_logic_vector(resize(unsigned(tmp_10_fu_437_p2),13));
    tmp_4_cast_i_cast_fu_419_p1 <= std_logic_vector(resize(unsigned(tmp_5_fu_413_p2),13));
    tmp_4_fu_379_p2 <= std_logic_vector(unsigned(tmp_2_fu_363_p1) + unsigned(ap_const_lv11_7FD));
    tmp_4_i2_fu_457_p3 <= (tmp_11_fu_453_p1 & ap_const_lv1_0);
        tmp_5_cast_i_fu_429_p1 <= std_logic_vector(resize(signed(tmp_5_i_fu_423_p2),15));

    tmp_5_fu_413_p2 <= std_logic_vector(shift_left(unsigned(p_src_cols_V_read),to_integer(unsigned('0' & ap_const_lv12_1(12-1 downto 0)))));
    tmp_5_i1_fu_447_p2 <= std_logic_vector(unsigned(tmp_4_cast_i46_cast_fu_443_p1) + unsigned(ap_const_lv13_2));
    tmp_5_i2_fu_465_p2 <= (tmp_4_i2_fu_457_p3 xor ap_const_lv2_2);
    tmp_5_i_fu_423_p2 <= std_logic_vector(unsigned(tmp_4_cast_i_cast_fu_419_p1) + unsigned(ap_const_lv13_1FFE));
    tmp_6_fu_475_p2 <= "1" when (unsigned(p_012_0_i_reg_284) < unsigned(heightloop_reg_1572)) else "0";
    tmp_7_fu_486_p2 <= "1" when (unsigned(p_012_0_i_reg_284) > unsigned(ap_const_lv11_4)) else "0";
    tmp_8_fu_866_p2 <= "1" when (unsigned(p_025_0_i_reg_295) < unsigned(widthloop_reg_1577)) else "0";
    tmp_i1_fu_546_p2 <= "1" when (signed(ImagLoc_y_fu_492_p2) < signed(len_cast4_i30_cast_reg_1614)) else "0";
    tmp_i2_fu_633_p2 <= "1" when (signed(y_1_fu_613_p2) < signed(len_cast4_i30_cast_reg_1614)) else "0";
    tmp_i2_not_fu_692_p2 <= (tmp_i2_fu_633_p2 xor ap_const_lv1_1);
    tmp_i3_fu_734_p2 <= "1" when (signed(y_1_1_fu_714_p2) < signed(len_cast4_i30_cast_reg_1614)) else "0";
    tmp_i3_not_fu_785_p2 <= (tmp_i3_fu_734_p2 xor ap_const_lv1_1);
    tmp_i_fu_922_p2 <= "1" when (signed(ImagLoc_x_fu_898_p2) < signed(len_cast4_i_cast_reg_1603)) else "0";
    tmp_i_i_38_fu_1442_p2 <= (isneg_reg_1822 or overflow_fu_1429_p2);
    tmp_i_i_fu_1424_p2 <= (isneg_reg_1822 xor ap_const_lv1_1);
    tmp_i_not_fu_960_p2 <= (tmp_i_fu_922_p2 xor ap_const_lv1_1);
    tmp_s_fu_498_p2 <= "1" when (signed(ImagLoc_y_fu_492_p2) < signed(ap_const_lv12_FFF)) else "0";
    widthloop_fu_373_p2 <= std_logic_vector(unsigned(tmp_2_fu_363_p1) + unsigned(ap_const_lv11_2));
        x_fu_1034_p1 <= std_logic_vector(resize(signed(p_assign_2_i_fu_1027_p3),32));

    y_1_1_fu_714_p2 <= std_logic_vector(unsigned(tmp_18_cast_fu_471_p1) + unsigned(ap_const_lv12_FFA));
    y_1_fu_613_p2 <= std_logic_vector(unsigned(tmp_18_cast_fu_471_p1) + unsigned(ap_const_lv12_FFB));
end behav;
