-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2014.4
-- Copyright (C) 2014 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity image_filter_borderInterpolate is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    p : IN STD_LOGIC_VECTOR (11 downto 0);
    len : IN STD_LOGIC_VECTOR (10 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (12 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of image_filter_borderInterpolate is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv13_1FFE : STD_LOGIC_VECTOR (12 downto 0) := "1111111111110";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal p_p2_fu_91_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_p2_reg_198 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_3_fu_103_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_203 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_145_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_reg_208 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_demorgan_fu_151_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_demorgan_reg_213 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel9_fu_157_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal newSel9_reg_218 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_fu_37_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal len_cast4_cast_fu_51_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_s_fu_55_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev_fu_45_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_80_fu_77_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_assign_fu_85_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_4_fu_109_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_4_cast_cast_fu_117_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_5_fu_121_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_p2_cast_cast_fu_99_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_not_fu_133_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_71_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_fu_139_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_82_fu_61_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_cast_cast_fu_67_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_assign_1_fu_127_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sel_tmp6_fu_165_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_170_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel_fu_175_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal or_cond_fu_186_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel_cast_fu_182_p1 : STD_LOGIC_VECTOR (12 downto 0);


begin




    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                newSel9_reg_218 <= newSel9_fu_157_p3;
                p_p2_reg_198 <= p_p2_fu_91_p3;
                sel_tmp2_reg_208 <= sel_tmp2_fu_145_p2;
                sel_tmp6_demorgan_reg_213 <= sel_tmp6_demorgan_fu_151_p2;
                tmp_3_reg_203 <= tmp_3_fu_103_p2;
            end if;
        end if;
    end process;
    ap_return <= 
        newSel_cast_fu_182_p1 when (or_cond_fu_186_p2(0) = '1') else 
        newSel9_reg_218;
    len_cast4_cast_fu_51_p1 <= std_logic_vector(resize(unsigned(len),12));
    newSel9_fu_157_p3 <= 
        p_cast_cast_fu_67_p1 when (or_cond_82_fu_61_p2(0) = '1') else 
        p_assign_1_fu_127_p2;
    newSel_cast_fu_182_p1 <= std_logic_vector(resize(unsigned(newSel_fu_175_p3),13));
    newSel_fu_175_p3 <= 
        p_p2_reg_198 when (sel_tmp7_fu_170_p2(0) = '1') else 
        ap_const_lv12_0;
    or_cond_82_fu_61_p2 <= (tmp_s_fu_55_p2 and rev_fu_45_p2);
    or_cond_fu_186_p2 <= (sel_tmp7_fu_170_p2 or sel_tmp2_reg_208);
    p_assign_1_fu_127_p2 <= std_logic_vector(unsigned(tmp_5_fu_121_p2) - unsigned(p_p2_cast_cast_fu_99_p1));
    p_assign_fu_85_p2 <= std_logic_vector(unsigned(ap_const_lv12_0) - unsigned(p));
        p_cast_cast_fu_67_p1 <= std_logic_vector(resize(signed(p),13));

    p_p2_cast_cast_fu_99_p1 <= std_logic_vector(resize(unsigned(p_p2_fu_91_p3),13));
    p_p2_fu_91_p3 <= 
        p_assign_fu_85_p2 when (tmp_80_fu_77_p3(0) = '1') else 
        p;
    rev_fu_45_p2 <= (tmp_fu_37_p3 xor ap_const_lv1_1);
    sel_tmp1_fu_139_p2 <= (tmp_fu_37_p3 or tmp_not_fu_133_p2);
    sel_tmp2_fu_145_p2 <= (tmp_1_fu_71_p2 and sel_tmp1_fu_139_p2);
    sel_tmp6_demorgan_fu_151_p2 <= (or_cond_82_fu_61_p2 or tmp_1_fu_71_p2);
    sel_tmp6_fu_165_p2 <= (sel_tmp6_demorgan_reg_213 xor ap_const_lv1_1);
    sel_tmp7_fu_170_p2 <= (tmp_3_reg_203 and sel_tmp6_fu_165_p2);
    tmp_1_fu_71_p2 <= "1" when (len = ap_const_lv11_1) else "0";
    tmp_3_fu_103_p2 <= "1" when (unsigned(p_p2_fu_91_p3) < unsigned(len_cast4_cast_fu_51_p1)) else "0";
    tmp_4_cast_cast_fu_117_p1 <= std_logic_vector(resize(unsigned(tmp_4_fu_109_p3),13));
    tmp_4_fu_109_p3 <= (len & ap_const_lv1_0);
    tmp_5_fu_121_p2 <= std_logic_vector(unsigned(tmp_4_cast_cast_fu_117_p1) + unsigned(ap_const_lv13_1FFE));
    tmp_80_fu_77_p3 <= p(11 downto 11);
    tmp_fu_37_p3 <= p(11 downto 11);
    tmp_not_fu_133_p2 <= (tmp_s_fu_55_p2 xor ap_const_lv1_1);
    tmp_s_fu_55_p2 <= "1" when (signed(len_cast4_cast_fu_51_p1) > signed(p)) else "0";
end behav;
