// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================


#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#define AP_INT_MAX_W 32678

#include "ap_int.h"

#include "hls_stream.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;

template< int D ,int U ,int TI ,int TD > struct ap_axiu ;
template<> struct  ap_axiu<32, 1, 1, 1> {
ap_uint<32> data;
ap_uint<4> keep;
ap_uint<4> strb;
ap_uint<1> user;
ap_uint<1> last;
ap_uint<1> id;
ap_uint<1> dest;
}; 



   #define AUTOTB_TVIN_INPUT_STREAM_V_data_V  "../tv/cdatafile/c.image_filter.autotvin_INPUT_STREAM_V_data_V.dat"
   #define WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_data_V  "../tv/stream_size/stream_size_in_INPUT_STREAM_V_data_V.dat"
   #define AUTOTB_TVIN_INPUT_STREAM_V_keep_V  "../tv/cdatafile/c.image_filter.autotvin_INPUT_STREAM_V_keep_V.dat"
   #define WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_keep_V  "../tv/stream_size/stream_size_in_INPUT_STREAM_V_keep_V.dat"
   #define AUTOTB_TVIN_INPUT_STREAM_V_strb_V  "../tv/cdatafile/c.image_filter.autotvin_INPUT_STREAM_V_strb_V.dat"
   #define WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_strb_V  "../tv/stream_size/stream_size_in_INPUT_STREAM_V_strb_V.dat"
   #define AUTOTB_TVIN_INPUT_STREAM_V_user_V  "../tv/cdatafile/c.image_filter.autotvin_INPUT_STREAM_V_user_V.dat"
   #define WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_user_V  "../tv/stream_size/stream_size_in_INPUT_STREAM_V_user_V.dat"
   #define AUTOTB_TVIN_INPUT_STREAM_V_last_V  "../tv/cdatafile/c.image_filter.autotvin_INPUT_STREAM_V_last_V.dat"
   #define WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_last_V  "../tv/stream_size/stream_size_in_INPUT_STREAM_V_last_V.dat"
   #define AUTOTB_TVIN_INPUT_STREAM_V_id_V  "../tv/cdatafile/c.image_filter.autotvin_INPUT_STREAM_V_id_V.dat"
   #define WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_id_V  "../tv/stream_size/stream_size_in_INPUT_STREAM_V_id_V.dat"
   #define AUTOTB_TVIN_INPUT_STREAM_V_dest_V  "../tv/cdatafile/c.image_filter.autotvin_INPUT_STREAM_V_dest_V.dat"
   #define WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_dest_V  "../tv/stream_size/stream_size_in_INPUT_STREAM_V_dest_V.dat"
   #define AUTOTB_TVOUT_OUTPUT_STREAM_V_data_V  "../tv/cdatafile/c.image_filter.autotvout_OUTPUT_STREAM_V_data_V.dat"
   #define AUTOTB_TVIN_OUTPUT_STREAM_V_data_V  "../tv/cdatafile/c.image_filter.autotvin_OUTPUT_STREAM_V_data_V.dat"
   #define WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_data_V  "../tv/stream_size/stream_size_out_OUTPUT_STREAM_V_data_V.dat"
   #define AUTOTB_TVOUT_OUTPUT_STREAM_V_keep_V  "../tv/cdatafile/c.image_filter.autotvout_OUTPUT_STREAM_V_keep_V.dat"
   #define AUTOTB_TVIN_OUTPUT_STREAM_V_keep_V  "../tv/cdatafile/c.image_filter.autotvin_OUTPUT_STREAM_V_keep_V.dat"
   #define WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_keep_V  "../tv/stream_size/stream_size_out_OUTPUT_STREAM_V_keep_V.dat"
   #define AUTOTB_TVOUT_OUTPUT_STREAM_V_strb_V  "../tv/cdatafile/c.image_filter.autotvout_OUTPUT_STREAM_V_strb_V.dat"
   #define AUTOTB_TVIN_OUTPUT_STREAM_V_strb_V  "../tv/cdatafile/c.image_filter.autotvin_OUTPUT_STREAM_V_strb_V.dat"
   #define WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_strb_V  "../tv/stream_size/stream_size_out_OUTPUT_STREAM_V_strb_V.dat"
   #define AUTOTB_TVOUT_OUTPUT_STREAM_V_user_V  "../tv/cdatafile/c.image_filter.autotvout_OUTPUT_STREAM_V_user_V.dat"
   #define AUTOTB_TVIN_OUTPUT_STREAM_V_user_V  "../tv/cdatafile/c.image_filter.autotvin_OUTPUT_STREAM_V_user_V.dat"
   #define WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_user_V  "../tv/stream_size/stream_size_out_OUTPUT_STREAM_V_user_V.dat"
   #define AUTOTB_TVOUT_OUTPUT_STREAM_V_last_V  "../tv/cdatafile/c.image_filter.autotvout_OUTPUT_STREAM_V_last_V.dat"
   #define AUTOTB_TVIN_OUTPUT_STREAM_V_last_V  "../tv/cdatafile/c.image_filter.autotvin_OUTPUT_STREAM_V_last_V.dat"
   #define WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_last_V  "../tv/stream_size/stream_size_out_OUTPUT_STREAM_V_last_V.dat"
   #define AUTOTB_TVOUT_OUTPUT_STREAM_V_id_V  "../tv/cdatafile/c.image_filter.autotvout_OUTPUT_STREAM_V_id_V.dat"
   #define AUTOTB_TVIN_OUTPUT_STREAM_V_id_V  "../tv/cdatafile/c.image_filter.autotvin_OUTPUT_STREAM_V_id_V.dat"
   #define WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_id_V  "../tv/stream_size/stream_size_out_OUTPUT_STREAM_V_id_V.dat"
   #define AUTOTB_TVOUT_OUTPUT_STREAM_V_dest_V  "../tv/cdatafile/c.image_filter.autotvout_OUTPUT_STREAM_V_dest_V.dat"
   #define AUTOTB_TVIN_OUTPUT_STREAM_V_dest_V  "../tv/cdatafile/c.image_filter.autotvin_OUTPUT_STREAM_V_dest_V.dat"
   #define WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_dest_V  "../tv/stream_size/stream_size_out_OUTPUT_STREAM_V_dest_V.dat"
   #define AUTOTB_TVIN_rows  "../tv/cdatafile/c.image_filter.autotvin_rows.dat"
   #define AUTOTB_TVIN_cols  "../tv/cdatafile/c.image_filter.autotvin_cols.dat"
   #define INTER_TCL  "../tv/cdatafile/ref.tcl"

   #define AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_data_V  "../tv/rtldatafile/rtl.image_filter.autotvout_OUTPUT_STREAM_V_data_V.dat"
   #define AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_keep_V  "../tv/rtldatafile/rtl.image_filter.autotvout_OUTPUT_STREAM_V_keep_V.dat"
   #define AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_strb_V  "../tv/rtldatafile/rtl.image_filter.autotvout_OUTPUT_STREAM_V_strb_V.dat"
   #define AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_user_V  "../tv/rtldatafile/rtl.image_filter.autotvout_OUTPUT_STREAM_V_user_V.dat"
   #define AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_last_V  "../tv/rtldatafile/rtl.image_filter.autotvout_OUTPUT_STREAM_V_last_V.dat"
   #define AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_id_V  "../tv/rtldatafile/rtl.image_filter.autotvout_OUTPUT_STREAM_V_id_V.dat"
   #define AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_dest_V  "../tv/rtldatafile/rtl.image_filter.autotvout_OUTPUT_STREAM_V_dest_V.dat"

class INTER_TCL_FILE {
    public:
//functions
        INTER_TCL_FILE(const char* name) {
            mName = name;
            INPUT_STREAM_V_data_V_depth = 0;
            INPUT_STREAM_V_keep_V_depth = 0;
            INPUT_STREAM_V_strb_V_depth = 0;
            INPUT_STREAM_V_user_V_depth = 0;
            INPUT_STREAM_V_last_V_depth = 0;
            INPUT_STREAM_V_id_V_depth = 0;
            INPUT_STREAM_V_dest_V_depth = 0;
            OUTPUT_STREAM_V_data_V_depth = 0;
            OUTPUT_STREAM_V_keep_V_depth = 0;
            OUTPUT_STREAM_V_strb_V_depth = 0;
            OUTPUT_STREAM_V_user_V_depth = 0;
            OUTPUT_STREAM_V_last_V_depth = 0;
            OUTPUT_STREAM_V_id_V_depth = 0;
            OUTPUT_STREAM_V_dest_V_depth = 0;
            rows_depth = 0;
            cols_depth = 0;
            trans_num =0;
        }
        ~INTER_TCL_FILE() {
            mFile.open(mName);
            if (!mFile.good() ) {
                cout<<"Failed to open file ref.tcl."<<endl;
                exit (1);
            }
            string total_list = get_depth_list();
            mFile<<"set depth_list {\n";
            mFile<<total_list; 
            mFile<<"}\n";
            mFile<<"set trans_num "<<trans_num<<endl;
            mFile.close();
        }
        string get_depth_list () {
            stringstream total_list;
            total_list<<"   {INPUT_STREAM_V_data_V "<< INPUT_STREAM_V_data_V_depth << "}\n";
            total_list<<"   {INPUT_STREAM_V_keep_V "<< INPUT_STREAM_V_keep_V_depth << "}\n";
            total_list<<"   {INPUT_STREAM_V_strb_V "<< INPUT_STREAM_V_strb_V_depth << "}\n";
            total_list<<"   {INPUT_STREAM_V_user_V "<< INPUT_STREAM_V_user_V_depth << "}\n";
            total_list<<"   {INPUT_STREAM_V_last_V "<< INPUT_STREAM_V_last_V_depth << "}\n";
            total_list<<"   {INPUT_STREAM_V_id_V "<< INPUT_STREAM_V_id_V_depth << "}\n";
            total_list<<"   {INPUT_STREAM_V_dest_V "<< INPUT_STREAM_V_dest_V_depth << "}\n";
            total_list<<"   {OUTPUT_STREAM_V_data_V "<< OUTPUT_STREAM_V_data_V_depth << "}\n";
            total_list<<"   {OUTPUT_STREAM_V_keep_V "<< OUTPUT_STREAM_V_keep_V_depth << "}\n";
            total_list<<"   {OUTPUT_STREAM_V_strb_V "<< OUTPUT_STREAM_V_strb_V_depth << "}\n";
            total_list<<"   {OUTPUT_STREAM_V_user_V "<< OUTPUT_STREAM_V_user_V_depth << "}\n";
            total_list<<"   {OUTPUT_STREAM_V_last_V "<< OUTPUT_STREAM_V_last_V_depth << "}\n";
            total_list<<"   {OUTPUT_STREAM_V_id_V "<< OUTPUT_STREAM_V_id_V_depth << "}\n";
            total_list<<"   {OUTPUT_STREAM_V_dest_V "<< OUTPUT_STREAM_V_dest_V_depth << "}\n";
            total_list<<"   {rows "<< rows_depth << "}\n";
            total_list<<"   {cols "<< cols_depth << "}\n";
            return total_list.str();
        }
        void set_num (int num , int* class_num) {
            (*class_num) = (*class_num) > num ? (*class_num) : num;
        }
    public:
//variables
        int INPUT_STREAM_V_data_V_depth;
        int INPUT_STREAM_V_keep_V_depth;
        int INPUT_STREAM_V_strb_V_depth;
        int INPUT_STREAM_V_user_V_depth;
        int INPUT_STREAM_V_last_V_depth;
        int INPUT_STREAM_V_id_V_depth;
        int INPUT_STREAM_V_dest_V_depth;
        int OUTPUT_STREAM_V_data_V_depth;
        int OUTPUT_STREAM_V_keep_V_depth;
        int OUTPUT_STREAM_V_strb_V_depth;
        int OUTPUT_STREAM_V_user_V_depth;
        int OUTPUT_STREAM_V_last_V_depth;
        int OUTPUT_STREAM_V_id_V_depth;
        int OUTPUT_STREAM_V_dest_V_depth;
        int rows_depth;
        int cols_depth;
        int trans_num;
    private:
        ofstream mFile;
        const char* mName;
};

#define image_filter AESL_ORIG_DUT_image_filter
extern void image_filter ( hls::stream< ap_axiu< 32 ,1 ,1 ,1 > > & INPUT_STREAM,  hls::stream< ap_axiu< 32 ,1 ,1 ,1 > > & OUTPUT_STREAM,  int rows,  int cols);
#undef image_filter
void image_filter ( hls::stream< ap_axiu< 32 ,1 ,1 ,1 > > & INPUT_STREAM,  hls::stream< ap_axiu< 32 ,1 ,1 ,1 > > & OUTPUT_STREAM,  int rows,  int cols) {

    fstream wrapc_switch_file_token;

    wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");

    int AESL_i;

    if (wrapc_switch_file_token.good()) {

        static unsigned AESL_transaction_pc;

        string AESL_token;

        string AESL_num;

        static AESL_FILE_HANDLER aesl_fh;

        aesl_fh.read(WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_data_V, AESL_token); //[[transaction]]

        aesl_fh.read(WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_data_V, AESL_num); //transaction number

        if (atoi(AESL_num.c_str()) == AESL_transaction_pc ) {

            aesl_fh.read(WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_data_V, AESL_token); //pop_size

            int aesl_tmp_1 = atoi(AESL_token.c_str());

            for (int i = 0 ; i < aesl_tmp_1  ; i++) {

                INPUT_STREAM.read();

            }

            aesl_fh.read(WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_data_V, AESL_token); //[[/transaction]]

        }

        int aesl_tmp_4;

        int aesl_tmp_5 = 0;

        aesl_fh.read(WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_data_V, AESL_token); //[[transaction]]

        aesl_fh.read(WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_data_V, AESL_num); //transaction number

        if (atoi(AESL_num.c_str()) == AESL_transaction_pc ) {

            aesl_fh.read(WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_data_V, AESL_token); //pop_size

            aesl_tmp_4 = atoi(AESL_token.c_str());

            aesl_fh.read(WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_data_V, AESL_token); //[[/transaction]]

        }

        std::vector<ap_axiu< 32 ,1 ,1 ,1 > > aesl_tmp_3;

        aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_data_V, AESL_token); //[[transaction]]

        if ( AESL_token != "[[transaction]]") {

           exit(1);

        }

        aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_data_V, AESL_num); //transaction number

        if (atoi(AESL_num.c_str()) == AESL_transaction_pc ) {

            aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_data_V, AESL_token); //data

            std::vector < sc_bv<32> > OUTPUT_STREAM_V_data_V_pc_buffer;

            int i = 0;

            while (AESL_token != "[[/transaction]]") {

                bool no_x = false;

                bool err = false;

                while (!no_x) {

                size_t x_found = AESL_token.find('X');

                if (x_found != string::npos) {

                    if (!err) {

                        cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'OUTPUT_STREAM_V_data_V', possible cause: There are uninitialized variables in the C design." << endl; 

                        err = true;

                    }

                    AESL_token.replace(x_found, 1, "0");

                } else {

                    no_x = true;

                }

                }

                no_x = false;

                while (!no_x) {

                size_t x_found = AESL_token.find('x', 2);

                if (x_found != string::npos) {

                    if (!err) {

                        cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'OUTPUT_STREAM_V_data_V', possible cause: There are uninitialized variables in the C design." << endl; 

                        err = true;

                    }

                    AESL_token.replace(x_found, 1, "0");

                } else {

                    no_x = true;

                }

                }

                if (AESL_token != "") {

                    OUTPUT_STREAM_V_data_V_pc_buffer.push_back( AESL_token.c_str() );

                    i++;

                }

                aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_data_V, AESL_token); //data or [[/transaction]]

                if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_data_V)) {

                   exit(1);

                }

            }

            if (i != aesl_tmp_4) {

               aesl_tmp_4 = i;

            }

            if (aesl_tmp_4 > 0 && aesl_tmp_3.size() < aesl_tmp_4) {

                int aesl_tmp_3_size = aesl_tmp_3.size();

                for (int tmp_aesl_tmp_3 = 0 ; tmp_aesl_tmp_3 < aesl_tmp_4 - aesl_tmp_3_size ; tmp_aesl_tmp_3 ++ ) {

                    ap_axiu< 32 ,1 ,1 ,1 > tmp;

                    aesl_tmp_3.push_back(tmp);

                }

            }

            if (i > 0) {

                sc_lv<32> *OUTPUT_STREAM_V_data_V_lv0_0_0_1_lv1_0_0_1 = new sc_lv<32>[aesl_tmp_4 - aesl_tmp_5];

                AESL_i = 0; //subscript for rtl array

                for (int i_0 = 0; i_0 <= aesl_tmp_4 - aesl_tmp_5 - 1 ; i_0+= 1) {

                    for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

                        if(&(aesl_tmp_3[0].data) != 0) {

                           OUTPUT_STREAM_V_data_V_lv0_0_0_1_lv1_0_0_1[0 + AESL_i].range(31, 0) = sc_bv<32>(OUTPUT_STREAM_V_data_V_pc_buffer[0 + AESL_i].range(31, 0));

                        }

                        AESL_i++;

                    }

                }

                AESL_i = 0; //subscript for rtl array

                for (int i_0 = 0; i_0 <= aesl_tmp_4 - aesl_tmp_5 - 1 ; i_0+= 1) {

                    for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

                        if(&(aesl_tmp_3[0].data) != 0) {

                           aesl_tmp_3[i_0].data = (OUTPUT_STREAM_V_data_V_lv0_0_0_1_lv1_0_0_1[0 + AESL_i]).to_string(SC_BIN).c_str();

                        }

                        AESL_i++;

                    }

                }

                }

        }

        aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_keep_V, AESL_token); //[[transaction]]

        if ( AESL_token != "[[transaction]]") {

           exit(1);

        }

        aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_keep_V, AESL_num); //transaction number

        if (atoi(AESL_num.c_str()) == AESL_transaction_pc ) {

            aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_keep_V, AESL_token); //data

            std::vector < sc_bv<4> > OUTPUT_STREAM_V_keep_V_pc_buffer;

            int i = 0;

            while (AESL_token != "[[/transaction]]") {

                bool no_x = false;

                bool err = false;

                while (!no_x) {

                size_t x_found = AESL_token.find('X');

                if (x_found != string::npos) {

                    if (!err) {

                        cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'OUTPUT_STREAM_V_keep_V', possible cause: There are uninitialized variables in the C design." << endl; 

                        err = true;

                    }

                    AESL_token.replace(x_found, 1, "0");

                } else {

                    no_x = true;

                }

                }

                no_x = false;

                while (!no_x) {

                size_t x_found = AESL_token.find('x', 2);

                if (x_found != string::npos) {

                    if (!err) {

                        cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'OUTPUT_STREAM_V_keep_V', possible cause: There are uninitialized variables in the C design." << endl; 

                        err = true;

                    }

                    AESL_token.replace(x_found, 1, "0");

                } else {

                    no_x = true;

                }

                }

                if (AESL_token != "") {

                    OUTPUT_STREAM_V_keep_V_pc_buffer.push_back( AESL_token.c_str() );

                    i++;

                }

                aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_keep_V, AESL_token); //data or [[/transaction]]

                if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_keep_V)) {

                   exit(1);

                }

            }

            if (i != aesl_tmp_4) {

               aesl_tmp_4 = i;

            }

            if (aesl_tmp_4 > 0 && aesl_tmp_3.size() < aesl_tmp_4) {

                int aesl_tmp_3_size = aesl_tmp_3.size();

                for (int tmp_aesl_tmp_3 = 0 ; tmp_aesl_tmp_3 < aesl_tmp_4 - aesl_tmp_3_size ; tmp_aesl_tmp_3 ++ ) {

                    ap_axiu< 32 ,1 ,1 ,1 > tmp;

                    aesl_tmp_3.push_back(tmp);

                }

            }

            if (i > 0) {

                sc_lv<4> *OUTPUT_STREAM_V_keep_V_lv0_0_0_1_lv1_0_0_1 = new sc_lv<4>[aesl_tmp_4 - aesl_tmp_5];

                AESL_i = 0; //subscript for rtl array

                for (int i_0 = 0; i_0 <= aesl_tmp_4 - aesl_tmp_5 - 1 ; i_0+= 1) {

                    for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

                        if(&(aesl_tmp_3[0].keep) != 0) {

                           OUTPUT_STREAM_V_keep_V_lv0_0_0_1_lv1_0_0_1[0 + AESL_i].range(3, 0) = sc_bv<4>(OUTPUT_STREAM_V_keep_V_pc_buffer[0 + AESL_i].range(3, 0));

                        }

                        AESL_i++;

                    }

                }

                AESL_i = 0; //subscript for rtl array

                for (int i_0 = 0; i_0 <= aesl_tmp_4 - aesl_tmp_5 - 1 ; i_0+= 1) {

                    for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

                        if(&(aesl_tmp_3[0].keep) != 0) {

                           aesl_tmp_3[i_0].keep = (OUTPUT_STREAM_V_keep_V_lv0_0_0_1_lv1_0_0_1[0 + AESL_i]).to_string(SC_BIN).c_str();

                        }

                        AESL_i++;

                    }

                }

                }

        }

        aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_strb_V, AESL_token); //[[transaction]]

        if ( AESL_token != "[[transaction]]") {

           exit(1);

        }

        aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_strb_V, AESL_num); //transaction number

        if (atoi(AESL_num.c_str()) == AESL_transaction_pc ) {

            aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_strb_V, AESL_token); //data

            std::vector < sc_bv<4> > OUTPUT_STREAM_V_strb_V_pc_buffer;

            int i = 0;

            while (AESL_token != "[[/transaction]]") {

                bool no_x = false;

                bool err = false;

                while (!no_x) {

                size_t x_found = AESL_token.find('X');

                if (x_found != string::npos) {

                    if (!err) {

                        cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'OUTPUT_STREAM_V_strb_V', possible cause: There are uninitialized variables in the C design." << endl; 

                        err = true;

                    }

                    AESL_token.replace(x_found, 1, "0");

                } else {

                    no_x = true;

                }

                }

                no_x = false;

                while (!no_x) {

                size_t x_found = AESL_token.find('x', 2);

                if (x_found != string::npos) {

                    if (!err) {

                        cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'OUTPUT_STREAM_V_strb_V', possible cause: There are uninitialized variables in the C design." << endl; 

                        err = true;

                    }

                    AESL_token.replace(x_found, 1, "0");

                } else {

                    no_x = true;

                }

                }

                if (AESL_token != "") {

                    OUTPUT_STREAM_V_strb_V_pc_buffer.push_back( AESL_token.c_str() );

                    i++;

                }

                aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_strb_V, AESL_token); //data or [[/transaction]]

                if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_strb_V)) {

                   exit(1);

                }

            }

            if (i != aesl_tmp_4) {

               aesl_tmp_4 = i;

            }

            if (aesl_tmp_4 > 0 && aesl_tmp_3.size() < aesl_tmp_4) {

                int aesl_tmp_3_size = aesl_tmp_3.size();

                for (int tmp_aesl_tmp_3 = 0 ; tmp_aesl_tmp_3 < aesl_tmp_4 - aesl_tmp_3_size ; tmp_aesl_tmp_3 ++ ) {

                    ap_axiu< 32 ,1 ,1 ,1 > tmp;

                    aesl_tmp_3.push_back(tmp);

                }

            }

            if (i > 0) {

                sc_lv<4> *OUTPUT_STREAM_V_strb_V_lv0_0_0_1_lv1_0_0_1 = new sc_lv<4>[aesl_tmp_4 - aesl_tmp_5];

                AESL_i = 0; //subscript for rtl array

                for (int i_0 = 0; i_0 <= aesl_tmp_4 - aesl_tmp_5 - 1 ; i_0+= 1) {

                    for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

                        if(&(aesl_tmp_3[0].strb) != 0) {

                           OUTPUT_STREAM_V_strb_V_lv0_0_0_1_lv1_0_0_1[0 + AESL_i].range(3, 0) = sc_bv<4>(OUTPUT_STREAM_V_strb_V_pc_buffer[0 + AESL_i].range(3, 0));

                        }

                        AESL_i++;

                    }

                }

                AESL_i = 0; //subscript for rtl array

                for (int i_0 = 0; i_0 <= aesl_tmp_4 - aesl_tmp_5 - 1 ; i_0+= 1) {

                    for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

                        if(&(aesl_tmp_3[0].strb) != 0) {

                           aesl_tmp_3[i_0].strb = (OUTPUT_STREAM_V_strb_V_lv0_0_0_1_lv1_0_0_1[0 + AESL_i]).to_string(SC_BIN).c_str();

                        }

                        AESL_i++;

                    }

                }

                }

        }

        aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_user_V, AESL_token); //[[transaction]]

        if ( AESL_token != "[[transaction]]") {

           exit(1);

        }

        aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_user_V, AESL_num); //transaction number

        if (atoi(AESL_num.c_str()) == AESL_transaction_pc ) {

            aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_user_V, AESL_token); //data

            std::vector < sc_bv<1> > OUTPUT_STREAM_V_user_V_pc_buffer;

            int i = 0;

            while (AESL_token != "[[/transaction]]") {

                bool no_x = false;

                bool err = false;

                while (!no_x) {

                size_t x_found = AESL_token.find('X');

                if (x_found != string::npos) {

                    if (!err) {

                        cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'OUTPUT_STREAM_V_user_V', possible cause: There are uninitialized variables in the C design." << endl; 

                        err = true;

                    }

                    AESL_token.replace(x_found, 1, "0");

                } else {

                    no_x = true;

                }

                }

                no_x = false;

                while (!no_x) {

                size_t x_found = AESL_token.find('x', 2);

                if (x_found != string::npos) {

                    if (!err) {

                        cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'OUTPUT_STREAM_V_user_V', possible cause: There are uninitialized variables in the C design." << endl; 

                        err = true;

                    }

                    AESL_token.replace(x_found, 1, "0");

                } else {

                    no_x = true;

                }

                }

                if (AESL_token != "") {

                    OUTPUT_STREAM_V_user_V_pc_buffer.push_back( AESL_token.c_str() );

                    i++;

                }

                aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_user_V, AESL_token); //data or [[/transaction]]

                if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_user_V)) {

                   exit(1);

                }

            }

            if (i != aesl_tmp_4) {

               aesl_tmp_4 = i;

            }

            if (aesl_tmp_4 > 0 && aesl_tmp_3.size() < aesl_tmp_4) {

                int aesl_tmp_3_size = aesl_tmp_3.size();

                for (int tmp_aesl_tmp_3 = 0 ; tmp_aesl_tmp_3 < aesl_tmp_4 - aesl_tmp_3_size ; tmp_aesl_tmp_3 ++ ) {

                    ap_axiu< 32 ,1 ,1 ,1 > tmp;

                    aesl_tmp_3.push_back(tmp);

                }

            }

            if (i > 0) {

                sc_lv<1> *OUTPUT_STREAM_V_user_V_lv0_0_0_1_lv1_0_0_1 = new sc_lv<1>[aesl_tmp_4 - aesl_tmp_5];

                AESL_i = 0; //subscript for rtl array

                for (int i_0 = 0; i_0 <= aesl_tmp_4 - aesl_tmp_5 - 1 ; i_0+= 1) {

                    for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

                        if(&(aesl_tmp_3[0].user) != 0) {

                           OUTPUT_STREAM_V_user_V_lv0_0_0_1_lv1_0_0_1[0 + AESL_i].range(0, 0) = sc_bv<1>(OUTPUT_STREAM_V_user_V_pc_buffer[0 + AESL_i].range(0, 0));

                        }

                        AESL_i++;

                    }

                }

                AESL_i = 0; //subscript for rtl array

                for (int i_0 = 0; i_0 <= aesl_tmp_4 - aesl_tmp_5 - 1 ; i_0+= 1) {

                    for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

                        if(&(aesl_tmp_3[0].user) != 0) {

                           aesl_tmp_3[i_0].user = (OUTPUT_STREAM_V_user_V_lv0_0_0_1_lv1_0_0_1[0 + AESL_i]).to_string(SC_BIN).c_str();

                        }

                        AESL_i++;

                    }

                }

                }

        }

        aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_last_V, AESL_token); //[[transaction]]

        if ( AESL_token != "[[transaction]]") {

           exit(1);

        }

        aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_last_V, AESL_num); //transaction number

        if (atoi(AESL_num.c_str()) == AESL_transaction_pc ) {

            aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_last_V, AESL_token); //data

            std::vector < sc_bv<1> > OUTPUT_STREAM_V_last_V_pc_buffer;

            int i = 0;

            while (AESL_token != "[[/transaction]]") {

                bool no_x = false;

                bool err = false;

                while (!no_x) {

                size_t x_found = AESL_token.find('X');

                if (x_found != string::npos) {

                    if (!err) {

                        cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'OUTPUT_STREAM_V_last_V', possible cause: There are uninitialized variables in the C design." << endl; 

                        err = true;

                    }

                    AESL_token.replace(x_found, 1, "0");

                } else {

                    no_x = true;

                }

                }

                no_x = false;

                while (!no_x) {

                size_t x_found = AESL_token.find('x', 2);

                if (x_found != string::npos) {

                    if (!err) {

                        cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'OUTPUT_STREAM_V_last_V', possible cause: There are uninitialized variables in the C design." << endl; 

                        err = true;

                    }

                    AESL_token.replace(x_found, 1, "0");

                } else {

                    no_x = true;

                }

                }

                if (AESL_token != "") {

                    OUTPUT_STREAM_V_last_V_pc_buffer.push_back( AESL_token.c_str() );

                    i++;

                }

                aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_last_V, AESL_token); //data or [[/transaction]]

                if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_last_V)) {

                   exit(1);

                }

            }

            if (i != aesl_tmp_4) {

               aesl_tmp_4 = i;

            }

            if (aesl_tmp_4 > 0 && aesl_tmp_3.size() < aesl_tmp_4) {

                int aesl_tmp_3_size = aesl_tmp_3.size();

                for (int tmp_aesl_tmp_3 = 0 ; tmp_aesl_tmp_3 < aesl_tmp_4 - aesl_tmp_3_size ; tmp_aesl_tmp_3 ++ ) {

                    ap_axiu< 32 ,1 ,1 ,1 > tmp;

                    aesl_tmp_3.push_back(tmp);

                }

            }

            if (i > 0) {

                sc_lv<1> *OUTPUT_STREAM_V_last_V_lv0_0_0_1_lv1_0_0_1 = new sc_lv<1>[aesl_tmp_4 - aesl_tmp_5];

                AESL_i = 0; //subscript for rtl array

                for (int i_0 = 0; i_0 <= aesl_tmp_4 - aesl_tmp_5 - 1 ; i_0+= 1) {

                    for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

                        if(&(aesl_tmp_3[0].last) != 0) {

                           OUTPUT_STREAM_V_last_V_lv0_0_0_1_lv1_0_0_1[0 + AESL_i].range(0, 0) = sc_bv<1>(OUTPUT_STREAM_V_last_V_pc_buffer[0 + AESL_i].range(0, 0));

                        }

                        AESL_i++;

                    }

                }

                AESL_i = 0; //subscript for rtl array

                for (int i_0 = 0; i_0 <= aesl_tmp_4 - aesl_tmp_5 - 1 ; i_0+= 1) {

                    for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

                        if(&(aesl_tmp_3[0].last) != 0) {

                           aesl_tmp_3[i_0].last = (OUTPUT_STREAM_V_last_V_lv0_0_0_1_lv1_0_0_1[0 + AESL_i]).to_string(SC_BIN).c_str();

                        }

                        AESL_i++;

                    }

                }

                }

        }

        aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_id_V, AESL_token); //[[transaction]]

        if ( AESL_token != "[[transaction]]") {

           exit(1);

        }

        aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_id_V, AESL_num); //transaction number

        if (atoi(AESL_num.c_str()) == AESL_transaction_pc ) {

            aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_id_V, AESL_token); //data

            std::vector < sc_bv<1> > OUTPUT_STREAM_V_id_V_pc_buffer;

            int i = 0;

            while (AESL_token != "[[/transaction]]") {

                bool no_x = false;

                bool err = false;

                while (!no_x) {

                size_t x_found = AESL_token.find('X');

                if (x_found != string::npos) {

                    if (!err) {

                        cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'OUTPUT_STREAM_V_id_V', possible cause: There are uninitialized variables in the C design." << endl; 

                        err = true;

                    }

                    AESL_token.replace(x_found, 1, "0");

                } else {

                    no_x = true;

                }

                }

                no_x = false;

                while (!no_x) {

                size_t x_found = AESL_token.find('x', 2);

                if (x_found != string::npos) {

                    if (!err) {

                        cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'OUTPUT_STREAM_V_id_V', possible cause: There are uninitialized variables in the C design." << endl; 

                        err = true;

                    }

                    AESL_token.replace(x_found, 1, "0");

                } else {

                    no_x = true;

                }

                }

                if (AESL_token != "") {

                    OUTPUT_STREAM_V_id_V_pc_buffer.push_back( AESL_token.c_str() );

                    i++;

                }

                aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_id_V, AESL_token); //data or [[/transaction]]

                if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_id_V)) {

                   exit(1);

                }

            }

            if (i != aesl_tmp_4) {

               aesl_tmp_4 = i;

            }

            if (aesl_tmp_4 > 0 && aesl_tmp_3.size() < aesl_tmp_4) {

                int aesl_tmp_3_size = aesl_tmp_3.size();

                for (int tmp_aesl_tmp_3 = 0 ; tmp_aesl_tmp_3 < aesl_tmp_4 - aesl_tmp_3_size ; tmp_aesl_tmp_3 ++ ) {

                    ap_axiu< 32 ,1 ,1 ,1 > tmp;

                    aesl_tmp_3.push_back(tmp);

                }

            }

            if (i > 0) {

                sc_lv<1> *OUTPUT_STREAM_V_id_V_lv0_0_0_1_lv1_0_0_1 = new sc_lv<1>[aesl_tmp_4 - aesl_tmp_5];

                AESL_i = 0; //subscript for rtl array

                for (int i_0 = 0; i_0 <= aesl_tmp_4 - aesl_tmp_5 - 1 ; i_0+= 1) {

                    for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

                        if(&(aesl_tmp_3[0].id) != 0) {

                           OUTPUT_STREAM_V_id_V_lv0_0_0_1_lv1_0_0_1[0 + AESL_i].range(0, 0) = sc_bv<1>(OUTPUT_STREAM_V_id_V_pc_buffer[0 + AESL_i].range(0, 0));

                        }

                        AESL_i++;

                    }

                }

                AESL_i = 0; //subscript for rtl array

                for (int i_0 = 0; i_0 <= aesl_tmp_4 - aesl_tmp_5 - 1 ; i_0+= 1) {

                    for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

                        if(&(aesl_tmp_3[0].id) != 0) {

                           aesl_tmp_3[i_0].id = (OUTPUT_STREAM_V_id_V_lv0_0_0_1_lv1_0_0_1[0 + AESL_i]).to_string(SC_BIN).c_str();

                        }

                        AESL_i++;

                    }

                }

                }

        }

        aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_dest_V, AESL_token); //[[transaction]]

        if ( AESL_token != "[[transaction]]") {

           exit(1);

        }

        aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_dest_V, AESL_num); //transaction number

        if (atoi(AESL_num.c_str()) == AESL_transaction_pc ) {

            aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_dest_V, AESL_token); //data

            std::vector < sc_bv<1> > OUTPUT_STREAM_V_dest_V_pc_buffer;

            int i = 0;

            while (AESL_token != "[[/transaction]]") {

                bool no_x = false;

                bool err = false;

                while (!no_x) {

                size_t x_found = AESL_token.find('X');

                if (x_found != string::npos) {

                    if (!err) {

                        cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'OUTPUT_STREAM_V_dest_V', possible cause: There are uninitialized variables in the C design." << endl; 

                        err = true;

                    }

                    AESL_token.replace(x_found, 1, "0");

                } else {

                    no_x = true;

                }

                }

                no_x = false;

                while (!no_x) {

                size_t x_found = AESL_token.find('x', 2);

                if (x_found != string::npos) {

                    if (!err) {

                        cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'OUTPUT_STREAM_V_dest_V', possible cause: There are uninitialized variables in the C design." << endl; 

                        err = true;

                    }

                    AESL_token.replace(x_found, 1, "0");

                } else {

                    no_x = true;

                }

                }

                if (AESL_token != "") {

                    OUTPUT_STREAM_V_dest_V_pc_buffer.push_back( AESL_token.c_str() );

                    i++;

                }

                aesl_fh.read(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_dest_V, AESL_token); //data or [[/transaction]]

                if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_OUTPUT_STREAM_V_dest_V)) {

                   exit(1);

                }

            }

            if (i != aesl_tmp_4) {

               aesl_tmp_4 = i;

            }

            if (aesl_tmp_4 > 0 && aesl_tmp_3.size() < aesl_tmp_4) {

                int aesl_tmp_3_size = aesl_tmp_3.size();

                for (int tmp_aesl_tmp_3 = 0 ; tmp_aesl_tmp_3 < aesl_tmp_4 - aesl_tmp_3_size ; tmp_aesl_tmp_3 ++ ) {

                    ap_axiu< 32 ,1 ,1 ,1 > tmp;

                    aesl_tmp_3.push_back(tmp);

                }

            }

            if (i > 0) {

                sc_lv<1> *OUTPUT_STREAM_V_dest_V_lv0_0_0_1_lv1_0_0_1 = new sc_lv<1>[aesl_tmp_4 - aesl_tmp_5];

                AESL_i = 0; //subscript for rtl array

                for (int i_0 = 0; i_0 <= aesl_tmp_4 - aesl_tmp_5 - 1 ; i_0+= 1) {

                    for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

                        if(&(aesl_tmp_3[0].dest) != 0) {

                           OUTPUT_STREAM_V_dest_V_lv0_0_0_1_lv1_0_0_1[0 + AESL_i].range(0, 0) = sc_bv<1>(OUTPUT_STREAM_V_dest_V_pc_buffer[0 + AESL_i].range(0, 0));

                        }

                        AESL_i++;

                    }

                }

                AESL_i = 0; //subscript for rtl array

                for (int i_0 = 0; i_0 <= aesl_tmp_4 - aesl_tmp_5 - 1 ; i_0+= 1) {

                    for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

                        if(&(aesl_tmp_3[0].dest) != 0) {

                           aesl_tmp_3[i_0].dest = (OUTPUT_STREAM_V_dest_V_lv0_0_0_1_lv1_0_0_1[0 + AESL_i]).to_string(SC_BIN).c_str();

                        }

                        AESL_i++;

                    }

                }

                }

        }

        for (int i = 0; i < aesl_tmp_4; i++) {

            OUTPUT_STREAM.write(aesl_tmp_3[i]);

        }

        AESL_transaction_pc ++ ;

    } else {

        static unsigned AESL_transaction;

        static AESL_FILE_HANDLER aesl_fh;

        char* tvin_INPUT_STREAM_V_data_V = new char[50];

        char* wrapc_stream_size_in_INPUT_STREAM_V_data_V = new char[50];

        char* tvin_INPUT_STREAM_V_keep_V = new char[50];

        char* wrapc_stream_size_in_INPUT_STREAM_V_keep_V = new char[50];

        char* tvin_INPUT_STREAM_V_strb_V = new char[50];

        char* wrapc_stream_size_in_INPUT_STREAM_V_strb_V = new char[50];

        char* tvin_INPUT_STREAM_V_user_V = new char[50];

        char* wrapc_stream_size_in_INPUT_STREAM_V_user_V = new char[50];

        char* tvin_INPUT_STREAM_V_last_V = new char[50];

        char* wrapc_stream_size_in_INPUT_STREAM_V_last_V = new char[50];

        char* tvin_INPUT_STREAM_V_id_V = new char[50];

        char* wrapc_stream_size_in_INPUT_STREAM_V_id_V = new char[50];

        char* tvin_INPUT_STREAM_V_dest_V = new char[50];

        char* wrapc_stream_size_in_INPUT_STREAM_V_dest_V = new char[50];

        char* tvout_OUTPUT_STREAM_V_data_V = new char[50];

        char* tvin_OUTPUT_STREAM_V_data_V = new char[50];

        aesl_fh.touch(AUTOTB_TVIN_OUTPUT_STREAM_V_data_V);

        char* wrapc_stream_size_out_OUTPUT_STREAM_V_data_V = new char[50];

        char* tvout_OUTPUT_STREAM_V_keep_V = new char[50];

        char* tvin_OUTPUT_STREAM_V_keep_V = new char[50];

        aesl_fh.touch(AUTOTB_TVIN_OUTPUT_STREAM_V_keep_V);

        char* wrapc_stream_size_out_OUTPUT_STREAM_V_keep_V = new char[50];

        char* tvout_OUTPUT_STREAM_V_strb_V = new char[50];

        char* tvin_OUTPUT_STREAM_V_strb_V = new char[50];

        aesl_fh.touch(AUTOTB_TVIN_OUTPUT_STREAM_V_strb_V);

        char* wrapc_stream_size_out_OUTPUT_STREAM_V_strb_V = new char[50];

        char* tvout_OUTPUT_STREAM_V_user_V = new char[50];

        char* tvin_OUTPUT_STREAM_V_user_V = new char[50];

        aesl_fh.touch(AUTOTB_TVIN_OUTPUT_STREAM_V_user_V);

        char* wrapc_stream_size_out_OUTPUT_STREAM_V_user_V = new char[50];

        char* tvout_OUTPUT_STREAM_V_last_V = new char[50];

        char* tvin_OUTPUT_STREAM_V_last_V = new char[50];

        aesl_fh.touch(AUTOTB_TVIN_OUTPUT_STREAM_V_last_V);

        char* wrapc_stream_size_out_OUTPUT_STREAM_V_last_V = new char[50];

        char* tvout_OUTPUT_STREAM_V_id_V = new char[50];

        char* tvin_OUTPUT_STREAM_V_id_V = new char[50];

        aesl_fh.touch(AUTOTB_TVIN_OUTPUT_STREAM_V_id_V);

        char* wrapc_stream_size_out_OUTPUT_STREAM_V_id_V = new char[50];

        char* tvout_OUTPUT_STREAM_V_dest_V = new char[50];

        char* tvin_OUTPUT_STREAM_V_dest_V = new char[50];

        aesl_fh.touch(AUTOTB_TVIN_OUTPUT_STREAM_V_dest_V);

        char* wrapc_stream_size_out_OUTPUT_STREAM_V_dest_V = new char[50];

        char* tvin_rows = new char[50];

        char* tvin_cols = new char[50];

        static INTER_TCL_FILE tcl_file(INTER_TCL);


        int leading_zero;

        std::vector<ap_axiu< 32 ,1 ,1 ,1 > > aesl_tmp_0;

        int aesl_tmp_1 = 0;

        while (!INPUT_STREAM.empty()) {

            aesl_tmp_0.push_back(INPUT_STREAM.read());

            aesl_tmp_1 ++;

        }

        std::vector<ap_axiu< 32 ,1 ,1 ,1 > > aesl_tmp_3;

        int aesl_tmp_4 = 0;

        while (!OUTPUT_STREAM.empty()) {

            aesl_tmp_3.push_back(OUTPUT_STREAM.read());

            aesl_tmp_4 ++;

        }

        sprintf(tvin_rows, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVIN_rows, tvin_rows);

        sc_bv<32> rows_tvin_wrapc_buffer;

        AESL_i = 0; //subscript for rtl array

        sc_lv<32> rows_tmp_mem; 

        if(&(rows) != 0) {

        rows_tmp_mem = rows;

           rows_tvin_wrapc_buffer.range(31, 0) = rows_tmp_mem.range(31, 0 ) ;

        }

        AESL_i++;

        for (int i = 0; i < 1 ; i++) {

            sprintf(tvin_rows, "%s\n", (rows_tvin_wrapc_buffer).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVIN_rows, tvin_rows);

        }

        tcl_file.set_num(1,&tcl_file.rows_depth);

        sprintf(tvin_rows, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVIN_rows, tvin_rows);

        sprintf(tvin_cols, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVIN_cols, tvin_cols);

        sc_bv<32> cols_tvin_wrapc_buffer;

        AESL_i = 0; //subscript for rtl array

        sc_lv<32> cols_tmp_mem; 

        if(&(cols) != 0) {

        cols_tmp_mem = cols;

           cols_tvin_wrapc_buffer.range(31, 0) = cols_tmp_mem.range(31, 0 ) ;

        }

        AESL_i++;

        for (int i = 0; i < 1 ; i++) {

            sprintf(tvin_cols, "%s\n", (cols_tvin_wrapc_buffer).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVIN_cols, tvin_cols);

        }

        tcl_file.set_num(1,&tcl_file.cols_depth);

        sprintf(tvin_cols, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVIN_cols, tvin_cols);

        for (int i = 0; i < aesl_tmp_1; i++) {

            INPUT_STREAM.write(aesl_tmp_0[i]);

        }

        AESL_ORIG_DUT_image_filter(INPUT_STREAM,OUTPUT_STREAM,rows,cols);

        int aesl_tmp_2 = INPUT_STREAM.size();

        int aesl_tmp_5 = aesl_tmp_4;

        while (!OUTPUT_STREAM.empty()) {

            aesl_tmp_3.push_back(OUTPUT_STREAM.read());

            aesl_tmp_4 ++;

        }

        sprintf(tvin_INPUT_STREAM_V_data_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVIN_INPUT_STREAM_V_data_V, tvin_INPUT_STREAM_V_data_V);

        sc_bv<32> *INPUT_STREAM_V_data_V_tvin_wrapc_buffer = new sc_bv<32>[aesl_tmp_1 - aesl_tmp_2];

        AESL_i = 0; //subscript for rtl array

        for (int i_0 = 0; i_0 <= aesl_tmp_1 - aesl_tmp_2 - 1 ; i_0+= 1) {

        sc_lv<32> INPUT_STREAM_V_data_V_tmp_mem; 

            for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

            sc_lv<32> INPUT_STREAM_V_data_V_tmp_mem; 

                if(&(aesl_tmp_0[0].data) != 0) {

                INPUT_STREAM_V_data_V_tmp_mem = (aesl_tmp_0[i_0].data).to_string(2).c_str();

                   INPUT_STREAM_V_data_V_tvin_wrapc_buffer[0 + AESL_i].range(31, 0) = INPUT_STREAM_V_data_V_tmp_mem.range(31, 0 ) ;

                }

                AESL_i++;

            }

        }

        for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2 ; i++) {

            sprintf(tvin_INPUT_STREAM_V_data_V, "%s\n", (INPUT_STREAM_V_data_V_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVIN_INPUT_STREAM_V_data_V, tvin_INPUT_STREAM_V_data_V);

        }

        tcl_file.set_num(aesl_tmp_1 - aesl_tmp_2,&tcl_file.INPUT_STREAM_V_data_V_depth);

        sprintf(tvin_INPUT_STREAM_V_data_V, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVIN_INPUT_STREAM_V_data_V, tvin_INPUT_STREAM_V_data_V);

        delete [] INPUT_STREAM_V_data_V_tvin_wrapc_buffer;

        sprintf(wrapc_stream_size_in_INPUT_STREAM_V_data_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_data_V, wrapc_stream_size_in_INPUT_STREAM_V_data_V);

        sprintf(wrapc_stream_size_in_INPUT_STREAM_V_data_V, "%d\n", aesl_tmp_1 - aesl_tmp_2);

        aesl_fh.write(WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_data_V, wrapc_stream_size_in_INPUT_STREAM_V_data_V);

        sprintf(wrapc_stream_size_in_INPUT_STREAM_V_data_V, "[[/transaction]] \n");

        aesl_fh.write(WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_data_V, wrapc_stream_size_in_INPUT_STREAM_V_data_V);

        sprintf(tvin_INPUT_STREAM_V_keep_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVIN_INPUT_STREAM_V_keep_V, tvin_INPUT_STREAM_V_keep_V);

        sc_bv<4> *INPUT_STREAM_V_keep_V_tvin_wrapc_buffer = new sc_bv<4>[aesl_tmp_1 - aesl_tmp_2];

        AESL_i = 0; //subscript for rtl array

        for (int i_0 = 0; i_0 <= aesl_tmp_1 - aesl_tmp_2 - 1 ; i_0+= 1) {

        sc_lv<4> INPUT_STREAM_V_keep_V_tmp_mem; 

            for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

            sc_lv<4> INPUT_STREAM_V_keep_V_tmp_mem; 

                if(&(aesl_tmp_0[0].keep) != 0) {

                INPUT_STREAM_V_keep_V_tmp_mem = (aesl_tmp_0[i_0].keep).to_string(2).c_str();

                   INPUT_STREAM_V_keep_V_tvin_wrapc_buffer[0 + AESL_i].range(3, 0) = INPUT_STREAM_V_keep_V_tmp_mem.range(3, 0 ) ;

                }

                AESL_i++;

            }

        }

        for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2 ; i++) {

            sprintf(tvin_INPUT_STREAM_V_keep_V, "%s\n", (INPUT_STREAM_V_keep_V_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVIN_INPUT_STREAM_V_keep_V, tvin_INPUT_STREAM_V_keep_V);

        }

        tcl_file.set_num(aesl_tmp_1 - aesl_tmp_2,&tcl_file.INPUT_STREAM_V_keep_V_depth);

        sprintf(tvin_INPUT_STREAM_V_keep_V, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVIN_INPUT_STREAM_V_keep_V, tvin_INPUT_STREAM_V_keep_V);

        delete [] INPUT_STREAM_V_keep_V_tvin_wrapc_buffer;

        sprintf(wrapc_stream_size_in_INPUT_STREAM_V_keep_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_keep_V, wrapc_stream_size_in_INPUT_STREAM_V_keep_V);

        sprintf(wrapc_stream_size_in_INPUT_STREAM_V_keep_V, "%d\n", aesl_tmp_1 - aesl_tmp_2);

        aesl_fh.write(WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_keep_V, wrapc_stream_size_in_INPUT_STREAM_V_keep_V);

        sprintf(wrapc_stream_size_in_INPUT_STREAM_V_keep_V, "[[/transaction]] \n");

        aesl_fh.write(WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_keep_V, wrapc_stream_size_in_INPUT_STREAM_V_keep_V);

        sprintf(tvin_INPUT_STREAM_V_strb_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVIN_INPUT_STREAM_V_strb_V, tvin_INPUT_STREAM_V_strb_V);

        sc_bv<4> *INPUT_STREAM_V_strb_V_tvin_wrapc_buffer = new sc_bv<4>[aesl_tmp_1 - aesl_tmp_2];

        AESL_i = 0; //subscript for rtl array

        for (int i_0 = 0; i_0 <= aesl_tmp_1 - aesl_tmp_2 - 1 ; i_0+= 1) {

        sc_lv<4> INPUT_STREAM_V_strb_V_tmp_mem; 

            for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

            sc_lv<4> INPUT_STREAM_V_strb_V_tmp_mem; 

                if(&(aesl_tmp_0[0].strb) != 0) {

                INPUT_STREAM_V_strb_V_tmp_mem = (aesl_tmp_0[i_0].strb).to_string(2).c_str();

                   INPUT_STREAM_V_strb_V_tvin_wrapc_buffer[0 + AESL_i].range(3, 0) = INPUT_STREAM_V_strb_V_tmp_mem.range(3, 0 ) ;

                }

                AESL_i++;

            }

        }

        for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2 ; i++) {

            sprintf(tvin_INPUT_STREAM_V_strb_V, "%s\n", (INPUT_STREAM_V_strb_V_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVIN_INPUT_STREAM_V_strb_V, tvin_INPUT_STREAM_V_strb_V);

        }

        tcl_file.set_num(aesl_tmp_1 - aesl_tmp_2,&tcl_file.INPUT_STREAM_V_strb_V_depth);

        sprintf(tvin_INPUT_STREAM_V_strb_V, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVIN_INPUT_STREAM_V_strb_V, tvin_INPUT_STREAM_V_strb_V);

        delete [] INPUT_STREAM_V_strb_V_tvin_wrapc_buffer;

        sprintf(wrapc_stream_size_in_INPUT_STREAM_V_strb_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_strb_V, wrapc_stream_size_in_INPUT_STREAM_V_strb_V);

        sprintf(wrapc_stream_size_in_INPUT_STREAM_V_strb_V, "%d\n", aesl_tmp_1 - aesl_tmp_2);

        aesl_fh.write(WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_strb_V, wrapc_stream_size_in_INPUT_STREAM_V_strb_V);

        sprintf(wrapc_stream_size_in_INPUT_STREAM_V_strb_V, "[[/transaction]] \n");

        aesl_fh.write(WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_strb_V, wrapc_stream_size_in_INPUT_STREAM_V_strb_V);

        sprintf(tvin_INPUT_STREAM_V_user_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVIN_INPUT_STREAM_V_user_V, tvin_INPUT_STREAM_V_user_V);

        sc_bv<1> *INPUT_STREAM_V_user_V_tvin_wrapc_buffer = new sc_bv<1>[aesl_tmp_1 - aesl_tmp_2];

        AESL_i = 0; //subscript for rtl array

        for (int i_0 = 0; i_0 <= aesl_tmp_1 - aesl_tmp_2 - 1 ; i_0+= 1) {

        sc_lv<1> INPUT_STREAM_V_user_V_tmp_mem; 

            for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

            sc_lv<1> INPUT_STREAM_V_user_V_tmp_mem; 

                if(&(aesl_tmp_0[0].user) != 0) {

                INPUT_STREAM_V_user_V_tmp_mem = (aesl_tmp_0[i_0].user).to_string(2).c_str();

                   INPUT_STREAM_V_user_V_tvin_wrapc_buffer[0 + AESL_i].range(0, 0) = INPUT_STREAM_V_user_V_tmp_mem.range(0, 0 ) ;

                }

                AESL_i++;

            }

        }

        for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2 ; i++) {

            sprintf(tvin_INPUT_STREAM_V_user_V, "%s\n", (INPUT_STREAM_V_user_V_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVIN_INPUT_STREAM_V_user_V, tvin_INPUT_STREAM_V_user_V);

        }

        tcl_file.set_num(aesl_tmp_1 - aesl_tmp_2,&tcl_file.INPUT_STREAM_V_user_V_depth);

        sprintf(tvin_INPUT_STREAM_V_user_V, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVIN_INPUT_STREAM_V_user_V, tvin_INPUT_STREAM_V_user_V);

        delete [] INPUT_STREAM_V_user_V_tvin_wrapc_buffer;

        sprintf(wrapc_stream_size_in_INPUT_STREAM_V_user_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_user_V, wrapc_stream_size_in_INPUT_STREAM_V_user_V);

        sprintf(wrapc_stream_size_in_INPUT_STREAM_V_user_V, "%d\n", aesl_tmp_1 - aesl_tmp_2);

        aesl_fh.write(WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_user_V, wrapc_stream_size_in_INPUT_STREAM_V_user_V);

        sprintf(wrapc_stream_size_in_INPUT_STREAM_V_user_V, "[[/transaction]] \n");

        aesl_fh.write(WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_user_V, wrapc_stream_size_in_INPUT_STREAM_V_user_V);

        sprintf(tvin_INPUT_STREAM_V_last_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVIN_INPUT_STREAM_V_last_V, tvin_INPUT_STREAM_V_last_V);

        sc_bv<1> *INPUT_STREAM_V_last_V_tvin_wrapc_buffer = new sc_bv<1>[aesl_tmp_1 - aesl_tmp_2];

        AESL_i = 0; //subscript for rtl array

        for (int i_0 = 0; i_0 <= aesl_tmp_1 - aesl_tmp_2 - 1 ; i_0+= 1) {

        sc_lv<1> INPUT_STREAM_V_last_V_tmp_mem; 

            for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

            sc_lv<1> INPUT_STREAM_V_last_V_tmp_mem; 

                if(&(aesl_tmp_0[0].last) != 0) {

                INPUT_STREAM_V_last_V_tmp_mem = (aesl_tmp_0[i_0].last).to_string(2).c_str();

                   INPUT_STREAM_V_last_V_tvin_wrapc_buffer[0 + AESL_i].range(0, 0) = INPUT_STREAM_V_last_V_tmp_mem.range(0, 0 ) ;

                }

                AESL_i++;

            }

        }

        for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2 ; i++) {

            sprintf(tvin_INPUT_STREAM_V_last_V, "%s\n", (INPUT_STREAM_V_last_V_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVIN_INPUT_STREAM_V_last_V, tvin_INPUT_STREAM_V_last_V);

        }

        tcl_file.set_num(aesl_tmp_1 - aesl_tmp_2,&tcl_file.INPUT_STREAM_V_last_V_depth);

        sprintf(tvin_INPUT_STREAM_V_last_V, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVIN_INPUT_STREAM_V_last_V, tvin_INPUT_STREAM_V_last_V);

        delete [] INPUT_STREAM_V_last_V_tvin_wrapc_buffer;

        sprintf(wrapc_stream_size_in_INPUT_STREAM_V_last_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_last_V, wrapc_stream_size_in_INPUT_STREAM_V_last_V);

        sprintf(wrapc_stream_size_in_INPUT_STREAM_V_last_V, "%d\n", aesl_tmp_1 - aesl_tmp_2);

        aesl_fh.write(WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_last_V, wrapc_stream_size_in_INPUT_STREAM_V_last_V);

        sprintf(wrapc_stream_size_in_INPUT_STREAM_V_last_V, "[[/transaction]] \n");

        aesl_fh.write(WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_last_V, wrapc_stream_size_in_INPUT_STREAM_V_last_V);

        sprintf(tvin_INPUT_STREAM_V_id_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVIN_INPUT_STREAM_V_id_V, tvin_INPUT_STREAM_V_id_V);

        sc_bv<1> *INPUT_STREAM_V_id_V_tvin_wrapc_buffer = new sc_bv<1>[aesl_tmp_1 - aesl_tmp_2];

        AESL_i = 0; //subscript for rtl array

        for (int i_0 = 0; i_0 <= aesl_tmp_1 - aesl_tmp_2 - 1 ; i_0+= 1) {

        sc_lv<1> INPUT_STREAM_V_id_V_tmp_mem; 

            for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

            sc_lv<1> INPUT_STREAM_V_id_V_tmp_mem; 

                if(&(aesl_tmp_0[0].id) != 0) {

                INPUT_STREAM_V_id_V_tmp_mem = (aesl_tmp_0[i_0].id).to_string(2).c_str();

                   INPUT_STREAM_V_id_V_tvin_wrapc_buffer[0 + AESL_i].range(0, 0) = INPUT_STREAM_V_id_V_tmp_mem.range(0, 0 ) ;

                }

                AESL_i++;

            }

        }

        for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2 ; i++) {

            sprintf(tvin_INPUT_STREAM_V_id_V, "%s\n", (INPUT_STREAM_V_id_V_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVIN_INPUT_STREAM_V_id_V, tvin_INPUT_STREAM_V_id_V);

        }

        tcl_file.set_num(aesl_tmp_1 - aesl_tmp_2,&tcl_file.INPUT_STREAM_V_id_V_depth);

        sprintf(tvin_INPUT_STREAM_V_id_V, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVIN_INPUT_STREAM_V_id_V, tvin_INPUT_STREAM_V_id_V);

        delete [] INPUT_STREAM_V_id_V_tvin_wrapc_buffer;

        sprintf(wrapc_stream_size_in_INPUT_STREAM_V_id_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_id_V, wrapc_stream_size_in_INPUT_STREAM_V_id_V);

        sprintf(wrapc_stream_size_in_INPUT_STREAM_V_id_V, "%d\n", aesl_tmp_1 - aesl_tmp_2);

        aesl_fh.write(WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_id_V, wrapc_stream_size_in_INPUT_STREAM_V_id_V);

        sprintf(wrapc_stream_size_in_INPUT_STREAM_V_id_V, "[[/transaction]] \n");

        aesl_fh.write(WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_id_V, wrapc_stream_size_in_INPUT_STREAM_V_id_V);

        sprintf(tvin_INPUT_STREAM_V_dest_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVIN_INPUT_STREAM_V_dest_V, tvin_INPUT_STREAM_V_dest_V);

        sc_bv<1> *INPUT_STREAM_V_dest_V_tvin_wrapc_buffer = new sc_bv<1>[aesl_tmp_1 - aesl_tmp_2];

        AESL_i = 0; //subscript for rtl array

        for (int i_0 = 0; i_0 <= aesl_tmp_1 - aesl_tmp_2 - 1 ; i_0+= 1) {

        sc_lv<1> INPUT_STREAM_V_dest_V_tmp_mem; 

            for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

            sc_lv<1> INPUT_STREAM_V_dest_V_tmp_mem; 

                if(&(aesl_tmp_0[0].dest) != 0) {

                INPUT_STREAM_V_dest_V_tmp_mem = (aesl_tmp_0[i_0].dest).to_string(2).c_str();

                   INPUT_STREAM_V_dest_V_tvin_wrapc_buffer[0 + AESL_i].range(0, 0) = INPUT_STREAM_V_dest_V_tmp_mem.range(0, 0 ) ;

                }

                AESL_i++;

            }

        }

        for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2 ; i++) {

            sprintf(tvin_INPUT_STREAM_V_dest_V, "%s\n", (INPUT_STREAM_V_dest_V_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVIN_INPUT_STREAM_V_dest_V, tvin_INPUT_STREAM_V_dest_V);

        }

        tcl_file.set_num(aesl_tmp_1 - aesl_tmp_2,&tcl_file.INPUT_STREAM_V_dest_V_depth);

        sprintf(tvin_INPUT_STREAM_V_dest_V, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVIN_INPUT_STREAM_V_dest_V, tvin_INPUT_STREAM_V_dest_V);

        delete [] INPUT_STREAM_V_dest_V_tvin_wrapc_buffer;

        sprintf(wrapc_stream_size_in_INPUT_STREAM_V_dest_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_dest_V, wrapc_stream_size_in_INPUT_STREAM_V_dest_V);

        sprintf(wrapc_stream_size_in_INPUT_STREAM_V_dest_V, "%d\n", aesl_tmp_1 - aesl_tmp_2);

        aesl_fh.write(WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_dest_V, wrapc_stream_size_in_INPUT_STREAM_V_dest_V);

        sprintf(wrapc_stream_size_in_INPUT_STREAM_V_dest_V, "[[/transaction]] \n");

        aesl_fh.write(WRAPC_STREAM_SIZE_IN_INPUT_STREAM_V_dest_V, wrapc_stream_size_in_INPUT_STREAM_V_dest_V);

        sprintf(tvout_OUTPUT_STREAM_V_data_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVOUT_OUTPUT_STREAM_V_data_V, tvout_OUTPUT_STREAM_V_data_V);

        sc_bv<32> *OUTPUT_STREAM_V_data_V_tvout_wrapc_buffer = new sc_bv<32>[aesl_tmp_4 - aesl_tmp_5];

        AESL_i = 0; //subscript for rtl array

        for (int i_0 = 0; i_0 <= aesl_tmp_4 - aesl_tmp_5 - 1 ; i_0+= 1) {

        sc_lv<32> OUTPUT_STREAM_V_data_V_tmp_mem; 

            for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

            sc_lv<32> OUTPUT_STREAM_V_data_V_tmp_mem; 

                if(&(aesl_tmp_3[0].data) != 0) {

                OUTPUT_STREAM_V_data_V_tmp_mem = (aesl_tmp_3[i_0].data).to_string(2).c_str();

                   OUTPUT_STREAM_V_data_V_tvout_wrapc_buffer[0 + AESL_i].range(31, 0) = OUTPUT_STREAM_V_data_V_tmp_mem.range(31, 0 ) ;

                }

                AESL_i++;

            }

        }

        for (int i = 0; i < aesl_tmp_4 - aesl_tmp_5 ; i++) {

            sprintf(tvout_OUTPUT_STREAM_V_data_V, "%s\n", (OUTPUT_STREAM_V_data_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVOUT_OUTPUT_STREAM_V_data_V, tvout_OUTPUT_STREAM_V_data_V);

        }

        tcl_file.set_num(aesl_tmp_4 - aesl_tmp_5,&tcl_file.OUTPUT_STREAM_V_data_V_depth);

        sprintf(tvout_OUTPUT_STREAM_V_data_V, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVOUT_OUTPUT_STREAM_V_data_V, tvout_OUTPUT_STREAM_V_data_V);

        delete [] OUTPUT_STREAM_V_data_V_tvout_wrapc_buffer;

        sprintf(wrapc_stream_size_out_OUTPUT_STREAM_V_data_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_data_V, wrapc_stream_size_out_OUTPUT_STREAM_V_data_V);

        sprintf(wrapc_stream_size_out_OUTPUT_STREAM_V_data_V, "%d\n", aesl_tmp_4 - aesl_tmp_5);

        aesl_fh.write(WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_data_V, wrapc_stream_size_out_OUTPUT_STREAM_V_data_V);

        sprintf(wrapc_stream_size_out_OUTPUT_STREAM_V_data_V, "[[/transaction]] \n");

        aesl_fh.write(WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_data_V, wrapc_stream_size_out_OUTPUT_STREAM_V_data_V);

        sprintf(tvout_OUTPUT_STREAM_V_keep_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVOUT_OUTPUT_STREAM_V_keep_V, tvout_OUTPUT_STREAM_V_keep_V);

        sc_bv<4> *OUTPUT_STREAM_V_keep_V_tvout_wrapc_buffer = new sc_bv<4>[aesl_tmp_4 - aesl_tmp_5];

        AESL_i = 0; //subscript for rtl array

        for (int i_0 = 0; i_0 <= aesl_tmp_4 - aesl_tmp_5 - 1 ; i_0+= 1) {

        sc_lv<4> OUTPUT_STREAM_V_keep_V_tmp_mem; 

            for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

            sc_lv<4> OUTPUT_STREAM_V_keep_V_tmp_mem; 

                if(&(aesl_tmp_3[0].keep) != 0) {

                OUTPUT_STREAM_V_keep_V_tmp_mem = (aesl_tmp_3[i_0].keep).to_string(2).c_str();

                   OUTPUT_STREAM_V_keep_V_tvout_wrapc_buffer[0 + AESL_i].range(3, 0) = OUTPUT_STREAM_V_keep_V_tmp_mem.range(3, 0 ) ;

                }

                AESL_i++;

            }

        }

        for (int i = 0; i < aesl_tmp_4 - aesl_tmp_5 ; i++) {

            sprintf(tvout_OUTPUT_STREAM_V_keep_V, "%s\n", (OUTPUT_STREAM_V_keep_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVOUT_OUTPUT_STREAM_V_keep_V, tvout_OUTPUT_STREAM_V_keep_V);

        }

        tcl_file.set_num(aesl_tmp_4 - aesl_tmp_5,&tcl_file.OUTPUT_STREAM_V_keep_V_depth);

        sprintf(tvout_OUTPUT_STREAM_V_keep_V, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVOUT_OUTPUT_STREAM_V_keep_V, tvout_OUTPUT_STREAM_V_keep_V);

        delete [] OUTPUT_STREAM_V_keep_V_tvout_wrapc_buffer;

        sprintf(wrapc_stream_size_out_OUTPUT_STREAM_V_keep_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_keep_V, wrapc_stream_size_out_OUTPUT_STREAM_V_keep_V);

        sprintf(wrapc_stream_size_out_OUTPUT_STREAM_V_keep_V, "%d\n", aesl_tmp_4 - aesl_tmp_5);

        aesl_fh.write(WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_keep_V, wrapc_stream_size_out_OUTPUT_STREAM_V_keep_V);

        sprintf(wrapc_stream_size_out_OUTPUT_STREAM_V_keep_V, "[[/transaction]] \n");

        aesl_fh.write(WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_keep_V, wrapc_stream_size_out_OUTPUT_STREAM_V_keep_V);

        sprintf(tvout_OUTPUT_STREAM_V_strb_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVOUT_OUTPUT_STREAM_V_strb_V, tvout_OUTPUT_STREAM_V_strb_V);

        sc_bv<4> *OUTPUT_STREAM_V_strb_V_tvout_wrapc_buffer = new sc_bv<4>[aesl_tmp_4 - aesl_tmp_5];

        AESL_i = 0; //subscript for rtl array

        for (int i_0 = 0; i_0 <= aesl_tmp_4 - aesl_tmp_5 - 1 ; i_0+= 1) {

        sc_lv<4> OUTPUT_STREAM_V_strb_V_tmp_mem; 

            for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

            sc_lv<4> OUTPUT_STREAM_V_strb_V_tmp_mem; 

                if(&(aesl_tmp_3[0].strb) != 0) {

                OUTPUT_STREAM_V_strb_V_tmp_mem = (aesl_tmp_3[i_0].strb).to_string(2).c_str();

                   OUTPUT_STREAM_V_strb_V_tvout_wrapc_buffer[0 + AESL_i].range(3, 0) = OUTPUT_STREAM_V_strb_V_tmp_mem.range(3, 0 ) ;

                }

                AESL_i++;

            }

        }

        for (int i = 0; i < aesl_tmp_4 - aesl_tmp_5 ; i++) {

            sprintf(tvout_OUTPUT_STREAM_V_strb_V, "%s\n", (OUTPUT_STREAM_V_strb_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVOUT_OUTPUT_STREAM_V_strb_V, tvout_OUTPUT_STREAM_V_strb_V);

        }

        tcl_file.set_num(aesl_tmp_4 - aesl_tmp_5,&tcl_file.OUTPUT_STREAM_V_strb_V_depth);

        sprintf(tvout_OUTPUT_STREAM_V_strb_V, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVOUT_OUTPUT_STREAM_V_strb_V, tvout_OUTPUT_STREAM_V_strb_V);

        delete [] OUTPUT_STREAM_V_strb_V_tvout_wrapc_buffer;

        sprintf(wrapc_stream_size_out_OUTPUT_STREAM_V_strb_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_strb_V, wrapc_stream_size_out_OUTPUT_STREAM_V_strb_V);

        sprintf(wrapc_stream_size_out_OUTPUT_STREAM_V_strb_V, "%d\n", aesl_tmp_4 - aesl_tmp_5);

        aesl_fh.write(WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_strb_V, wrapc_stream_size_out_OUTPUT_STREAM_V_strb_V);

        sprintf(wrapc_stream_size_out_OUTPUT_STREAM_V_strb_V, "[[/transaction]] \n");

        aesl_fh.write(WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_strb_V, wrapc_stream_size_out_OUTPUT_STREAM_V_strb_V);

        sprintf(tvout_OUTPUT_STREAM_V_user_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVOUT_OUTPUT_STREAM_V_user_V, tvout_OUTPUT_STREAM_V_user_V);

        sc_bv<1> *OUTPUT_STREAM_V_user_V_tvout_wrapc_buffer = new sc_bv<1>[aesl_tmp_4 - aesl_tmp_5];

        AESL_i = 0; //subscript for rtl array

        for (int i_0 = 0; i_0 <= aesl_tmp_4 - aesl_tmp_5 - 1 ; i_0+= 1) {

        sc_lv<1> OUTPUT_STREAM_V_user_V_tmp_mem; 

            for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

            sc_lv<1> OUTPUT_STREAM_V_user_V_tmp_mem; 

                if(&(aesl_tmp_3[0].user) != 0) {

                OUTPUT_STREAM_V_user_V_tmp_mem = (aesl_tmp_3[i_0].user).to_string(2).c_str();

                   OUTPUT_STREAM_V_user_V_tvout_wrapc_buffer[0 + AESL_i].range(0, 0) = OUTPUT_STREAM_V_user_V_tmp_mem.range(0, 0 ) ;

                }

                AESL_i++;

            }

        }

        for (int i = 0; i < aesl_tmp_4 - aesl_tmp_5 ; i++) {

            sprintf(tvout_OUTPUT_STREAM_V_user_V, "%s\n", (OUTPUT_STREAM_V_user_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVOUT_OUTPUT_STREAM_V_user_V, tvout_OUTPUT_STREAM_V_user_V);

        }

        tcl_file.set_num(aesl_tmp_4 - aesl_tmp_5,&tcl_file.OUTPUT_STREAM_V_user_V_depth);

        sprintf(tvout_OUTPUT_STREAM_V_user_V, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVOUT_OUTPUT_STREAM_V_user_V, tvout_OUTPUT_STREAM_V_user_V);

        delete [] OUTPUT_STREAM_V_user_V_tvout_wrapc_buffer;

        sprintf(wrapc_stream_size_out_OUTPUT_STREAM_V_user_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_user_V, wrapc_stream_size_out_OUTPUT_STREAM_V_user_V);

        sprintf(wrapc_stream_size_out_OUTPUT_STREAM_V_user_V, "%d\n", aesl_tmp_4 - aesl_tmp_5);

        aesl_fh.write(WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_user_V, wrapc_stream_size_out_OUTPUT_STREAM_V_user_V);

        sprintf(wrapc_stream_size_out_OUTPUT_STREAM_V_user_V, "[[/transaction]] \n");

        aesl_fh.write(WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_user_V, wrapc_stream_size_out_OUTPUT_STREAM_V_user_V);

        sprintf(tvout_OUTPUT_STREAM_V_last_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVOUT_OUTPUT_STREAM_V_last_V, tvout_OUTPUT_STREAM_V_last_V);

        sc_bv<1> *OUTPUT_STREAM_V_last_V_tvout_wrapc_buffer = new sc_bv<1>[aesl_tmp_4 - aesl_tmp_5];

        AESL_i = 0; //subscript for rtl array

        for (int i_0 = 0; i_0 <= aesl_tmp_4 - aesl_tmp_5 - 1 ; i_0+= 1) {

        sc_lv<1> OUTPUT_STREAM_V_last_V_tmp_mem; 

            for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

            sc_lv<1> OUTPUT_STREAM_V_last_V_tmp_mem; 

                if(&(aesl_tmp_3[0].last) != 0) {

                OUTPUT_STREAM_V_last_V_tmp_mem = (aesl_tmp_3[i_0].last).to_string(2).c_str();

                   OUTPUT_STREAM_V_last_V_tvout_wrapc_buffer[0 + AESL_i].range(0, 0) = OUTPUT_STREAM_V_last_V_tmp_mem.range(0, 0 ) ;

                }

                AESL_i++;

            }

        }

        for (int i = 0; i < aesl_tmp_4 - aesl_tmp_5 ; i++) {

            sprintf(tvout_OUTPUT_STREAM_V_last_V, "%s\n", (OUTPUT_STREAM_V_last_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVOUT_OUTPUT_STREAM_V_last_V, tvout_OUTPUT_STREAM_V_last_V);

        }

        tcl_file.set_num(aesl_tmp_4 - aesl_tmp_5,&tcl_file.OUTPUT_STREAM_V_last_V_depth);

        sprintf(tvout_OUTPUT_STREAM_V_last_V, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVOUT_OUTPUT_STREAM_V_last_V, tvout_OUTPUT_STREAM_V_last_V);

        delete [] OUTPUT_STREAM_V_last_V_tvout_wrapc_buffer;

        sprintf(wrapc_stream_size_out_OUTPUT_STREAM_V_last_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_last_V, wrapc_stream_size_out_OUTPUT_STREAM_V_last_V);

        sprintf(wrapc_stream_size_out_OUTPUT_STREAM_V_last_V, "%d\n", aesl_tmp_4 - aesl_tmp_5);

        aesl_fh.write(WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_last_V, wrapc_stream_size_out_OUTPUT_STREAM_V_last_V);

        sprintf(wrapc_stream_size_out_OUTPUT_STREAM_V_last_V, "[[/transaction]] \n");

        aesl_fh.write(WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_last_V, wrapc_stream_size_out_OUTPUT_STREAM_V_last_V);

        sprintf(tvout_OUTPUT_STREAM_V_id_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVOUT_OUTPUT_STREAM_V_id_V, tvout_OUTPUT_STREAM_V_id_V);

        sc_bv<1> *OUTPUT_STREAM_V_id_V_tvout_wrapc_buffer = new sc_bv<1>[aesl_tmp_4 - aesl_tmp_5];

        AESL_i = 0; //subscript for rtl array

        for (int i_0 = 0; i_0 <= aesl_tmp_4 - aesl_tmp_5 - 1 ; i_0+= 1) {

        sc_lv<1> OUTPUT_STREAM_V_id_V_tmp_mem; 

            for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

            sc_lv<1> OUTPUT_STREAM_V_id_V_tmp_mem; 

                if(&(aesl_tmp_3[0].id) != 0) {

                OUTPUT_STREAM_V_id_V_tmp_mem = (aesl_tmp_3[i_0].id).to_string(2).c_str();

                   OUTPUT_STREAM_V_id_V_tvout_wrapc_buffer[0 + AESL_i].range(0, 0) = OUTPUT_STREAM_V_id_V_tmp_mem.range(0, 0 ) ;

                }

                AESL_i++;

            }

        }

        for (int i = 0; i < aesl_tmp_4 - aesl_tmp_5 ; i++) {

            sprintf(tvout_OUTPUT_STREAM_V_id_V, "%s\n", (OUTPUT_STREAM_V_id_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVOUT_OUTPUT_STREAM_V_id_V, tvout_OUTPUT_STREAM_V_id_V);

        }

        tcl_file.set_num(aesl_tmp_4 - aesl_tmp_5,&tcl_file.OUTPUT_STREAM_V_id_V_depth);

        sprintf(tvout_OUTPUT_STREAM_V_id_V, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVOUT_OUTPUT_STREAM_V_id_V, tvout_OUTPUT_STREAM_V_id_V);

        delete [] OUTPUT_STREAM_V_id_V_tvout_wrapc_buffer;

        sprintf(wrapc_stream_size_out_OUTPUT_STREAM_V_id_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_id_V, wrapc_stream_size_out_OUTPUT_STREAM_V_id_V);

        sprintf(wrapc_stream_size_out_OUTPUT_STREAM_V_id_V, "%d\n", aesl_tmp_4 - aesl_tmp_5);

        aesl_fh.write(WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_id_V, wrapc_stream_size_out_OUTPUT_STREAM_V_id_V);

        sprintf(wrapc_stream_size_out_OUTPUT_STREAM_V_id_V, "[[/transaction]] \n");

        aesl_fh.write(WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_id_V, wrapc_stream_size_out_OUTPUT_STREAM_V_id_V);

        sprintf(tvout_OUTPUT_STREAM_V_dest_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVOUT_OUTPUT_STREAM_V_dest_V, tvout_OUTPUT_STREAM_V_dest_V);

        sc_bv<1> *OUTPUT_STREAM_V_dest_V_tvout_wrapc_buffer = new sc_bv<1>[aesl_tmp_4 - aesl_tmp_5];

        AESL_i = 0; //subscript for rtl array

        for (int i_0 = 0; i_0 <= aesl_tmp_4 - aesl_tmp_5 - 1 ; i_0+= 1) {

        sc_lv<1> OUTPUT_STREAM_V_dest_V_tmp_mem; 

            for (int i_1 = 0; i_1 <= 0 ; i_1+= 1) {

            sc_lv<1> OUTPUT_STREAM_V_dest_V_tmp_mem; 

                if(&(aesl_tmp_3[0].dest) != 0) {

                OUTPUT_STREAM_V_dest_V_tmp_mem = (aesl_tmp_3[i_0].dest).to_string(2).c_str();

                   OUTPUT_STREAM_V_dest_V_tvout_wrapc_buffer[0 + AESL_i].range(0, 0) = OUTPUT_STREAM_V_dest_V_tmp_mem.range(0, 0 ) ;

                }

                AESL_i++;

            }

        }

        for (int i = 0; i < aesl_tmp_4 - aesl_tmp_5 ; i++) {

            sprintf(tvout_OUTPUT_STREAM_V_dest_V, "%s\n", (OUTPUT_STREAM_V_dest_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVOUT_OUTPUT_STREAM_V_dest_V, tvout_OUTPUT_STREAM_V_dest_V);

        }

        tcl_file.set_num(aesl_tmp_4 - aesl_tmp_5,&tcl_file.OUTPUT_STREAM_V_dest_V_depth);

        sprintf(tvout_OUTPUT_STREAM_V_dest_V, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVOUT_OUTPUT_STREAM_V_dest_V, tvout_OUTPUT_STREAM_V_dest_V);

        delete [] OUTPUT_STREAM_V_dest_V_tvout_wrapc_buffer;

        sprintf(wrapc_stream_size_out_OUTPUT_STREAM_V_dest_V, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_dest_V, wrapc_stream_size_out_OUTPUT_STREAM_V_dest_V);

        sprintf(wrapc_stream_size_out_OUTPUT_STREAM_V_dest_V, "%d\n", aesl_tmp_4 - aesl_tmp_5);

        aesl_fh.write(WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_dest_V, wrapc_stream_size_out_OUTPUT_STREAM_V_dest_V);

        sprintf(wrapc_stream_size_out_OUTPUT_STREAM_V_dest_V, "[[/transaction]] \n");

        aesl_fh.write(WRAPC_STREAM_SIZE_OUT_OUTPUT_STREAM_V_dest_V, wrapc_stream_size_out_OUTPUT_STREAM_V_dest_V);

        for (int i = 0; i < aesl_tmp_4; i++) {

            OUTPUT_STREAM.write(aesl_tmp_3[i]);

        }

        delete [] tvin_INPUT_STREAM_V_data_V;

        delete [] wrapc_stream_size_in_INPUT_STREAM_V_data_V;

        delete [] tvin_INPUT_STREAM_V_keep_V;

        delete [] wrapc_stream_size_in_INPUT_STREAM_V_keep_V;

        delete [] tvin_INPUT_STREAM_V_strb_V;

        delete [] wrapc_stream_size_in_INPUT_STREAM_V_strb_V;

        delete [] tvin_INPUT_STREAM_V_user_V;

        delete [] wrapc_stream_size_in_INPUT_STREAM_V_user_V;

        delete [] tvin_INPUT_STREAM_V_last_V;

        delete [] wrapc_stream_size_in_INPUT_STREAM_V_last_V;

        delete [] tvin_INPUT_STREAM_V_id_V;

        delete [] wrapc_stream_size_in_INPUT_STREAM_V_id_V;

        delete [] tvin_INPUT_STREAM_V_dest_V;

        delete [] wrapc_stream_size_in_INPUT_STREAM_V_dest_V;

        delete [] tvout_OUTPUT_STREAM_V_data_V;

        delete [] tvin_OUTPUT_STREAM_V_data_V;

        delete [] wrapc_stream_size_out_OUTPUT_STREAM_V_data_V;

        delete [] tvout_OUTPUT_STREAM_V_keep_V;

        delete [] tvin_OUTPUT_STREAM_V_keep_V;

        delete [] wrapc_stream_size_out_OUTPUT_STREAM_V_keep_V;

        delete [] tvout_OUTPUT_STREAM_V_strb_V;

        delete [] tvin_OUTPUT_STREAM_V_strb_V;

        delete [] wrapc_stream_size_out_OUTPUT_STREAM_V_strb_V;

        delete [] tvout_OUTPUT_STREAM_V_user_V;

        delete [] tvin_OUTPUT_STREAM_V_user_V;

        delete [] wrapc_stream_size_out_OUTPUT_STREAM_V_user_V;

        delete [] tvout_OUTPUT_STREAM_V_last_V;

        delete [] tvin_OUTPUT_STREAM_V_last_V;

        delete [] wrapc_stream_size_out_OUTPUT_STREAM_V_last_V;

        delete [] tvout_OUTPUT_STREAM_V_id_V;

        delete [] tvin_OUTPUT_STREAM_V_id_V;

        delete [] wrapc_stream_size_out_OUTPUT_STREAM_V_id_V;

        delete [] tvout_OUTPUT_STREAM_V_dest_V;

        delete [] tvin_OUTPUT_STREAM_V_dest_V;

        delete [] wrapc_stream_size_out_OUTPUT_STREAM_V_dest_V;

        delete [] tvin_rows;

        delete [] tvin_cols;

        AESL_transaction++;

        tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);

    }
}


